'use client'

import type { Incident, TelemetryDataset } from '../../lib/domain/telemetry'
import { buildScopedHref, parseReturnContext, scopeSearchParams } from '../../lib/query/navigation-state'
import { withAppBasePath } from '../../lib/query/internal-href'
import { parseDetailReturnContext } from '../../lib/query/internal-href'
import { useScope } from '../../providers/ScopeProvider'
import styles from './alerts.module.css'
import { useEffect, useState } from 'react'

function absoluteTimestamp(dataset: TelemetryDataset, offsetMs: number): string {
  return new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'medium', timeZone: 'UTC' }).format(
    new Date(Date.parse(dataset.baselineInstant) + offsetMs),
  )
}

function duration(incident: Incident): string {
  const end = incident.resolvedOffsetMs ?? 0
  const milliseconds = Math.max(0, end - incident.startedOffsetMs)
  const minutes = Math.floor(milliseconds / 60_000)
  return `${minutes} min${minutes === 1 ? '' : 's'}${incident.resolvedOffsetMs === null ? ' and ongoing at baseline' : ''}`
}

export function IncidentDetail({ incident, dataset }: Readonly<{ incident: Incident; dataset: TelemetryDataset }>) {
  const { scope } = useScope()
  const [originHref, setOriginHref] = useState('')
  useEffect(() => {
    const synchronize = () => {
      const search = new URLSearchParams(window.location.search)
      setOriginHref(parseDetailReturnContext(search) ?? parseReturnContext(search, ['/', '/alerts', '/alerts/']) ?? '')
    }
    synchronize()
    window.addEventListener('popstate', synchronize)
    return () => window.removeEventListener('popstate', synchronize)
  }, [])
  const returnParams = scopeSearchParams({ environmentId: scope.environmentId, range: scope.range })
  returnParams.set('view', 'incidents')
  const returnHref = originHref || `/alerts/?${returnParams}`
  const incidentHref = buildScopedHref(`/incidents/${incident.id}/`, scope)
  const serviceParams = scopeSearchParams({ environmentId: scope.environmentId, range: scope.range })
  serviceParams.set('return', incidentHref)
  const rule = dataset.alertRules.find(({ id }) => id === incident.ruleId)
  const services = incident.serviceIds.map((id) => dataset.services.find((service) => service.id === id)?.name ?? id)

  return (
    <article className={styles.page}>
      <header className={styles.headingRow}>
        <div>
          <p className={styles.eyebrow}>Incident lifecycle</p>
          <h1>{rule?.name ?? incident.id}</h1>
          <p className={styles.lede}>A complete deterministic incident record generated by a synthetic alert rule. No external incident system is connected.</p>
        </div>
        <c2-badge tone={incident.severity === 'critical' ? 'danger' : 'warning'}>{incident.severity}</c2-badge>
      </header>

      <section className={styles.summaryGrid} aria-label="Incident summary">
        <c2-card>
          <strong slot="header">State</strong>
          <p>{incident.state}</p>
        </c2-card>
        <c2-card>
          <strong slot="header">Owner</strong>
          <p>{incident.owner ?? 'Unassigned — ownership required'}</p>
        </c2-card>
        <c2-card>
          <strong slot="header">Duration</strong>
          <p>{duration(incident)}</p>
        </c2-card>
        <c2-card>
          <strong slot="header">Affected services</strong>
          <p>{services.join(', ')}</p>
        </c2-card>
      </section>

      <section className={`${styles.panel} ${styles.timeline}`} aria-labelledby="timeline-heading">
        <h2 id="timeline-heading">Chronological state history</h2>
        <c2-steps current={incident.timeline.length} marker="icon" aria-label="Incident state history">
          {incident.timeline.map((event, index) => (
            <c2-step
              key={event.id}
              status={index === incident.timeline.length - 1 && incident.state !== 'resolved' ? 'current' : 'success'}
              label={event.state}
              detail={`${event.actor} · ${event.note}`}
              trailing={absoluteTimestamp(dataset, event.offsetMs)}
            />
          ))}
        </c2-steps>
      </section>

      <section className={styles.panel} aria-labelledby="annotations-heading">
        <h2 id="annotations-heading">Annotations</h2>
        <ol className={styles.annotationList}>
          {incident.annotations.map((annotation) => (
            <li key={annotation.id}>
              <strong>{annotation.author}</strong> <span className={styles.timestamp}>{absoluteTimestamp(dataset, annotation.offsetMs)}</span>
              <p>{annotation.body}</p>
            </li>
          ))}
        </ol>
      </section>

      <div className={styles.actions}>
        <c2-link-button href={withAppBasePath(returnHref)}>
          {returnHref === '/' || returnHref.startsWith('/?')
            ? 'Return to overview'
            : returnHref.startsWith('/services/')
              ? 'Return to service detail'
              : 'Return to incidents'}
        </c2-link-button>
        {incident.serviceIds[0] && (
          <c2-link-button href={withAppBasePath(`/services/${incident.serviceIds[0]}/?${serviceParams}`)}>Open affected service</c2-link-button>
        )}
      </div>
    </article>
  )
}
