// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/navigation-menu. Import once, anywhere in the program:
//
//     import '@c2n/navigation-menu/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { NavigationMenu } from '@c2n/navigation-menu'
import type { NavigationMenuItem } from '@c2n/navigation-menu/navigation-menu-item.js'
import type { NavigationMenuLink } from '@c2n/navigation-menu/navigation-menu-link.js'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-navigation-menu': C2Props<NavigationMenu>
      'c2-navigation-menu-item': C2Props<NavigationMenuItem>
      'c2-navigation-menu-link': C2Props<NavigationMenuLink>
    }
  }
}

export {}
