// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/navigation-menu. Import once, anywhere in the program:
//
//     import '@c2n/navigation-menu/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { NavigationMenu, NavigationMenuEventMap } from '@c2n/navigation-menu'
import type { NavigationMenuItem, NavigationMenuItemEventMap } from '@c2n/navigation-menu/navigation-menu-item.js'
import type { NavigationMenuLink } from '@c2n/navigation-menu/navigation-menu-link.js'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-navigation-menu': DefineComponent<
      C2Props<NavigationMenu> & {
        'aria-label'?: unknown
        'open-on'?: unknown
        'open-delay'?: unknown
        'close-delay'?: unknown
        'panel-anchor'?: unknown
        'mobile-breakpoint'?: unknown
        'mobile-label'?: unknown
        'mobile-open'?: unknown
        'auto-current'?: unknown
        'current-url'?: unknown
        onValueChange?: (event: NavigationMenuEventMap['value-change']) => void
      }
    >
    'c2-navigation-menu-item': DefineComponent<
      C2Props<NavigationMenuItem> & {
        'current-group'?: unknown
        onPanelToggle?: (event: NavigationMenuItemEventMap['panel-toggle']) => void
      }
    >
    'c2-navigation-menu-link': DefineComponent<C2Props<NavigationMenuLink>>
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
