// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/month-planner. Import once, anywhere in the program:
//
//     import '@c2n/month-planner/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { EventMapOf } from '@c2n/core/event-helper.js'
import type { MonthPlanner } from '@c2n/month-planner'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes
/** The event an element fires under `name`, read from the map its `addEventListener` carries (its own or inherited). */
type EventOf<T extends EventTarget, Name extends string> = Name extends keyof EventMapOf<T> ? EventMapOf<T>[Name] : CustomEvent

declare module 'vue' {
  interface GlobalComponents {
    'c2-month-planner': DefineComponent<
      C2Props<MonthPlanner> & {
        'week-start'?: unknown
        'month-picker'?: unknown
        'aria-label'?: unknown
        onMonthChange?: (event: EventOf<MonthPlanner, 'month-change'>) => void
        onEventClick?: (event: EventOf<MonthPlanner, 'event-click'>) => void
        onDayClick?: (event: EventOf<MonthPlanner, 'day-click'>) => void
        onEventChange?: (event: EventOf<MonthPlanner, 'event-change'>) => void
        onRangeSelect?: (event: EventOf<MonthPlanner, 'range-select'>) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
