// GENERATED by @c2n/framework-types. Do not edit by hand.
// Every module of @c2n/attachment. Importing this registers each of its elements.

export * from '@c2n/attachment'
export * from '@c2n/attachment/attachment-group.js'
