// GENERATED by @c2n/framework-types. Do not edit by hand.
// Every module of @c2n/details. Importing this registers each of its elements.

export * from '@c2n/details'
export * from '@c2n/details/details-context.js'
