// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/side-nav. Import once, anywhere in the program:
//
//     import '@c2n/side-nav/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { SideNav, SideNavEventMap } from '@c2n/side-nav'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-side-nav': DefineComponent<
      C2Props<SideNav> & {
        'desktop-mode'?: unknown
        'tablet-mode'?: unknown
        'responsive-tablet'?: unknown
        onOpenedChange?: (event: SideNavEventMap['opened-change']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
