import { test, expect, watch, accessible } from '../../../../tests/component-fixture'

test('typing publishes value and Enter submits exactly once then clears', async ({ page, renderScenario }) => {
  await renderScenario('<c2-chat-input aria-label="Message" placeholder="Write a message"></c2-chat-input>')
  const host = page.locator('c2-chat-input')
  await watch(host, 'submit-message')
  await page.getByRole('textbox').fill('Hello')
  await expect(host).toHaveJSProperty('value', 'Hello')
  await page.getByRole('textbox').press('Enter')
  await expect(host).toHaveAttribute('data-events', '["Hello"]')
  await expect(page.getByRole('textbox')).toHaveValue('')
  await accessible(page)
})
test('Alt+Enter inserts a newline without submitting', async ({ page, renderScenario }) => {
  await renderScenario('<c2-chat-input aria-label="Message"></c2-chat-input>')
  const input = page.getByRole('textbox')
  await watch(page.locator('c2-chat-input'), 'submit-message')
  await input.fill('First')
  await input.press('Alt+Enter')
  await input.pressSequentially('Second')
  await expect(input).toHaveValue('First\nSecond')
  await expect(page.locator('c2-chat-input')).toHaveAttribute('data-events', '[]')
})
test('input edits mark the value dirty even without a keyboard event', async ({ page, renderScenario }) => {
  await renderScenario('<c2-chat-input value="Original" aria-label="Message"></c2-chat-input>')
  await page.getByRole('textbox').fill('Pasted')
  await page.locator('c2-chat-input').evaluate((el) => el.setAttribute('value', 'Replacement'))
  await expect(page.getByRole('textbox')).toHaveValue('Pasted')
})
test('participates in forms, validates required and resets its initial value', async ({ page, renderScenario }) => {
  await renderScenario('<form><c2-chat-input name="message" value="Draft" required aria-label="Message"></c2-chat-input></form>')
  const host = page.locator('c2-chat-input')
  const input = page.getByRole('textbox')
  const form = page.locator('form')
  await input.fill('Ready to send')
  await expect.poll(() => form.evaluate((element) => new FormData(element as HTMLFormElement).get('message'))).toBe('Ready to send')
  await input.fill('')
  await expect.poll(() => host.evaluate((element) => (element as HTMLElement & { checkValidity(): boolean }).checkValidity())).toBe(false)
  await form.evaluate((element) => (element as HTMLFormElement).reset())
  await expect(input).toHaveValue('Draft')
  await expect.poll(() => host.evaluate((element) => (element as HTMLElement & { checkValidity(): boolean }).checkValidity())).toBe(true)
})
test('fieldset disabled state prevents chat input submission', async ({ page, renderScenario }) => {
  await renderScenario('<form><fieldset disabled><c2-chat-input name="message" value="Draft" aria-label="Message"></c2-chat-input></fieldset></form>')
  await expect(page.getByRole('textbox')).toBeDisabled()
  await expect.poll(() => page.locator('form').evaluate((element) => new FormData(element as HTMLFormElement).has('message'))).toBe(false)
})
