// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/cascader. Import once, anywhere in the program:
//
//     import '@c2n/cascader/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { Cascader } from '@c2n/cascader'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-cascader': C2Props<Cascader>
    }
  }
}

export {}
