// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/cascader. Import once, anywhere in the program:
//
//     import '@c2n/cascader/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Cascader, CascaderEventMap } from '@c2n/cascader'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-cascader': DefineComponent<
      C2Props<Cascader> & {
        'aria-label'?: unknown
        'change-on-select'?: unknown
        'expand-trigger'?: unknown
        onOpenChange?: (event: CascaderEventMap['open-change']) => void
        onCascaderChange?: (event: CascaderEventMap['cascader-change']) => void
        onInput?: (event: CascaderEventMap['input']) => void
        onChange?: (event: CascaderEventMap['change']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
