// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/dashboard. Import once, anywhere in the program:
//
//     import '@c2n/dashboard/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { DashCard, DashCardEventMap } from '@c2n/dashboard/dash-card.js'
import type { Dashboard, DashboardEventMap } from '@c2n/dashboard'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-dash-card': DefineComponent<
      C2Props<DashCard> & {
        'card-id'?: unknown
        'col-span'?: unknown
        'row-span'?: unknown
        'min-width'?: unknown
        'min-height'?: unknown
        'expand-width'?: unknown
        'expand-height'?: unknown
        'expand-full'?: unknown
        onExpandChange?: (event: DashCardEventMap['expand-change']) => void
      }
    >
    'c2-dashboard': DefineComponent<
      C2Props<Dashboard> & {
        'min-column-width'?: unknown
        'min-row-height'?: unknown
        'storage-key'?: unknown
        onLayoutChange?: (event: DashboardEventMap['layout-change']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
