// GENERATED by scripts/icon-generator from @phosphor-icons/core@2.1.1. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { PhosphorIcon, type PhosphorIconWeight } from '../phosphor-icon'

/**
 * Phosphor `arrow-bend-up-left` icon.
 *
 * @tag c2-phosphor-arrow-bend-up-left
 *
 * @cssproperty {pixel} [--c2-phosphor-icon--size=24px]
 * @cssproperty {color} [--c2-phosphor-icon--color=currentColor]
 */
@customElement('c2-phosphor-arrow-bend-up-left')
export class PhosphorArrowBendUpLeftIcon extends PhosphorIcon {
  protected override renderIcon(weight: PhosphorIconWeight) {
    switch (weight) {
      case 'regular':
        return svg`<path d="M232,200a8,8,0,0,1-16,0,88.1,88.1,0,0,0-88-88H51.31l34.35,34.34a8,8,0,0,1-11.32,11.32l-48-48a8,8,0,0,1,0-11.32l48-48A8,8,0,0,1,85.66,61.66L51.31,96H128A104.11,104.11,0,0,1,232,200Z"/>`
      case 'thin':
        return svg`<path d="M228,200a4,4,0,0,1-8,0,92.1,92.1,0,0,0-92-92H41.66l41.17,41.17a4,4,0,0,1-5.66,5.66l-48-48a4,4,0,0,1,0-5.66l48-48a4,4,0,0,1,5.66,5.66L41.66,100H128A100.11,100.11,0,0,1,228,200Z"/>`
      case 'light':
        return svg`<path d="M230,200a6,6,0,0,1-12,0,90.1,90.1,0,0,0-90-90H46.49l37.75,37.76a6,6,0,1,1-8.48,8.48l-48-48a6,6,0,0,1,0-8.48l48-48a6,6,0,0,1,8.48,8.48L46.49,98H128A102.12,102.12,0,0,1,230,200Z"/>`
      case 'bold':
        return svg`<path d="M236,200a12,12,0,0,1-24,0,84.09,84.09,0,0,0-84-84H61l27.52,27.51a12,12,0,0,1-17,17l-48-48a12,12,0,0,1,0-17l48-48a12,12,0,0,1,17,17L61,92h67A108.12,108.12,0,0,1,236,200Z"/>`
      case 'fill':
        return svg`<path d="M232,200a8,8,0,0,1-16,0,88.1,88.1,0,0,0-88-88H88v40a8,8,0,0,1-13.66,5.66l-48-48a8,8,0,0,1,0-11.32l48-48A8,8,0,0,1,88,56V96h40A104.11,104.11,0,0,1,232,200Z"/>`
      case 'duotone':
        return svg`<path d="M80,56v96L32,104Z" opacity="0.2"/><path d="M128,96H88V56a8,8,0,0,0-13.66-5.66l-48,48a8,8,0,0,0,0,11.32l48,48A8,8,0,0,0,88,152V112h40a88.1,88.1,0,0,1,88,88,8,8,0,0,0,16,0A104.11,104.11,0,0,0,128,96ZM72,132.69,43.31,104,72,75.31Z"/>`
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-phosphor-arrow-bend-up-left': PhosphorArrowBendUpLeftIcon
  }
}
