// GENERATED by scripts/icon-generator from @phosphor-icons/core@2.1.1. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { PhosphorIcon, type PhosphorIconWeight } from '../phosphor-icon'

/**
 * Phosphor `divide` icon.
 *
 * @tag c2-phosphor-divide
 *
 * @cssproperty {pixel} [--c2-phosphor-icon--size=24px]
 * @cssproperty {color} [--c2-phosphor-icon--color=currentColor]
 */
@customElement('c2-phosphor-divide')
export class PhosphorDivideIcon extends PhosphorIcon {
  protected override renderIcon(weight: PhosphorIconWeight) {
    switch (weight) {
      case 'regular':
        return svg`<path d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128ZM128,80a16,16,0,1,0-16-16A16,16,0,0,0,128,80Zm0,96a16,16,0,1,0,16,16A16,16,0,0,0,128,176Z"/>`
      case 'thin':
        return svg`<path d="M220,128a4,4,0,0,1-4,4H40a4,4,0,0,1,0-8H216A4,4,0,0,1,220,128ZM128,76a12,12,0,1,0-12-12A12,12,0,0,0,128,76Zm0,104a12,12,0,1,0,12,12A12,12,0,0,0,128,180Z"/>`
      case 'light':
        return svg`<path d="M222,128a6,6,0,0,1-6,6H40a6,6,0,0,1,0-12H216A6,6,0,0,1,222,128ZM128,78a14,14,0,1,0-14-14A14,14,0,0,0,128,78Zm0,100a14,14,0,1,0,14,14A14,14,0,0,0,128,178Z"/>`
      case 'bold':
        return svg`<path d="M228,128a12,12,0,0,1-12,12H40a12,12,0,0,1,0-24H216A12,12,0,0,1,228,128ZM128,84a20,20,0,1,0-20-20A20,20,0,0,0,128,84Zm0,88a20,20,0,1,0,20,20A20,20,0,0,0,128,172Z"/>`
      case 'fill':
        return svg`<path d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM128,64a16,16,0,1,1-16,16A16,16,0,0,1,128,64Zm0,128a16,16,0,1,1,16-16A16,16,0,0,1,128,192Zm56-56H72a8,8,0,0,1,0-16H184a8,8,0,0,1,0,16Z"/>`
      case 'duotone':
        return svg`<path d="M216,56V200a16,16,0,0,1-16,16H56a16,16,0,0,1-16-16V56A16,16,0,0,1,56,40H200A16,16,0,0,1,216,56Z" opacity="0.2"/><path d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128ZM128,80a16,16,0,1,0-16-16A16,16,0,0,0,128,80Zm0,96a16,16,0,1,0,16,16A16,16,0,0,0,128,176Z"/>`
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-phosphor-divide': PhosphorDivideIcon
  }
}
