// GENERATED by scripts/icon-generator from @phosphor-icons/core@2.1.1. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { PhosphorIcon, type PhosphorIconWeight } from '../phosphor-icon'

/**
 * Phosphor `text-align-justify` icon.
 *
 * @tag c2-phosphor-text-align-justify
 *
 * @cssproperty {pixel} [--c2-phosphor-icon--size=24px]
 * @cssproperty {color} [--c2-phosphor-icon--color=currentColor]
 */
@customElement('c2-phosphor-text-align-justify')
export class PhosphorTextAlignJustifyIcon extends PhosphorIcon {
  protected override renderIcon(weight: PhosphorIconWeight) {
    switch (weight) {
      case 'regular':
        return svg`<path d="M32,64a8,8,0,0,1,8-8H216a8,8,0,0,1,0,16H40A8,8,0,0,1,32,64ZM216,96H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Zm0,40H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Zm0,40H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Z"/>`
      case 'thin':
        return svg`<path d="M36,64a4,4,0,0,1,4-4H216a4,4,0,0,1,0,8H40A4,4,0,0,1,36,64Zm180,36H40a4,4,0,0,0,0,8H216a4,4,0,0,0,0-8Zm0,40H40a4,4,0,0,0,0,8H216a4,4,0,0,0,0-8Zm0,40H40a4,4,0,0,0,0,8H216a4,4,0,0,0,0-8Z"/>`
      case 'light':
        return svg`<path d="M34,64a6,6,0,0,1,6-6H216a6,6,0,0,1,0,12H40A6,6,0,0,1,34,64ZM216,98H40a6,6,0,0,0,0,12H216a6,6,0,0,0,0-12Zm0,40H40a6,6,0,0,0,0,12H216a6,6,0,0,0,0-12Zm0,40H40a6,6,0,0,0,0,12H216a6,6,0,0,0,0-12Z"/>`
      case 'bold':
        return svg`<path d="M28,64A12,12,0,0,1,40,52H216a12,12,0,0,1,0,24H40A12,12,0,0,1,28,64ZM216,92H40a12,12,0,0,0,0,24H216a12,12,0,0,0,0-24Zm0,40H40a12,12,0,0,0,0,24H216a12,12,0,0,0,0-24Zm0,40H40a12,12,0,0,0,0,24H216a12,12,0,0,0,0-24Z"/>`
      case 'fill':
        return svg`<path d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM192,184H64a8,8,0,0,1,0-16H192a8,8,0,0,1,0,16Zm0-32H64a8,8,0,0,1,0-16H192a8,8,0,0,1,0,16Zm0-32H64a8,8,0,0,1,0-16H192a8,8,0,0,1,0,16Zm0-32H64a8,8,0,0,1,0-16H192a8,8,0,0,1,0,16Z"/>`
      case 'duotone':
        return svg`<path d="M216,64V184H40V64Z" opacity="0.2"/><path d="M32,64a8,8,0,0,1,8-8H216a8,8,0,0,1,0,16H40A8,8,0,0,1,32,64ZM216,96H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Zm0,40H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Zm0,40H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Z"/>`
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-phosphor-text-align-justify': PhosphorTextAlignJustifyIcon
  }
}
