// GENERATED by scripts/icon-generator from @phosphor-icons/core@2.1.1. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { PhosphorIcon, type PhosphorIconWeight } from '../phosphor-icon'

/**
 * Phosphor `text-h` icon.
 *
 * @tag c2-phosphor-text-h
 *
 * @cssproperty {pixel} [--c2-phosphor-icon--size=24px]
 * @cssproperty {color} [--c2-phosphor-icon--color=currentColor]
 */
@customElement('c2-phosphor-text-h')
export class PhosphorTextHIcon extends PhosphorIcon {
  protected override renderIcon(weight: PhosphorIconWeight) {
    switch (weight) {
      case 'regular':
        return svg`<path d="M208,56V200a8,8,0,0,1-16,0V136H64v64a8,8,0,0,1-16,0V56a8,8,0,0,1,16,0v64H192V56a8,8,0,0,1,16,0Z"/>`
      case 'thin':
        return svg`<path d="M204,56V200a4,4,0,0,1-8,0V132H60v68a4,4,0,0,1-8,0V56a4,4,0,0,1,8,0v68H196V56a4,4,0,0,1,8,0Z"/>`
      case 'light':
        return svg`<path d="M206,56V200a6,6,0,0,1-12,0V134H62v66a6,6,0,0,1-12,0V56a6,6,0,0,1,12,0v66H194V56a6,6,0,0,1,12,0Z"/>`
      case 'bold':
        return svg`<path d="M212,56V200a12,12,0,0,1-24,0V140H68v60a12,12,0,0,1-24,0V56a12,12,0,0,1,24,0v60H188V56a12,12,0,0,1,24,0Z"/>`
      case 'fill':
        return svg`<path d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM184,176a8,8,0,0,1-16,0V136H88v40a8,8,0,0,1-16,0V80a8,8,0,0,1,16,0v40h80V80a8,8,0,0,1,16,0Z"/>`
      case 'duotone':
        return svg`<path d="M200,56V200H56V56Z" opacity="0.2"/><path d="M208,56V200a8,8,0,0,1-16,0V136H64v64a8,8,0,0,1-16,0V56a8,8,0,0,1,16,0v64H192V56a8,8,0,0,1,16,0Z"/>`
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-phosphor-text-h': PhosphorTextHIcon
  }
}
