// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/kanban. Import once, anywhere in the program:
//
//     import '@c2n/kanban/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below. Structured converter-backed values
// also accept their serialized string form, so server JSX can emit the same JSON/CSV attribute used by HTML.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { Kanban } from '@c2n/kanban'
import type { KanbanColumn } from '@c2n/kanban/kanban-column.js'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>
/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */
type Attribute = string | number | boolean

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-kanban': Omit<C2Props<Kanban>, 'items'> & {
        'item-key'?: Attribute
        'column-field'?: Attribute
        'label-field'?: Attribute
        'description-field'?: Attribute
        items?: Kanban['items'] | string
      }
      'c2-kanban-column': C2Props<KanbanColumn> & {
        'column-id'?: Attribute
      }
    }
  }
}

export {}
