// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/symbols. Import once, anywhere in the program:
//
//     import '@c2n/symbols/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type {
  AccountLockedSymbol,
  AchievementSymbol,
  AgreementSymbol,
  AiAssistantSymbol,
  AllDoneSymbol,
  AnalyticsSymbol,
  AnnouncementSymbol,
  ApiSymbol,
  AppearanceSymbol,
  ArchiveSymbol,
  AttachmentSymbol,
  AutomationSymbol,
  BackupSymbol,
  BiometricSymbol,
  BlockedSymbol,
  BrokenLinkSymbol,
  BugSymbol,
  CallSymbol,
  CameraDeniedSymbol,
  CelebrationSymbol,
  ClipboardSymbol,
  CloudErrorSymbol,
  CoffeeBreakSymbol,
  ConnectedSymbol,
  ContactsSymbol,
  ConversationSymbol,
  CookieConsentSymbol,
  CreateNewSymbol,
  CreditCardSymbol,
  CustomizeSymbol,
  DatabaseSymbol,
  DeliverySymbol,
  DesktopSymbol,
  DisconnectedSymbol,
  DiscountSymbol,
  DocumentSymbol,
  EarningsSymbol,
  EmailVerificationSymbol,
  EmptyBoxSymbol,
  EmptyCartSymbol,
  EmptyFolderSymbol,
  EmptyInboxSymbol,
  EmptyTrashSymbol,
  EmptyWishlistSymbol,
  ErrorSymbol,
  ExpiredSymbol,
  ExploreSymbol,
  ExportSymbol,
  FaqSymbol,
  FeedbackSymbol,
  FolderSharedSymbol,
  ForbiddenSymbol,
  GiftSymbol,
  GoalsSymbol,
  GrowthSymbol,
  GuideSymbol,
  HealthSymbol,
  HelpSymbol,
  HiddenSymbol,
  IdeaSymbol,
  ImportSymbol,
  InfoSymbol,
  InviteSymbol,
  InvoiceSymbol,
  LanguageSymbol,
  LaunchSymbol,
  LearnSymbol,
  LinkSymbol,
  LocationDeniedSymbol,
  LocationSymbol,
  LowBatterySymbol,
  MagicSymbol,
  MailSentSymbol,
  MaintenanceSymbol,
  MicrophoneDeniedSymbol,
  MilestoneSymbol,
  MobileAppSymbol,
  NewMessageSymbol,
  NoBookmarksSymbol,
  NoCodeSymbol,
  NoDataSymbol,
  NoDownloadsSymbol,
  NoEventsSymbol,
  NoFavoritesSymbol,
  NoFilesSymbol,
  NoHistorySymbol,
  NoImagesSymbol,
  NoIntegrationsSymbol,
  NoLocationSymbol,
  NoLogsSymbol,
  NoMediaSymbol,
  NoMessagesSymbol,
  NoMusicSymbol,
  NoNotificationsSymbol,
  NoOrdersSymbol,
  NoResultsSymbol,
  NoReviewsSymbol,
  NoTagsSymbol,
  NoTasksSymbol,
  NoUsersSymbol,
  NotFoundSymbol,
  NotificationSymbol,
  OfflineSymbol,
  OnboardingSymbol,
  OutOfOfficeSymbol,
  PackageDeliveredSymbol,
  PageErrorSymbol,
  PasswordResetSymbol,
  PasswordSymbol,
  PaymentFailedSymbol,
  PaymentSuccessSymbol,
  PendingSymbol,
  PreferencesSymbol,
  PremiumSymbol,
  PrintSymbol,
  ProfileSymbol,
  QrScanSymbol,
  QuietHoursSymbol,
  RateLimitedSymbol,
  ReminderSymbol,
  ReportSymbol,
  ReturnsSymbol,
  SavingsSymbol,
  ScheduledSymbol,
  SearchSymbol,
  SecureSymbol,
  SecurityAlertSymbol,
  ServerErrorSymbol,
  ServerSymbol,
  SetupSymbol,
  ShareSymbol,
  ShoppingBagSymbol,
  SignInSymbol,
  SignOutSymbol,
  SpreadsheetSymbol,
  StorageFullSymbol,
  StoreSymbol,
  SuccessSymbol,
  SupportSymbol,
  SyncingSymbol,
  TeamSymbol,
  TemplatesSymbol,
  ThankYouSymbol,
  TimeoutSymbol,
  TwoFactorSymbol,
  UnlockedSymbol,
  UnsupportedDeviceSymbol,
  UpdateAvailableSymbol,
  UploadFailedSymbol,
  UploadSymbol,
  VaultSymbol,
  VerifiedSymbol,
  VersionControlSymbol,
  VideoCallSymbol,
  WalletSymbol,
  WarningSymbol,
  WelcomeSymbol,
} from '@c2n/symbols'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-symbol-account-locked': DefineComponent<C2Props<AccountLockedSymbol>>
    'c2-symbol-achievement': DefineComponent<C2Props<AchievementSymbol>>
    'c2-symbol-agreement': DefineComponent<C2Props<AgreementSymbol>>
    'c2-symbol-ai-assistant': DefineComponent<C2Props<AiAssistantSymbol>>
    'c2-symbol-all-done': DefineComponent<C2Props<AllDoneSymbol>>
    'c2-symbol-analytics': DefineComponent<C2Props<AnalyticsSymbol>>
    'c2-symbol-announcement': DefineComponent<C2Props<AnnouncementSymbol>>
    'c2-symbol-api': DefineComponent<C2Props<ApiSymbol>>
    'c2-symbol-appearance': DefineComponent<C2Props<AppearanceSymbol>>
    'c2-symbol-archive': DefineComponent<C2Props<ArchiveSymbol>>
    'c2-symbol-attachment': DefineComponent<C2Props<AttachmentSymbol>>
    'c2-symbol-automation': DefineComponent<C2Props<AutomationSymbol>>
    'c2-symbol-backup': DefineComponent<C2Props<BackupSymbol>>
    'c2-symbol-biometric': DefineComponent<C2Props<BiometricSymbol>>
    'c2-symbol-blocked': DefineComponent<C2Props<BlockedSymbol>>
    'c2-symbol-broken-link': DefineComponent<C2Props<BrokenLinkSymbol>>
    'c2-symbol-bug': DefineComponent<C2Props<BugSymbol>>
    'c2-symbol-call': DefineComponent<C2Props<CallSymbol>>
    'c2-symbol-camera-denied': DefineComponent<C2Props<CameraDeniedSymbol>>
    'c2-symbol-celebration': DefineComponent<C2Props<CelebrationSymbol>>
    'c2-symbol-clipboard': DefineComponent<C2Props<ClipboardSymbol>>
    'c2-symbol-cloud-error': DefineComponent<C2Props<CloudErrorSymbol>>
    'c2-symbol-coffee-break': DefineComponent<C2Props<CoffeeBreakSymbol>>
    'c2-symbol-connected': DefineComponent<C2Props<ConnectedSymbol>>
    'c2-symbol-contacts': DefineComponent<C2Props<ContactsSymbol>>
    'c2-symbol-conversation': DefineComponent<C2Props<ConversationSymbol>>
    'c2-symbol-cookie-consent': DefineComponent<C2Props<CookieConsentSymbol>>
    'c2-symbol-create-new': DefineComponent<C2Props<CreateNewSymbol>>
    'c2-symbol-credit-card': DefineComponent<C2Props<CreditCardSymbol>>
    'c2-symbol-customize': DefineComponent<C2Props<CustomizeSymbol>>
    'c2-symbol-database': DefineComponent<C2Props<DatabaseSymbol>>
    'c2-symbol-delivery': DefineComponent<C2Props<DeliverySymbol>>
    'c2-symbol-desktop': DefineComponent<C2Props<DesktopSymbol>>
    'c2-symbol-disconnected': DefineComponent<C2Props<DisconnectedSymbol>>
    'c2-symbol-discount': DefineComponent<C2Props<DiscountSymbol>>
    'c2-symbol-document': DefineComponent<C2Props<DocumentSymbol>>
    'c2-symbol-earnings': DefineComponent<C2Props<EarningsSymbol>>
    'c2-symbol-email-verification': DefineComponent<C2Props<EmailVerificationSymbol>>
    'c2-symbol-empty-box': DefineComponent<C2Props<EmptyBoxSymbol>>
    'c2-symbol-empty-cart': DefineComponent<C2Props<EmptyCartSymbol>>
    'c2-symbol-empty-folder': DefineComponent<C2Props<EmptyFolderSymbol>>
    'c2-symbol-empty-inbox': DefineComponent<C2Props<EmptyInboxSymbol>>
    'c2-symbol-empty-trash': DefineComponent<C2Props<EmptyTrashSymbol>>
    'c2-symbol-empty-wishlist': DefineComponent<C2Props<EmptyWishlistSymbol>>
    'c2-symbol-error': DefineComponent<C2Props<ErrorSymbol>>
    'c2-symbol-expired': DefineComponent<C2Props<ExpiredSymbol>>
    'c2-symbol-explore': DefineComponent<C2Props<ExploreSymbol>>
    'c2-symbol-export': DefineComponent<C2Props<ExportSymbol>>
    'c2-symbol-faq': DefineComponent<C2Props<FaqSymbol>>
    'c2-symbol-feedback': DefineComponent<C2Props<FeedbackSymbol>>
    'c2-symbol-folder-shared': DefineComponent<C2Props<FolderSharedSymbol>>
    'c2-symbol-forbidden': DefineComponent<C2Props<ForbiddenSymbol>>
    'c2-symbol-gift': DefineComponent<C2Props<GiftSymbol>>
    'c2-symbol-goals': DefineComponent<C2Props<GoalsSymbol>>
    'c2-symbol-growth': DefineComponent<C2Props<GrowthSymbol>>
    'c2-symbol-guide': DefineComponent<C2Props<GuideSymbol>>
    'c2-symbol-health': DefineComponent<C2Props<HealthSymbol>>
    'c2-symbol-help': DefineComponent<C2Props<HelpSymbol>>
    'c2-symbol-hidden': DefineComponent<C2Props<HiddenSymbol>>
    'c2-symbol-idea': DefineComponent<C2Props<IdeaSymbol>>
    'c2-symbol-import': DefineComponent<C2Props<ImportSymbol>>
    'c2-symbol-info': DefineComponent<C2Props<InfoSymbol>>
    'c2-symbol-invite': DefineComponent<C2Props<InviteSymbol>>
    'c2-symbol-invoice': DefineComponent<C2Props<InvoiceSymbol>>
    'c2-symbol-language': DefineComponent<C2Props<LanguageSymbol>>
    'c2-symbol-launch': DefineComponent<C2Props<LaunchSymbol>>
    'c2-symbol-learn': DefineComponent<C2Props<LearnSymbol>>
    'c2-symbol-link': DefineComponent<C2Props<LinkSymbol>>
    'c2-symbol-location': DefineComponent<C2Props<LocationSymbol>>
    'c2-symbol-location-denied': DefineComponent<C2Props<LocationDeniedSymbol>>
    'c2-symbol-low-battery': DefineComponent<C2Props<LowBatterySymbol>>
    'c2-symbol-magic': DefineComponent<C2Props<MagicSymbol>>
    'c2-symbol-mail-sent': DefineComponent<C2Props<MailSentSymbol>>
    'c2-symbol-maintenance': DefineComponent<C2Props<MaintenanceSymbol>>
    'c2-symbol-microphone-denied': DefineComponent<C2Props<MicrophoneDeniedSymbol>>
    'c2-symbol-milestone': DefineComponent<C2Props<MilestoneSymbol>>
    'c2-symbol-mobile-app': DefineComponent<C2Props<MobileAppSymbol>>
    'c2-symbol-new-message': DefineComponent<C2Props<NewMessageSymbol>>
    'c2-symbol-no-bookmarks': DefineComponent<C2Props<NoBookmarksSymbol>>
    'c2-symbol-no-code': DefineComponent<C2Props<NoCodeSymbol>>
    'c2-symbol-no-data': DefineComponent<C2Props<NoDataSymbol>>
    'c2-symbol-no-downloads': DefineComponent<C2Props<NoDownloadsSymbol>>
    'c2-symbol-no-events': DefineComponent<C2Props<NoEventsSymbol>>
    'c2-symbol-no-favorites': DefineComponent<C2Props<NoFavoritesSymbol>>
    'c2-symbol-no-files': DefineComponent<C2Props<NoFilesSymbol>>
    'c2-symbol-no-history': DefineComponent<C2Props<NoHistorySymbol>>
    'c2-symbol-no-images': DefineComponent<C2Props<NoImagesSymbol>>
    'c2-symbol-no-integrations': DefineComponent<C2Props<NoIntegrationsSymbol>>
    'c2-symbol-no-location': DefineComponent<C2Props<NoLocationSymbol>>
    'c2-symbol-no-logs': DefineComponent<C2Props<NoLogsSymbol>>
    'c2-symbol-no-media': DefineComponent<C2Props<NoMediaSymbol>>
    'c2-symbol-no-messages': DefineComponent<C2Props<NoMessagesSymbol>>
    'c2-symbol-no-music': DefineComponent<C2Props<NoMusicSymbol>>
    'c2-symbol-no-notifications': DefineComponent<C2Props<NoNotificationsSymbol>>
    'c2-symbol-no-orders': DefineComponent<C2Props<NoOrdersSymbol>>
    'c2-symbol-no-results': DefineComponent<C2Props<NoResultsSymbol>>
    'c2-symbol-no-reviews': DefineComponent<C2Props<NoReviewsSymbol>>
    'c2-symbol-no-tags': DefineComponent<C2Props<NoTagsSymbol>>
    'c2-symbol-no-tasks': DefineComponent<C2Props<NoTasksSymbol>>
    'c2-symbol-no-users': DefineComponent<C2Props<NoUsersSymbol>>
    'c2-symbol-not-found': DefineComponent<C2Props<NotFoundSymbol>>
    'c2-symbol-notification': DefineComponent<C2Props<NotificationSymbol>>
    'c2-symbol-offline': DefineComponent<C2Props<OfflineSymbol>>
    'c2-symbol-onboarding': DefineComponent<C2Props<OnboardingSymbol>>
    'c2-symbol-out-of-office': DefineComponent<C2Props<OutOfOfficeSymbol>>
    'c2-symbol-package-delivered': DefineComponent<C2Props<PackageDeliveredSymbol>>
    'c2-symbol-page-error': DefineComponent<C2Props<PageErrorSymbol>>
    'c2-symbol-password': DefineComponent<C2Props<PasswordSymbol>>
    'c2-symbol-password-reset': DefineComponent<C2Props<PasswordResetSymbol>>
    'c2-symbol-payment-failed': DefineComponent<C2Props<PaymentFailedSymbol>>
    'c2-symbol-payment-success': DefineComponent<C2Props<PaymentSuccessSymbol>>
    'c2-symbol-pending': DefineComponent<C2Props<PendingSymbol>>
    'c2-symbol-preferences': DefineComponent<C2Props<PreferencesSymbol>>
    'c2-symbol-premium': DefineComponent<C2Props<PremiumSymbol>>
    'c2-symbol-print': DefineComponent<C2Props<PrintSymbol>>
    'c2-symbol-profile': DefineComponent<C2Props<ProfileSymbol>>
    'c2-symbol-qr-scan': DefineComponent<C2Props<QrScanSymbol>>
    'c2-symbol-quiet-hours': DefineComponent<C2Props<QuietHoursSymbol>>
    'c2-symbol-rate-limited': DefineComponent<C2Props<RateLimitedSymbol>>
    'c2-symbol-reminder': DefineComponent<C2Props<ReminderSymbol>>
    'c2-symbol-report': DefineComponent<C2Props<ReportSymbol>>
    'c2-symbol-returns': DefineComponent<C2Props<ReturnsSymbol>>
    'c2-symbol-savings': DefineComponent<C2Props<SavingsSymbol>>
    'c2-symbol-scheduled': DefineComponent<C2Props<ScheduledSymbol>>
    'c2-symbol-search': DefineComponent<C2Props<SearchSymbol>>
    'c2-symbol-secure': DefineComponent<C2Props<SecureSymbol>>
    'c2-symbol-security-alert': DefineComponent<C2Props<SecurityAlertSymbol>>
    'c2-symbol-server': DefineComponent<C2Props<ServerSymbol>>
    'c2-symbol-server-error': DefineComponent<C2Props<ServerErrorSymbol>>
    'c2-symbol-setup': DefineComponent<C2Props<SetupSymbol>>
    'c2-symbol-share': DefineComponent<C2Props<ShareSymbol>>
    'c2-symbol-shopping-bag': DefineComponent<C2Props<ShoppingBagSymbol>>
    'c2-symbol-sign-in': DefineComponent<C2Props<SignInSymbol>>
    'c2-symbol-sign-out': DefineComponent<C2Props<SignOutSymbol>>
    'c2-symbol-spreadsheet': DefineComponent<C2Props<SpreadsheetSymbol>>
    'c2-symbol-storage-full': DefineComponent<C2Props<StorageFullSymbol>>
    'c2-symbol-store': DefineComponent<C2Props<StoreSymbol>>
    'c2-symbol-success': DefineComponent<C2Props<SuccessSymbol>>
    'c2-symbol-support': DefineComponent<C2Props<SupportSymbol>>
    'c2-symbol-syncing': DefineComponent<C2Props<SyncingSymbol>>
    'c2-symbol-team': DefineComponent<C2Props<TeamSymbol>>
    'c2-symbol-templates': DefineComponent<C2Props<TemplatesSymbol>>
    'c2-symbol-thank-you': DefineComponent<C2Props<ThankYouSymbol>>
    'c2-symbol-timeout': DefineComponent<C2Props<TimeoutSymbol>>
    'c2-symbol-two-factor': DefineComponent<C2Props<TwoFactorSymbol>>
    'c2-symbol-unlocked': DefineComponent<C2Props<UnlockedSymbol>>
    'c2-symbol-unsupported-device': DefineComponent<C2Props<UnsupportedDeviceSymbol>>
    'c2-symbol-update-available': DefineComponent<C2Props<UpdateAvailableSymbol>>
    'c2-symbol-upload': DefineComponent<C2Props<UploadSymbol>>
    'c2-symbol-upload-failed': DefineComponent<C2Props<UploadFailedSymbol>>
    'c2-symbol-vault': DefineComponent<C2Props<VaultSymbol>>
    'c2-symbol-verified': DefineComponent<C2Props<VerifiedSymbol>>
    'c2-symbol-version-control': DefineComponent<C2Props<VersionControlSymbol>>
    'c2-symbol-video-call': DefineComponent<C2Props<VideoCallSymbol>>
    'c2-symbol-wallet': DefineComponent<C2Props<WalletSymbol>>
    'c2-symbol-warning': DefineComponent<C2Props<WarningSymbol>>
    'c2-symbol-welcome': DefineComponent<C2Props<WelcomeSymbol>>
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
