// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/symbols. Import once, anywhere in the program:
//
//     import '@c2n/symbols/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type {
  AllDoneSymbol,
  EmptyBoxSymbol,
  EmptyCartSymbol,
  EmptyFolderSymbol,
  EmptyInboxSymbol,
  ErrorSymbol,
  ExpiredSymbol,
  ForbiddenSymbol,
  IdeaSymbol,
  InfoSymbol,
  LaunchSymbol,
  MailSentSymbol,
  MaintenanceSymbol,
  NoDataSymbol,
  NoEventsSymbol,
  NoMessagesSymbol,
  NoNotificationsSymbol,
  NoResultsSymbol,
  NoUsersSymbol,
  NotFoundSymbol,
  OfflineSymbol,
  SearchSymbol,
  SecureSymbol,
  ServerErrorSymbol,
  SuccessSymbol,
  UploadSymbol,
  WarningSymbol,
} from '@c2n/symbols'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-symbol-all-done': DefineComponent<C2Props<AllDoneSymbol>>
    'c2-symbol-empty-box': DefineComponent<C2Props<EmptyBoxSymbol>>
    'c2-symbol-empty-cart': DefineComponent<C2Props<EmptyCartSymbol>>
    'c2-symbol-empty-folder': DefineComponent<C2Props<EmptyFolderSymbol>>
    'c2-symbol-empty-inbox': DefineComponent<C2Props<EmptyInboxSymbol>>
    'c2-symbol-error': DefineComponent<C2Props<ErrorSymbol>>
    'c2-symbol-expired': DefineComponent<C2Props<ExpiredSymbol>>
    'c2-symbol-forbidden': DefineComponent<C2Props<ForbiddenSymbol>>
    'c2-symbol-idea': DefineComponent<C2Props<IdeaSymbol>>
    'c2-symbol-info': DefineComponent<C2Props<InfoSymbol>>
    'c2-symbol-launch': DefineComponent<C2Props<LaunchSymbol>>
    'c2-symbol-mail-sent': DefineComponent<C2Props<MailSentSymbol>>
    'c2-symbol-maintenance': DefineComponent<C2Props<MaintenanceSymbol>>
    'c2-symbol-no-data': DefineComponent<C2Props<NoDataSymbol>>
    'c2-symbol-no-events': DefineComponent<C2Props<NoEventsSymbol>>
    'c2-symbol-no-messages': DefineComponent<C2Props<NoMessagesSymbol>>
    'c2-symbol-no-notifications': DefineComponent<C2Props<NoNotificationsSymbol>>
    'c2-symbol-no-results': DefineComponent<C2Props<NoResultsSymbol>>
    'c2-symbol-no-users': DefineComponent<C2Props<NoUsersSymbol>>
    'c2-symbol-not-found': DefineComponent<C2Props<NotFoundSymbol>>
    'c2-symbol-offline': DefineComponent<C2Props<OfflineSymbol>>
    'c2-symbol-search': DefineComponent<C2Props<SearchSymbol>>
    'c2-symbol-secure': DefineComponent<C2Props<SecureSymbol>>
    'c2-symbol-server-error': DefineComponent<C2Props<ServerErrorSymbol>>
    'c2-symbol-success': DefineComponent<C2Props<SuccessSymbol>>
    'c2-symbol-upload': DefineComponent<C2Props<UploadSymbol>>
    'c2-symbol-warning': DefineComponent<C2Props<WarningSymbol>>
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
