// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/tree. Import once, anywhere in the program:
//
//     import '@c2n/tree/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { Tree } from '@c2n/tree'
import type { TreeItem } from '@c2n/tree/tree-item.js'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>
/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */
type Attribute = string | number | boolean

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-tree': C2Props<Tree> & {
        'expanded-items'?: Attribute
        'checkbox-selection'?: Attribute
        'selection-propagation'?: Attribute
        'children-outline'?: Attribute
        'expand-on-click'?: Attribute
      }
      'c2-tree-item': C2Props<TreeItem> & {
        'has-children'?: Attribute
        'children-outline'?: Attribute
      }
    }
  }
}

export {}
