import { formControlModel, type DiscoveredPackage } from './manifests.ts'

/**
 * A tsconfig fragment that teaches Volar which property `v-model` writes on a c2 form control.
 *
 * Volar assumes `modelValue` for anything it resolves as a component, and registering the tags in
 * `GlobalComponents` is what makes it resolve them at all — so without this, `v-model="query"` on a
 * `c2-text-field` type-checks against a prop the element does not have, even though the *runtime* compiler
 * (which goes by `isCustomElement`) correctly writes `value` and listens for `input`.
 *
 * `experimentalModelPropName` replaces Volar's defaults rather than merging with them, so the native entries are
 * repeated here.
 */
export function emitVueTsconfig(packages: DiscoveredPackage[], version: string): string {
  const value: Record<string, true> = {}
  const checked: Record<string, true> = {}

  for (const pkg of packages) {
    for (const element of pkg.elements) {
      const model = formControlModel(element)
      if (model === 'checked') checked[element.tagName] = true
      else if (model === 'value') value[element.tagName] = true
    }
  }

  const sorted = (entries: Record<string, true>) =>
    Object.fromEntries(
      Object.keys(entries)
        .sort()
        .map((tag) => [tag, true]),
    )

  return `${JSON.stringify(
    {
      $comment: `GENERATED by @c2n/framework-types@${version}. Do not edit by hand. Add to a Vue app's tsconfig: "extends": ["@c2n/config/tsconfig.lib.json", "@c2n/framework-types/tsconfig.vue.json"] — and declare no "vueCompilerOptions" of your own, because a local one replaces the inherited object rather than merging with it.`,
      vueCompilerOptions: {
        // The point of the generated `vue.d.ts` files: without it Volar checks nothing in a template.
        strictTemplates: true,
        experimentalModelPropName: {
          // Volar's own defaults, repeated because this option is replaced rather than merged.
          '': { input: true },
          value: { input: { type: 'text' }, textarea: true, select: true, ...sorted(value) },
          checked: sorted(checked),
        },
      },
    },
    null,
    2,
  )}\n`
}
