import type { CustomElement, DiscoveredPackage } from './manifests.ts'

const BANNER = '// GENERATED by @c2n/framework-types. Do not edit by hand.'

/**
 * JSX declarations for one package's tags.
 *
 * The props are derived from the element class rather than listed one by one, so a renamed or removed property
 * breaks the consumer's build instead of silently doing nothing at runtime. `HTMLAttributes` brings the standard
 * DOM attributes (`className`, `style`, `slot`, `ref`, `key`, …) that React understands for any host element.
 *
 * A kebab-case attribute whose property is camelCase is listed by its markup name as well (`'row-key'` next to
 * `rowKey`). That is the spelling a server-rendered page needs: React writes a custom element's props to the
 * HTML verbatim, the parser lowercases them and hydration never sets the property, so `rowKey="id"` reaches the
 * element as `rowkey` while `row-key="id"` reaches it as written.
 *
 * Events are deliberately absent: React has no JSX spelling for a kebab-case event name, and its `onChange` is a
 * synthetic form-control event of its own. Attach those with a ref and `addEventListener` — the element's own
 * `addEventListener` overloads type the detail (see `@c2n/core/event-helper.js`).
 */
export function emitReact(pkg: DiscoveredPackage): string {
  const imports = new Map<string, Set<string>>()
  const needsAttribute = pkg.elements.some((element) => element.attributes.some((attribute) => attribute.name !== attribute.fieldName))
  for (const element of pkg.elements) {
    if (!imports.has(element.module)) imports.set(element.module, new Set())
    imports.get(element.module)!.add(element.className)
  }

  const entry = (element: CustomElement) => {
    const aliases = element.attributes.filter((attribute) => attribute.name !== attribute.fieldName)
    const serialized = element.attributes.filter((attribute) => /\[\]|Array<|Record<|\bobject\b/.test(attribute.type ?? ''))
    const overridden = [...new Set(serialized.map((attribute) => attribute.fieldName))]
    const base =
      overridden.length > 0 ? `Omit<C2Props<${element.className}>, ${overridden.map((name) => `'${name}'`).join(' | ')}>` : `C2Props<${element.className}>`
    const extras = [
      ...aliases.map((attribute) => `        '${attribute.name}'?: Attribute`),
      ...serialized.map((attribute) => `        '${attribute.fieldName}'?: ${element.className}['${attribute.fieldName}'] | string`),
    ]
    if (extras.length === 0) return `      '${element.tagName}': ${base}`
    return [`      '${element.tagName}': ${base} & {`, ...[...new Set(extras)], `      }`].join('\n')
  }

  const lines = [
    BANNER,
    `//`,
    `// JSX types for the custom elements of ${pkg.name}. Import once, anywhere in the program:`,
    `//`,
    `//     import '${pkg.name}/react'`,
    `//`,
    `// Register the elements at module scope before React renders, or React writes an object prop as an`,
    `// attribute and it stringifies.`,
    `//`,
    `// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute`,
    `// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not`,
    `// set properties. Those names are listed next to the properties below. Structured converter-backed values`,
    `// also accept their serialized string form, so server JSX can emit the same JSON/CSV attribute used by HTML.`,
    ``,
    `import type { DetailedHTMLProps, HTMLAttributes } from 'react'`,
    ...[...imports].map(([module, names]) => `import type { ${[...names].sort().join(', ')} } from '${module}'`),
    ``,
    `/** Standard React host-element attributes plus the element's own public properties. */`,
    `type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>`,
    ...(needsAttribute
      ? [
          `/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */`,
          `type Attribute = string | number | boolean`,
        ]
      : []),
    ``,
    `declare module 'react' {`,
    `  namespace JSX {`,
    `    interface IntrinsicElements {`,
    ...pkg.elements.map(entry),
    `    }`,
    `  }`,
    `}`,
    ``,
    `export {}`,
    ``,
  ]

  return lines.join('\n')
}

/**
 * Vue declarations for one package's tags.
 *
 * Volar resolves a hyphenated tag against `GlobalComponents`, so that is what makes `strictTemplates` accept
 * `<c2-button>` and reject a misspelt property or a handler with the wrong detail type. Attributes are listed by
 * their real markup name as well, because a template may use either spelling.
 *
 * `HTMLAttributes` is widened with `slot`, which Vue's own definition omits: slotting a plain `<span slot="…">`
 * into a component is the normal way to use these elements, and `strictTemplates` would otherwise reject it.
 */
export function emitVue(pkg: DiscoveredPackage): string {
  const imports = new Map<string, Set<string>>()
  for (const element of pkg.elements) {
    if (!imports.has(element.module)) imports.set(element.module, new Set())
    const names = imports.get(element.module)!
    names.add(element.className)
    // The event map, not each detail interface: it lives in the same module as the class, so it always imports.
    if (element.events.length > 0) names.add(`${element.className}EventMap`)
  }

  const entry = (element: CustomElement) => {
    // A kebab attribute whose property is camelCase has to be listed by hand: `Omit<T, keyof HTMLElement>` only
    // carries the property spelling, and a template may legitimately use either.
    const attributes = element.attributes.filter((attribute) => attribute.name !== attribute.fieldName).map((attribute) => `'${attribute.name}'?: unknown`)
    const events = element.events.map((event) => `'on${handlerName(event.name)}'?: (event: ${element.className}EventMap['${event.name}']) => void`)
    const extras = [...new Set([...attributes, ...events])]
    const props =
      extras.length === 0 ? `C2Props<${element.className}>` : `C2Props<${element.className}> & {\n${extras.map((line) => `      ${line}`).join('\n')}\n    }`
    return `    '${element.tagName}': DefineComponent<${props}>`
  }

  return [
    BANNER,
    `//`,
    `// Vue template types for the custom elements of ${pkg.name}. Import once, anywhere in the program:`,
    `//`,
    `//     import '${pkg.name}/vue'`,
    `//`,
    `// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders`,
    `// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.`,
    ``,
    `import type { DefineComponent, HTMLAttributes } from 'vue'`,
    ...[...imports].map(([module, names]) => `import type { ${[...names].sort().join(', ')} } from '${module}'`),
    ``,
    `/** The element's own public properties, plus every attribute Vue understands on a host element. */`,
    `type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes`,
    ``,
    `declare module 'vue' {`,
    `  interface GlobalComponents {`,
    ...pkg.elements.map(entry),
    `  }`,
    `}`,
    ``,
    `declare module '@vue/runtime-dom' {`,
    `  interface HTMLAttributes {`,
    `    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */`,
    `    slot?: string`,
    `  }`,
    `}`,
    ``,
    `export {}`,
    ``,
  ].join('\n')
}

/** \`selection-change\` → \`SelectionChange\`, the spelling Volar resolves a \`@selection-change\` binding to. */
function handlerName(event: string): string {
  return event.replace(/(^|-)([a-z])/g, (_match, _separator, letter: string) => letter.toUpperCase())
}
