/**
 * `@c2n/components`, the one-install package: every component package as a dependency, one entry per package,
 * a barrel that registers them all, and the JSX / Vue declarations of every tag behind a single import.
 *
 * The package holds no component code. Each entry re-exports the real `@c2n/<name>` package, so a program that
 * reaches a component through the umbrella and through its own package loads one module, one class and one
 * `customElements.define`. Everything here is derived from the discovered packages, so a new component joins the
 * umbrella by being built, with no list to maintain.
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { DiscoveredPackage, Framework } from './manifests.ts'

const BANNER = '// GENERATED by @c2n/framework-types. Do not edit by hand.'

/**
 * Icon sets stay out: Phosphor alone is 1,512 elements, and a barrel import of the umbrella would register all
 * of them. They remain their own install, with their own per-icon entry points.
 */
const EXCLUDED = new Set(['@c2n/feather-icons', '@c2n/phosphor-icons', '@c2n/symbols', '@c2n/task-icons'])

/** The theme is part of "everything", but it ships stylesheets rather than elements, so discovery never sees it. */
const THEME = '@c2n/theme'
const THEME_STYLESHEETS = ['theme.css', 'base.css', 'tokens.css']

/** Keys of the umbrella's `package.json` that the generator owns; everything else is hand-written. */
const GENERATED_KEYS = ['exports', 'files', 'dependencies', 'peerDependencies', 'peerDependenciesMeta']

interface PackageJson {
  name: string
  version: string
  exports?: Record<string, { types?: string } | string>
  peerDependencies?: Record<string, string>
  peerDependenciesMeta?: Record<string, { optional?: boolean }>
  [key: string]: unknown
}

export interface UmbrellaEntry {
  /** npm package, e.g. `@c2n/table`. */
  pkg: string
  /** Subpath of the umbrella, and the name of its file under `lib/`, e.g. `table`. */
  name: string
  /** Every JavaScript module of the package, e.g. `@c2n/table`, `@c2n/table/table-column.js`. */
  modules: string[]
  /**
   * Frameworks the package ships a binding for (`@c2n/table/react`). The binding imports its framework, so it is
   * never part of the entry (`import '@c2n/components'` would load React and Vue); `@c2n/components/react` and
   * `/vue` re-export it instead.
   */
  frameworks: Framework[]
}

export interface UmbrellaFile {
  /** Path relative to the umbrella package. */
  path: string
  contents: string
  parser: 'typescript' | 'json-stringify' | 'css'
}

function readJson(file: string): PackageJson {
  return JSON.parse(readFileSync(file, 'utf8')) as PackageJson
}

/**
 * The umbrella's entries, one per component package. An entry re-exports every JavaScript subpath the package
 * publishes, not just its root: `@c2n/table`'s root does not re-export `TableColumn`, and importing the entry has
 * to register every tag the package defines.
 */
export function umbrellaEntries(packages: DiscoveredPackage[]): UmbrellaEntry[] {
  return packages
    .filter((pkg) => !EXCLUDED.has(pkg.name))
    .map((pkg) => {
      const exports = readJson(join(pkg.dir, 'package.json')).exports ?? {}
      const subpaths = Object.entries(exports)
        // A wildcard subpath (`@c2n/chart/maps/*.js`) publishes data modules an element loads on demand; re-exporting
        // them would make the barrel load every one of them up front.
        .filter(([subpath, entry]) => subpath !== '.' && subpath.endsWith('.js') && !subpath.includes('*') && typeof entry !== 'string' && entry.types)
        .map(([subpath]) => `${pkg.name}/${subpath.slice(2)}`)
      return {
        pkg: pkg.name,
        name: pkg.name.slice('@c2n/'.length),
        modules: [...(exports['.'] ? [pkg.name] : []), ...subpaths.sort()],
        frameworks: pkg.bindings,
      }
    })
}

export function emitUmbrella(packages: DiscoveredPackage[], umbrellaDir: string, scopeDir: string): UmbrellaFile[] {
  const entries = umbrellaEntries(packages)
  const files: UmbrellaFile[] = []
  const reexports = (modules: string[]) => modules.map((module) => `export * from '${module}'`)

  for (const entry of entries) {
    const body = [BANNER, `// Every module of ${entry.pkg}. Importing this registers each of its elements.`, ``, ...reexports(entry.modules), ``].join('\n')
    files.push({ path: `lib/${entry.name}.js`, contents: body, parser: 'typescript' })
    files.push({ path: `lib/${entry.name}.d.ts`, contents: body, parser: 'typescript' })
  }

  const barrel = [
    BANNER,
    `//`,
    `// Every c2n component. Importing this module registers all of them, and no bundler can tree-shake a`,
    `// registration away: an application that ships to users should import the components it uses instead:`,
    `//`,
    `//     import '@c2n/components/button'`,
    ``,
    ...reexports(entries.map((entry) => `./lib/${entry.name}.js`)),
    ``,
  ].join('\n')
  files.push({ path: 'index.js', contents: barrel, parser: 'typescript' })
  files.push({ path: 'index.d.ts', contents: barrel, parser: 'typescript' })

  // A package's `/react` and `/vue` either only declare types (imported for their side effect) or also carry the
  // package's binding (re-exported, so `import { useRenderedRows } from '@c2n/components/react'` works). Two bindings
  // exporting the same name fail the umbrella's type-check rather than silently dropping one.
  const withBinding = (framework: Framework) => entries.filter((entry) => entry.frameworks.includes(framework))
  const typesEntry = (framework: Framework, usage: string[]) =>
    [
      BANNER,
      `//`,
      `// ${framework === 'react' ? 'JSX' : 'Vue template'} types for every c2n component. Import once, anywhere in the program:`,
      `//`,
      `//     import '@c2n/components/${framework}'`,
      `//`,
      ...usage.map((line) => (line ? `// ${line}` : `//`)),
      ``,
      ...entries.map((entry) => (entry.frameworks.includes(framework) ? `export * from '${entry.pkg}/${framework}'` : `import '${entry.pkg}/${framework}'`)),
      ``,
      `export {}`,
      ``,
    ].join('\n')
  const bindingUsage = (framework: Framework) => {
    const packages = withBinding(framework).map((entry) => entry.pkg)
    if (packages.length === 0) return []
    return [
      ``,
      `It also re-exports the ${framework === 'react' ? 'hooks' : 'composables'} of ${packages.join(', ')}, which import ${framework === 'react' ? 'React' : 'Vue'}.`,
    ]
  }
  files.push({
    path: 'react.d.ts',
    contents: typesEntry('react', [
      `The declarations are those of each package's own '@c2n/<name>/react' entry; see any of them for the`,
      `rules React needs followed (register before rendering, kebab-case attribute names when server-rendering).`,
      ...bindingUsage('react'),
    ]),
    parser: 'typescript',
  })
  files.push({
    path: 'vue.d.ts',
    contents: typesEntry('vue', [
      `Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders`,
      `nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.`,
      ...bindingUsage('vue'),
    ]),
    parser: 'typescript',
  })
  // As in each package: `import '@c2n/components/react'` from a `.ts` file must resolve to a module at runtime, and
  // that module carries the packages' bindings.
  const runtimeEntry = (framework: Framework) => {
    const bindings = withBinding(framework)
    if (bindings.length === 0) return `${BANNER}\n// Types only — see the matching .d.ts.\nexport {}\n`
    return [BANNER, ...reexports(bindings.map((entry) => `${entry.pkg}/${framework}`)), ``].join('\n')
  }
  files.push({ path: 'react.js', contents: runtimeEntry('react'), parser: 'typescript' })
  files.push({ path: 'vue.js', contents: runtimeEntry('vue'), parser: 'typescript' })

  // Resolved from this file's own location, so the theme is reachable even where the package manager does not
  // hoist `@c2n/theme` next to the application (pnpm).
  for (const stylesheet of THEME_STYLESHEETS) {
    files.push({
      path: stylesheet,
      contents: `/* GENERATED by @c2n/framework-types. Do not edit by hand. */\n@import '${THEME}/${stylesheet}';\n`,
      parser: 'css',
    })
  }

  files.push({ path: 'package.json', contents: emitPackageJson(entries, umbrellaDir, scopeDir), parser: 'json-stringify' })
  return files
}

function emitPackageJson(entries: UmbrellaEntry[], umbrellaDir: string, scopeDir: string): string {
  const current = readJson(join(umbrellaDir, 'package.json'))
  const handWritten = Object.fromEntries(Object.entries(current).filter(([key]) => !GENERATED_KEYS.includes(key)))

  const exports: Record<string, unknown> = { '.': { types: './index.d.ts', default: './index.js' } }
  for (const entry of entries) exports[`./${entry.name}`] = { types: `./lib/${entry.name}.d.ts`, default: `./lib/${entry.name}.js` }
  exports['./react'] = { types: './react.d.ts', default: './react.js' }
  exports['./vue'] = { types: './vue.d.ts', default: './vue.js' }
  for (const stylesheet of THEME_STYLESHEETS) exports[`./${stylesheet}`] = `./${stylesheet}`
  exports['./package.json'] = './package.json'

  // Exact pins, like every other `@c2n` dependency in the repo: `lerna version` bumps them with the rest.
  const dependencies: Record<string, string> = {}
  const peerDependencies: Record<string, string> = {}
  const peerDependenciesMeta: Record<string, { optional: true }> = {}
  for (const pkg of [...entries.map((entry) => entry.pkg), THEME].sort()) {
    const manifest = readJson(join(scopeDir, pkg.slice('@c2n/'.length), 'package.json'))
    dependencies[pkg] = manifest.version
    // A package's optional engines (uplot, echarts, CodeMirror) are the application's to install; npm does not
    // install a dependency's peers on its behalf, so they are surfaced here where the application can see them.
    for (const [peer, range] of Object.entries(manifest.peerDependencies ?? {})) {
      peerDependencies[peer] = range
      if (manifest.peerDependenciesMeta?.[peer]?.optional) peerDependenciesMeta[peer] = { optional: true }
    }
  }

  const sorted = <T>(record: Record<string, T>) => Object.fromEntries(Object.entries(record).sort(([a], [b]) => a.localeCompare(b)))
  const packageJson = {
    ...handWritten,
    exports,
    files: ['index.js', 'index.d.ts', 'lib', 'react.js', 'react.d.ts', 'vue.js', 'vue.d.ts', ...THEME_STYLESHEETS],
    dependencies,
    ...(Object.keys(peerDependencies).length > 0 ? { peerDependencies: sorted(peerDependencies), peerDependenciesMeta: sorted(peerDependenciesMeta) } : {}),
  }
  return `${JSON.stringify(packageJson, null, 2)}\n`
}
