/**
 * `@c2n/components`, the one published component package: one entry per component package, a barrel that
 * registers them all, and the JSX / Vue declarations of every tag behind a single import.
 *
 * The component packages are private workspaces; only this package reaches npm. The generator writes the bundle
 * inputs under `src/` (each entry re-exports every module of one workspace package) and the package's
 * `package.json`; `scripts/bundle.ts` then builds `dist/` from them, inlining the workspace packages so the
 * published tarball depends on nothing but `@c2n/core`, the theme, the icon sets it uses and third-party libraries.
 * Everything here is derived from the discovered packages, so a new component joins the umbrella by being built,
 * with no list to maintain.
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { DiscoveredPackage } from './manifests.ts'

const BANNER = '// GENERATED by @c2n/framework-types. Do not edit by hand.'

/**
 * Icon sets stay out: Phosphor alone is 1,512 elements, and a barrel import of the umbrella would register all
 * of them. They remain their own install, with their own per-icon entry points.
 */
const EXCLUDED = new Set(['@c2n/feather-icons', '@c2n/phosphor-icons', '@c2n/symbols', '@c2n/task-icons'])

/** The theme is part of "everything", but it ships stylesheets rather than elements, so discovery never sees it. */
const THEME = '@c2n/theme'
const THEME_STYLESHEETS = ['theme.css', 'base.css', 'tokens.css']

/** Keys of the umbrella's `package.json` that the generator owns; everything else is hand-written. */
const GENERATED_KEYS = ['exports', 'files', 'customElements', 'dependencies', 'peerDependencies', 'peerDependenciesMeta', 'devDependencies']

interface PackageJson {
  name: string
  version: string
  exports?: Record<string, { types?: string } | string>
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
  peerDependenciesMeta?: Record<string, { optional?: boolean }>
  [key: string]: unknown
}

export interface UmbrellaEntry {
  /** npm package, e.g. `@c2n/table`. */
  pkg: string
  /** Subpath of the umbrella, and the name of its file under `src/` and `dist/`, e.g. `table`. */
  name: string
  /** Every JavaScript module of the package, e.g. `@c2n/table`, `@c2n/table/table-column.js`. */
  modules: string[]
}

export interface UmbrellaFile {
  /** Path relative to the umbrella package. */
  path: string
  contents: string
  parser: 'typescript' | 'json-stringify' | 'css'
}

function readJson(file: string): PackageJson {
  return JSON.parse(readFileSync(file, 'utf8')) as PackageJson
}

/**
 * The umbrella's entries, one per component package. An entry re-exports every JavaScript subpath the package
 * publishes, not just its root: `@c2n/table`'s root does not re-export `TableColumn`, and importing the entry has
 * to register every tag the package defines.
 */
export function umbrellaEntries(packages: DiscoveredPackage[]): UmbrellaEntry[] {
  return packages
    .filter((pkg) => !EXCLUDED.has(pkg.name))
    .map((pkg) => {
      const exports = readJson(join(pkg.dir, 'package.json')).exports ?? {}
      const subpaths = Object.entries(exports)
        // A wildcard subpath (`@c2n/chart/maps/*.js`) publishes data modules an element loads on demand; re-exporting
        // them would make the barrel load every one of them up front.
        .filter(([subpath, entry]) => subpath !== '.' && subpath.endsWith('.js') && !subpath.includes('*') && typeof entry !== 'string' && entry.types)
        .map(([subpath]) => `${pkg.name}/${subpath.slice(2)}`)
      return { pkg: pkg.name, name: pkg.name.slice('@c2n/'.length), modules: [...(exports['.'] ? [pkg.name] : []), ...subpaths.sort()] }
    })
}

export function emitUmbrella(packages: DiscoveredPackage[], umbrellaDir: string, scopeDir: string): UmbrellaFile[] {
  const entries = umbrellaEntries(packages)
  const files: UmbrellaFile[] = []
  const reexports = (modules: string[]) => modules.map((module) => `export * from '${module}'`)

  for (const entry of entries) {
    const body = [BANNER, `// Every module of ${entry.pkg}. Importing this registers each of its elements.`, ``, ...reexports(entry.modules), ``].join('\n')
    files.push({ path: `src/${entry.name}.js`, contents: body, parser: 'typescript' })
    files.push({ path: `src/${entry.name}.d.ts`, contents: body, parser: 'typescript' })
  }

  const barrel = [
    BANNER,
    `//`,
    `// Every c2n component. Importing this module registers all of them, and no bundler can tree-shake a`,
    `// registration away: an application that ships to users should import the components it uses instead:`,
    `//`,
    `//     import '@c2n/components/button'`,
    ``,
    ...reexports(entries.map((entry) => `./${entry.name}.js`)),
    ``,
  ].join('\n')
  files.push({ path: 'src/index.js', contents: barrel, parser: 'typescript' })
  files.push({ path: 'src/index.d.ts', contents: barrel, parser: 'typescript' })

  const typesEntry = (framework: 'react' | 'vue', usage: string[]) =>
    [
      BANNER,
      `//`,
      `// ${framework === 'react' ? 'JSX' : 'Vue template'} types for every c2n component. Import once, anywhere in the program:`,
      `//`,
      `//     import '@c2n/components/${framework}'`,
      `//`,
      ...usage.map((line) => (line ? `// ${line}` : `//`)),
      ``,
      ...entries.map((entry) => `import '${entry.pkg}/${framework}'`),
      ``,
      `export {}`,
      ``,
    ].join('\n')
  files.push({
    path: 'src/react.d.ts',
    contents: typesEntry('react', [
      `Register an element before React renders it, and pass kebab-case attribute names when server-rendering:`,
      `a camelCase prop that reaches the server as an attribute is never seen by the element.`,
    ]),
    parser: 'typescript',
  })
  files.push({
    path: 'src/vue.d.ts',
    contents: typesEntry('vue', [
      `Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders`,
      `nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.`,
    ]),
    parser: 'typescript',
  })
  // As in each package: `import '@c2n/components/react'` from a `.ts` file must resolve to a module at runtime.
  const stub = `${BANNER}\n// Types only — see the matching .d.ts.\nexport {}\n`
  files.push({ path: 'src/react.js', contents: stub, parser: 'typescript' })
  files.push({ path: 'src/vue.js', contents: stub, parser: 'typescript' })

  // Resolved from this file's own location, so the theme is reachable even where the package manager does not
  // hoist `@c2n/theme` next to the application (pnpm).
  for (const stylesheet of THEME_STYLESHEETS) {
    files.push({
      path: stylesheet,
      contents: `/* GENERATED by @c2n/framework-types. Do not edit by hand. */\n@import '${THEME}/${stylesheet}';\n`,
      parser: 'css',
    })
  }

  files.push({ path: 'package.json', contents: emitPackageJson(entries, umbrellaDir, scopeDir), parser: 'json-stringify' })
  return files
}

function emitPackageJson(entries: UmbrellaEntry[], umbrellaDir: string, scopeDir: string): string {
  const current = readJson(join(umbrellaDir, 'package.json'))
  const handWritten = Object.fromEntries(Object.entries(current).filter(([key]) => !GENERATED_KEYS.includes(key)))
  const readPackage = (pkg: string) => readJson(join(scopeDir, pkg.slice('@c2n/'.length), 'package.json'))

  const exports: Record<string, unknown> = { '.': { types: './dist/index.d.ts', default: './dist/index.js' } }
  for (const entry of entries) exports[`./${entry.name}`] = { types: `./dist/${entry.name}.d.ts`, default: `./dist/${entry.name}.js` }
  exports['./react'] = { types: './dist/react.d.ts', default: './dist/react.js' }
  exports['./vue'] = { types: './dist/vue.d.ts', default: './dist/vue.js' }
  for (const stylesheet of THEME_STYLESHEETS) exports[`./${stylesheet}`] = `./${stylesheet}`
  exports['./custom-elements.json'] = './custom-elements.json'
  exports['./package.json'] = './package.json'

  // The bundle inlines every workspace component package, so what remains to install is what those packages
  // import from outside the bundle: Lit, `@c2n/core`, an icon set, third-party libraries. A library two packages
  // pin differently would be installed once, at one of the two versions, so a disagreement stops the build.
  const bundled = new Set(entries.map((entry) => entry.pkg))
  const dependencies: Record<string, string> = {}
  const pinnedBy: Record<string, string> = {}
  const peerDependencies: Record<string, string> = {}
  const peerDependenciesMeta: Record<string, { optional: true }> = {}
  for (const entry of entries) {
    const manifest = readPackage(entry.pkg)
    for (const [dependency, range] of Object.entries(manifest.dependencies ?? {})) {
      if (bundled.has(dependency)) continue
      // Exact pins, like every other published `@c2n` dependency: `lerna version` bumps them with the rest.
      const version = dependency.startsWith('@c2n/') ? readPackage(dependency).version : range
      if (dependencies[dependency] !== undefined && dependencies[dependency] !== version) {
        throw new Error(`${entry.pkg} needs ${dependency}@${version}, but ${pinnedBy[dependency]} needs ${dependencies[dependency]}`)
      }
      dependencies[dependency] = version
      pinnedBy[dependency] = entry.pkg
    }
    // A package's optional engines (uplot, echarts, CodeMirror) are the application's to install; npm does not
    // install a dependency's peers on its behalf, so they are surfaced here where the application can see them.
    for (const [peer, range] of Object.entries(manifest.peerDependencies ?? {})) {
      if (bundled.has(peer)) continue
      peerDependencies[peer] = range
      if (manifest.peerDependenciesMeta?.[peer]?.optional) peerDependenciesMeta[peer] = { optional: true }
    }
  }
  dependencies[THEME] = readPackage(THEME).version
  for (const peer of Object.keys(peerDependencies)) delete dependencies[peer]

  // The workspace packages the bundle is built from: devDependencies, so a consumer never installs them, and `*`,
  // because they are private and never versioned.
  const devDependencies: Record<string, string> = { '@c2n/config': '*' }
  for (const entry of entries) devDependencies[entry.pkg] = '*'

  const sorted = <T>(record: Record<string, T>) => Object.fromEntries(Object.entries(record).sort(([a], [b]) => a.localeCompare(b)))
  const packageJson = {
    ...handWritten,
    exports,
    files: ['dist', 'custom-elements.json', ...THEME_STYLESHEETS],
    customElements: 'custom-elements.json',
    dependencies: sorted(dependencies),
    ...(Object.keys(peerDependencies).length > 0 ? { peerDependencies: sorted(peerDependencies), peerDependenciesMeta: sorted(peerDependenciesMeta) } : {}),
    devDependencies: sorted(devDependencies),
  }
  return `${JSON.stringify(packageJson, null, 2)}\n`
}
