/**
 * Generates the framework glue that consumers would otherwise hand-write, from the custom-elements manifests
 * that `vite-plugin-cem` already emits for every component:
 *
 * - `<package>/react.d.ts`  — JSX.IntrinsicElements, so `<c2-table rows={…}>` type-checks in React
 * - `<package>/vue.d.ts`    — IntrinsicElementAttributes, so a Vue template can run with `strictTemplates`
 * - `packages/adapters/angular/src/value-accessors.ts` — the `ControlValueAccessor` directives of `@c2n/angular`
 * - `dist/html-custom-data.json` — VS Code / Volar completion for plain HTML, Vue and Angular templates
 * - `dist/web-types.json`        — the JetBrains equivalent
 *
 * The two `.d.ts` files live in the package they describe: a single aggregate file would have to import from
 * every `@c2n` package, and a consumer who installed three of them would not be able to compile it.
 *
 * Run with `npm run build -w packages/tools/framework-types` (plain node on Node 24 type stripping, so keep this
 * to erasable TypeScript syntax only). Output is formatted with the repo's prettier config, and the per-package
 * files are committed alongside `custom-elements.json`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'
import { emitHtmlCustomData, emitWebTypes } from './emit-editor.ts'
import { emitReact, emitVue } from './emit-react.ts'
import { emitAngular } from './emit-angular.ts'
import { emitVueTsconfig } from './emit-vue-config.ts'
import { readPackages, repoRelative } from './manifests.ts'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const distDir = join(packageDir, 'dist')
const version = (JSON.parse(readFileSync(join(packageDir, 'package.json'), 'utf8')) as { version: string }).version

const prettierConfig = await resolveConfig(join(packageDir, 'package.json'))

async function write(file: string, contents: string, parser: 'typescript' | 'json'): Promise<void> {
  writeFileSync(file, await format(contents, { ...prettierConfig, parser }))
  console.log(`  ${repoRelative(file)}`)
}

const packages = readPackages()
const elementCount = packages.reduce((total, pkg) => total + pkg.elements.length, 0)
console.log(`[framework-types] ${elementCount} elements in ${packages.length} packages`)

// The `.js` stubs exist so `import '@c2n/button/react'` resolves from a `.ts` file as well as from a `.d.ts`:
// a types-only export would compile and then fail at runtime under `verbatimModuleSyntax`.
const STUB = '// GENERATED by @c2n/framework-types. Do not edit by hand.\n// Types only — see the matching .d.ts.\nexport {}\n'

for (const pkg of packages) {
  await write(join(pkg.dir, 'react.d.ts'), emitReact(pkg), 'typescript')
  await write(join(pkg.dir, 'react.js'), STUB, 'typescript')
  await write(join(pkg.dir, 'vue.d.ts'), emitVue(pkg), 'typescript')
  await write(join(pkg.dir, 'vue.js'), STUB, 'typescript')
}

mkdirSync(distDir, { recursive: true })
await write(resolve(packageDir, '../../adapters/angular/src/value-accessors.ts'), emitAngular(packages), 'typescript')
await write(join(packageDir, 'tsconfig.vue.json'), emitVueTsconfig(packages, version), 'json')
await write(join(distDir, 'html-custom-data.json'), emitHtmlCustomData(packages, version), 'json')
await write(join(distDir, 'web-types.json'), emitWebTypes(packages, version), 'json')
