// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/text-field. Import once, anywhere in the program:
//
//     import '@c2n/text-field/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { TextField, TextFieldEventMap } from '@c2n/text-field'
import type { TextFieldClear, TextFieldClearEventMap } from '@c2n/text-field/text-field-clear.js'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-text-field': DefineComponent<
      C2Props<TextField> & {
        readonly?: unknown
        maxlength?: unknown
        minlength?: unknown
        'aria-label'?: unknown
        'error-text'?: unknown
        onInput?: (event: TextFieldEventMap['input']) => void
        onChange?: (event: TextFieldEventMap['change']) => void
        onClear?: (event: TextFieldEventMap['clear']) => void
      }
    >
    'c2-text-field-clear': DefineComponent<
      C2Props<TextFieldClear> & {
        readonly?: unknown
        maxlength?: unknown
        minlength?: unknown
        'aria-label'?: unknown
        'error-text'?: unknown
        onInput?: (event: TextFieldClearEventMap['input']) => void
        onChange?: (event: TextFieldClearEventMap['change']) => void
        onClear?: (event: TextFieldClearEventMap['clear']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
