// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/autocomplete. Import once, anywhere in the program:
//
//     import '@c2n/autocomplete/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below. Structured converter-backed values
// also accept their serialized string form, so server JSX can emit the same JSON/CSV attribute used by HTML.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { Autocomplete } from '@c2n/autocomplete'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>
/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */
type Attribute = string | number | boolean

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-autocomplete': Omit<C2Props<Autocomplete>, 'suggestions' | 'searchFields'> & {
        'aria-label'?: Attribute
        'item-key'?: Attribute
        'label-field'?: Attribute
        'description-field'?: Attribute
        'disabled-field'?: Attribute
        'search-fields'?: Attribute
        'selection-behavior'?: Attribute
        'min-query-length'?: Attribute
        'max-results'?: Attribute
        'show-empty'?: Attribute
        suggestions?: Autocomplete['suggestions'] | string
        searchFields?: Autocomplete['searchFields'] | string
      }
    }
  }
}

export {}
