// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/autocomplete. Import once, anywhere in the program:
//
//     import '@c2n/autocomplete/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Autocomplete, AutocompleteEventMap } from '@c2n/autocomplete'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-autocomplete': DefineComponent<
      C2Props<Autocomplete> & {
        'aria-label'?: unknown
        'item-key'?: unknown
        'label-field'?: unknown
        'description-field'?: unknown
        'disabled-field'?: unknown
        'search-fields'?: unknown
        'selection-behavior'?: unknown
        'min-query-length'?: unknown
        'max-results'?: unknown
        'show-empty'?: unknown
        onSuggestionSelect?: (event: AutocompleteEventMap['suggestion-select']) => void
        onInput?: (event: AutocompleteEventMap['input']) => void
        onChange?: (event: AutocompleteEventMap['change']) => void
        onQueryChange?: (event: AutocompleteEventMap['query-change']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
