// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/modal. Import once, anywhere in the program:
//
//     import '@c2n/modal/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Modal, ModalEventMap } from '@c2n/modal'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-modal': DefineComponent<
      C2Props<Modal> & {
        'no-backdrop-close'?: unknown
        'no-escape'?: unknown
        'hide-close'?: unknown
        'no-scroll-lock'?: unknown
        onOpen?: (event: ModalEventMap['open']) => void
        onClose?: (event: ModalEventMap['close']) => void
        onCancel?: (event: ModalEventMap['cancel']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
