// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/gantt. Import once, anywhere in the program:
//
//     import '@c2n/gantt/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below. Structured converter-backed values
// also accept their serialized string form, so server JSX can emit the same JSON/CSV attribute used by HTML.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { Gantt } from '@c2n/gantt'
import type { GanttTask } from '@c2n/gantt/gantt-task.js'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>
/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */
type Attribute = string | number | boolean

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-gantt': Omit<C2Props<Gantt>, 'tasks' | 'collapsed'> & {
        'hide-list'?: Attribute
        'week-start'?: Attribute
        'aria-label'?: Attribute
        tasks?: Gantt['tasks'] | string
        collapsed?: Gantt['collapsed'] | string
      }
      'c2-gantt-task': C2Props<GanttTask> & {
        'task-id'?: Attribute
      }
    }
  }
}

export {}
