// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/gantt. Import once, anywhere in the program:
//
//     import '@c2n/gantt/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { EventMapOf } from '@c2n/core/event-helper.js'
import type { Gantt } from '@c2n/gantt'
import type { GanttTask } from '@c2n/gantt/gantt-task.js'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes
/** The event an element fires under `name`, read from the map its `addEventListener` carries (its own or inherited). */
type EventOf<T extends EventTarget, Name extends string> = Name extends keyof EventMapOf<T> ? EventMapOf<T>[Name] : CustomEvent

declare module 'vue' {
  interface GlobalComponents {
    'c2-gantt': DefineComponent<
      C2Props<Gantt> & {
        'hide-list'?: unknown
        'week-start'?: unknown
        'aria-label'?: unknown
        onSelectionChange?: (event: EventOf<Gantt, 'selection-change'>) => void
        onGroupToggle?: (event: EventOf<Gantt, 'group-toggle'>) => void
        onTaskHover?: (event: EventOf<Gantt, 'task-hover'>) => void
        onTaskClick?: (event: EventOf<Gantt, 'task-click'>) => void
      }
    >
    'c2-gantt-task': DefineComponent<
      C2Props<GanttTask> & {
        'task-id'?: unknown
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
