// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/upload. Import once, anywhere in the program:
//
//     import '@c2n/upload/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { EventMapOf } from '@c2n/core/event-helper.js'
import type { Upload } from '@c2n/upload'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes
/** The event an element fires under `name`, read from the map its `addEventListener` carries (its own or inherited). */
type EventOf<T extends EventTarget, Name extends string> = Name extends keyof EventMapOf<T> ? EventMapOf<T>[Name] : CustomEvent

declare module 'vue' {
  interface GlobalComponents {
    'c2-upload': DefineComponent<
      C2Props<Upload> & {
        'max-files'?: unknown
        'max-size'?: unknown
        'auto-upload'?: unknown
        'aria-label'?: unknown
        onInput?: (event: EventOf<Upload, 'input'>) => void
        onChange?: (event: EventOf<Upload, 'change'>) => void
        onFilesSelected?: (event: EventOf<Upload, 'files-selected'>) => void
        onFileReject?: (event: EventOf<Upload, 'file-reject'>) => void
        onUploadStart?: (event: EventOf<Upload, 'upload-start'>) => void
        onUploadProgress?: (event: EventOf<Upload, 'upload-progress'>) => void
        onUploadSuccess?: (event: EventOf<Upload, 'upload-success'>) => void
        onUploadError?: (event: EventOf<Upload, 'upload-error'>) => void
        onUploadRemove?: (event: EventOf<Upload, 'upload-remove'>) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
