// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * AI assistant symbol. A friendly robot: an AI assistant, a chatbot, a copilot or an automated agent.
 *
 * @tag c2-symbol-ai-assistant
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-ai-assistant')
export class AiAssistantSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="128" rx="30" ry="5"/><path class="line-ink" d="M80 50V36"/><circle class="accent" cx="80" cy="32" r="5"/><rect class="ink" x="34" y="70" width="10" height="22" rx="4"/><rect class="ink" x="116" y="70" width="10" height="22" rx="4"/><rect class="primary-soft line" x="42" y="50" width="76" height="62" rx="18"/><rect class="primary" x="52" y="62" width="56" height="34" rx="11"/><path class="line-surface" d="M64 80a5 5 0 0 1 10 0M86 80a5 5 0 0 1 10 0"/><path class="line" d="M70 104h20"/><path class="accent" d="M128 32Q130.2 37.8 136 40Q130.2 42.2 128 48Q125.8 42.2 120 40Q125.8 37.8 128 32Z"/><path class="primary" d="M32 39Q33.4 42.6 37 44Q33.4 45.4 32 49Q30.6 45.4 27 44Q30.6 42.6 32 39Z"/><path class="line-primary" d="M130 112v8M126 116h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-ai-assistant': AiAssistantSymbol
  }
}
