// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * All done symbol. A clipboard with every item checked off: a finished checklist, an inbox at zero, nothing left to review.
 *
 * @tag c2-symbol-all-done
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges, the light bulb, the rocket flame.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-all-done')
export class AllDoneSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><rect class="surface line" x="42" y="36" width="76" height="94" rx="8"/><rect class="muted line" x="62" y="28" width="36" height="16" rx="5"/><circle class="success" cx="59" cy="66" r="7"/><circle class="success" cx="59" cy="88" r="7"/><circle class="success" cx="59" cy="110" r="7"/><path class="line-surface" d="m55.5 66 2.5 2.5 5-5M55.5 88l2.5 2.5 5-5M55.5 110l2.5 2.5 5-5"/><path class="line" d="M74 66h30M74 88h24M74 110h28"/><path class="line-primary" d="M130 30v10M125 35h10"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-all-done': AllDoneSymbol
  }
}
