// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Analytics symbol. A bar chart with a trend line: analytics, insights, metrics, a dashboard or statistics.
 *
 * @tag c2-symbol-analytics
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-analytics')
export class AnalyticsSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="128" rx="44" ry="5"/><rect class="surface line" x="24" y="34" width="112" height="86" rx="8"/><rect class="primary-soft" x="38" y="84" width="14" height="24" rx="3"/><rect class="primary-soft" x="58" y="72" width="14" height="36" rx="3"/><rect class="primary" x="78" y="62" width="14" height="46" rx="3"/><rect class="primary-soft" x="98" y="76" width="14" height="32" rx="3"/><path class="line-accent" d="m38 66 20-10 20 4 32-18"/><circle class="accent" cx="110" cy="42" r="4"/><path class="line" d="M36 108h88"/><path class="primary" d="M132 17Q134 22 139 24Q134 26 132 31Q130 26 125 24Q130 22 132 17Z"/><circle class="accent" cx="30" cy="128" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-analytics': AnalyticsSymbol
  }
}
