// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * API symbol. A code window with braces: API access, developer settings, webhooks or JSON data.
 *
 * @tag c2-symbol-api
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-api')
export class ApiSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><rect class="ink" x="26" y="42" width="108" height="76" rx="10"/><path class="line-surface" opacity="0.2" d="M27.5 58h105"/><circle class="error" cx="37" cy="50" r="2.5"/><circle class="accent" cx="46" cy="50" r="2.5"/><circle class="success" cx="55" cy="50" r="2.5"/><path class="line-accent" d="M44 76c-6 0-6 4-6 8s0 8-6 8c6 0 6 4 6 8s0 8 6 8" transform="translate(4 -8)"/><path class="line-accent" d="M116 76c6 0 6 4 6 8s0 8 6 8c-6 0-6 4-6 8s0 8-6 8" transform="translate(-4 -8)"/><path class="line-primary" d="M60 78h28M60 90h40"/><path class="line-surface" opacity="0.4" d="M60 102h18"/><path class="primary" d="M130 24Q131.7 28.3 136 30Q131.7 31.7 130 36Q128.3 31.7 124 30Q128.3 28.3 130 24Z"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-api': ApiSymbol
  }
}
