// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Backup symbol. A cloud with sync arrows and a check: backups, cloud sync, autosave or restore points.
 *
 * @tag c2-symbol-backup
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-backup')
export class BackupSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><path class="primary-soft line" d="M52 110a22 22 0 0 1-2-43.9A30 30 0 0 1 108 60a25 25 0 0 1 2 50Z"/><path class="line-primary" d="M66.8 83.2A14 14 0 0 1 93.2 83.2M88 80.2L93.2 83.2L95.2 77.6"/><path class="line-primary" d="M93.2 92.8A14 14 0 0 1 66.8 92.8M72 95.8L66.8 92.8L64.8 98.4"/><circle class="success line-surface" cx="112" cy="108" r="12"/><path class="line-surface" d="M106.5 108.5l3.5 3.5 7-7"/><path class="accent" d="M30 34Q31.7 38.3 36 40Q31.7 41.7 30 46Q28.3 41.7 24 40Q28.3 38.3 30 34Z"/><path class="line-accent" d="M130 32v8M126 36h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-backup': BackupSymbol
  }
}
