// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Biometric symbol. A fingerprint: biometric sign-in, Touch ID, passkeys or identity verification.
 *
 * @tag c2-symbol-biometric
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-biometric')
export class BiometricSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><circle class="primary-soft" cx="80" cy="80" r="44"/><path class="line-primary" d="M49.2 71.6A34 34 0 0 1 110.8 71.6"/><path class="line-primary" d="M54.4 81.5A26 26 0 0 1 105.6 81.5M54 86c0 10 2 18 6 24"/><path class="line-primary" d="M62 86A18 18 0 0 1 98 86M98 86c0 12-3 22-8 30M62 86c0 14 4 24 10 32"/><path class="line-primary" d="M70 86A10 10 0 0 1 90 86M70 86c0 14 3 26 8 34M90 86c0 10-1 18-4 26"/><path class="line-primary" d="M80 86c0 12 1 22 4 30"/><path class="accent" d="M128 25Q130 30 135 32Q130 34 128 39Q126 34 121 32Q126 30 128 25Z"/><path class="line-accent" d="M32 114v8M28 118h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-biometric': BiometricSymbol
  }
}
