// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Cloud error symbol. A cloud with an error badge: sync failed, the service is unavailable or a backup did not finish.
 *
 * @tag c2-symbol-cloud-error
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-cloud-error')
export class CloudErrorSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><path class="surface line" d="M52 110a22 22 0 0 1-2-43.9A30 30 0 0 1 108 60a25 25 0 0 1 2 50Z"/><path class="line" d="M62 92h24"/><circle class="error line-surface" cx="106" cy="106" r="14"/><path class="line-surface" d="M106 99.5v7M106 111.5v.01"/><path class="primary" d="M34 34Q35.7 38.3 40 40Q35.7 41.7 34 46Q32.3 41.7 28 40Q32.3 38.3 34 34Z"/><path class="line-accent" d="M128 34v8M124 38h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-cloud-error': CloudErrorSymbol
  }
}
