// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Coffee break symbol. A steaming cup: all caught up, take a break, idle or away.
 *
 * @tag c2-symbol-coffee-break
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-coffee-break')
export class CoffeeBreakSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted line" cx="74" cy="122" rx="42" ry="6"/><path class="line" d="M104 80h6a11 11 0 0 1 0 22h-8"/><path class="surface line" d="M44 72h60v18a28 28 0 0 1-28 28h-4a28 28 0 0 1-28-28Z"/><path class="primary-soft" d="M45.5 84h57v6a26 26 0 0 1-1 7h-55a26 26 0 0 1-1-7Z"/><path class="line-primary" opacity="0.6" d="M62 60c-5-7 5-11 0-18M76 60c-5-7 5-11 0-18M90 60c-5-7 5-11 0-18"/><path class="accent" d="M126 33Q128 38 133 40Q128 42 126 47Q124 42 119 40Q124 38 126 33Z"/><circle class="accent" cx="32" cy="50" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-coffee-break': CoffeeBreakSymbol
  }
}
