// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Cookie consent symbol. A bitten cookie: cookie consent, tracking preferences and privacy settings.
 *
 * @tag c2-symbol-cookie-consent
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-cookie-consent')
export class CookieConsentSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><path class="accent" d="M115.4 75.4A38 38 0 1 1 97 49.1a9 9 0 0 0 7 14 9 9 0 0 0 11.4 12.3Z"/><path class="line-ink" opacity="0.25" d="M50 96a30 30 0 0 0 30 22"/><circle class="ink" cx="62" cy="70" r="4.5"/><circle class="ink" cx="84" cy="98" r="5"/><circle class="ink" cx="58" cy="100" r="3.5"/><circle class="ink" cx="92" cy="76" r="3"/><circle class="ink" cx="74" cy="84" r="2.5"/><circle class="ink" cx="100" cy="108" r="3"/><circle class="accent" cx="122" cy="50" r="2.5"/><circle class="accent" cx="128" cy="62" r="2"/><circle class="accent" cx="116" cy="40" r="1.8"/><path class="primary" d="M36 36Q37.7 40.3 42 42Q37.7 43.7 36 48Q34.3 43.7 30 42Q34.3 40.3 36 36Z"/><path class="line-primary" d="M128 114v8M124 118h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-cookie-consent': CookieConsentSymbol
  }
}
