// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Credit card symbol. Two payment cards: add a payment method, billing details or a saved card.
 *
 * @tag c2-symbol-credit-card
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-credit-card')
export class CreditCardSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="40" ry="5"/><rect class="primary" x="46" y="34" width="86" height="54" rx="8" transform="rotate(-12 89 61)"/><rect class="surface line" x="28" y="58" width="92" height="60" rx="8"/><rect class="accent" x="40" y="72" width="17" height="13" rx="3"/><path class="line-ink" opacity="0.4" d="M40 78.5h17M48.5 72v13"/><path class="line" d="M40 98h12M58 98h12M76 98h12M40 108h26"/><circle class="error" opacity="0.85" cx="98" cy="80" r="7"/><circle class="accent" opacity="0.85" cx="107" cy="80" r="7"/><path class="primary" d="M34 30Q35.7 34.3 40 36Q35.7 37.7 34 42Q32.3 37.7 28 36Q32.3 34.3 34 30Z"/><path class="line-accent" d="M134 112v8M130 116h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-credit-card': CreditCardSymbol
  }
}
