// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Disconnected symbol. A plug pulled from its socket: the connection was lost, a device or service is disconnected.
 *
 * @tag c2-symbol-disconnected
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-disconnected')
export class DisconnectedSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><path class="line-ink" d="M18 104c14 0 20-24 34-24M126 80c12 0 16 24 26 24"/><rect class="primary" x="48" y="66" width="26" height="28" rx="6"/><path class="line-ink" d="M74 73h10M74 87h10"/><rect class="surface line" x="96" y="62" width="30" height="36" rx="8"/><rect class="ink" x="102" y="71" width="8" height="4" rx="2"/><rect class="ink" x="102" y="85" width="8" height="4" rx="2"/><path class="line-accent" d="M90 56v8M90 96v8M84 60l2 4M96 100l-2-4"/><path class="primary" d="M36 32Q37.7 36.3 42 38Q37.7 39.7 36 44Q34.3 39.7 30 38Q34.3 36.3 36 32Z"/><circle class="primary-soft" cx="126" cy="120" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-disconnected': DisconnectedSymbol
  }
}
