// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Empty trash symbol. A clean trash can: the trash, recycle bin or deleted items are empty.
 *
 * @tag c2-symbol-empty-trash
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-empty-trash')
export class EmptyTrashSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="32" ry="5"/><path class="surface line" d="M50 52h60l-6 66a6 6 0 0 1-6 6H62a6 6 0 0 1-6-6Z"/><path class="line" d="M68 66v44M80 66v44M92 66v44"/><rect class="primary-soft line" x="42" y="40" width="76" height="12" rx="4"/><path class="line" d="M70 40v-4a4 4 0 0 1 4-4h12a4 4 0 0 1 4 4v4"/><path class="accent" d="M124 23Q126 28 131 30Q126 32 124 37Q122 32 117 30Q122 28 124 23Z"/><path class="line-primary" d="M34 95v10M29 100h10"/><circle class="primary-soft" cx="126" cy="96" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-empty-trash': EmptyTrashSymbol
  }
}
