// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Growth symbol. A sprouting plant: growth, progress, a new beginning, sustainability or nurturing.
 *
 * @tag c2-symbol-growth
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-growth')
export class GrowthSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="28" ry="5"/><path class="line-success" d="M80 100V60"/><path class="success" d="M80 76c-4-16-18-24-34-22 2 16 16 26 34 22Z"/><path class="success" opacity="0.7" d="M80 64c2-18 16-28 34-28-2 18-16 30-34 28Z"/><path class="primary" d="M56 98h48l-6 30H62Z"/><rect class="primary" x="52" y="94" width="56" height="10" rx="3"/><path class="accent" d="M126 84Q127.7 88.3 132 90Q127.7 91.7 126 96Q124.3 91.7 120 90Q124.3 88.3 126 84Z"/><path class="line-accent" d="M34 32v8M30 36h8"/><circle class="primary" cx="130" cy="50" r="3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-growth': GrowthSymbol
  }
}
