// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Hidden symbol. A crossed-out eye: private, hidden or sensitive content; visibility turned off.
 *
 * @tag c2-symbol-hidden
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-hidden')
export class HiddenSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><path class="surface line" d="M22 80c14-24 34-36 58-36s44 12 58 36c-14 24-34 36-58 36S36 104 22 80Z"/><circle class="primary" cx="80" cy="80" r="20"/><circle class="ink" cx="80" cy="80" r="8"/><circle class="surface" cx="87" cy="73" r="3.5"/><rect class="backdrop" x="75" y="22" width="10" height="116" rx="5" transform="rotate(-45 80 80)"/><rect class="error" x="77.5" y="26" width="5" height="108" rx="2.5" transform="rotate(-45 80 80)"/><path class="primary" d="M130 118Q131.7 122.3 136 124Q131.7 125.7 130 130Q128.3 125.7 124 124Q128.3 122.3 130 118Z"/><circle class="accent" cx="128" cy="38" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-hidden': HiddenSymbol
  }
}
