// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Invite symbol. An invitation card with a person and a plus badge: invite teammates, share access, add members.
 *
 * @tag c2-symbol-invite
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-invite')
export class InviteSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="40" ry="5"/><rect class="primary-soft line" x="28" y="60" width="104" height="62" rx="7"/><rect class="surface line" x="44" y="30" width="72" height="66" rx="5"/><circle class="primary" cx="80" cy="52" r="10"/><path class="primary" d="M64 80a16 16 0 0 1 32 0Z"/><path class="surface line" d="M29.5 64 80 96l50.5-32V116a6 6 0 0 1-6 6h-89a6 6 0 0 1-6-6Z"/><circle class="success line-surface" cx="118" cy="44" r="12"/><path class="line-surface" d="M118 38v12M112 44h12"/><path class="accent" d="M30 30Q31.7 34.3 36 36Q31.7 37.7 30 42Q28.3 37.7 24 36Q28.3 34.3 30 30Z"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-invite': InviteSymbol
  }
}
