// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Invoice symbol. A paid invoice with a stamp: billing, receipts, invoices or statements.
 *
 * @tag c2-symbol-invoice
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-invoice')
export class InvoiceSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="34" ry="5"/><rect class="surface line" x="40" y="26" width="80" height="102" rx="6"/><path class="primary" d="M41.5 32a4.5 4.5 0 0 1 4.5-4.5h68a4.5 4.5 0 0 1 4.5 4.5v12h-77Z"/><path class="line-surface" d="M50 36h22"/><path class="line" d="M50 58h36M96 58h14M50 70h30M96 70h14M50 82h40M96 82h14"/><rect class="success" opacity="0.14" x="60" y="98" width="46" height="20" rx="4" transform="rotate(-10 83 108)"/><rect class="line-success" x="60" y="98" width="46" height="20" rx="4" transform="rotate(-10 83 108)"/><path class="line-success" d="m74 109 5 5 10-10"/><path class="accent" d="M130 30Q131.7 34.3 136 36Q131.7 37.7 130 42Q128.3 37.7 124 36Q128.3 34.3 130 30Z"/><path class="line-primary" d="M30 52v8M26 56h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-invoice': InvoiceSymbol
  }
}
