// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Location symbol. A pin on a folded map: an address, a store locator, delivery area or places.
 *
 * @tag c2-symbol-location
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-location')
export class LocationSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="42" ry="5"/><path class="surface line" d="M30 56 58 46l44 12 28-10v70l-28 10-44-12-28 10Z"/><path class="muted" d="M58 46v70l44 12V58Z"/><path class="line" d="M58 46v70M102 58v70M58 46l44 12M30 56l28-10"/><path class="primary line-surface" d="M80 24a20 20 0 0 1 20 20c0 16-20 38-20 38S60 60 60 44a20 20 0 0 1 20-20Z"/><circle class="surface" cx="80" cy="44" r="7"/><path class="accent" d="M128 24Q129.7 28.3 134 30Q129.7 31.7 128 36Q126.3 31.7 122 30Q126.3 28.3 128 24Z"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-location': LocationSymbol
  }
}
