// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Magic symbol. A magic wand with sparkles: generate with AI, auto-fill, smart suggestions or one-click setup.
 *
 * @tag c2-symbol-magic
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-magic')
export class MagicSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><g transform="rotate(45 72 92)"><rect class="ink" x="66" y="60" width="12" height="70" rx="4"/><rect class="surface line" x="66" y="60" width="12" height="16" rx="3"/></g><path class="accent" d="M98 38Q102.5 49.5 114 54Q102.5 58.5 98 70Q93.5 58.5 82 54Q93.5 49.5 98 38Z"/><path class="primary" d="M122 78Q124.2 83.8 130 86Q124.2 88.2 122 94Q119.8 88.2 114 86Q119.8 83.8 122 78Z"/><path class="primary" d="M70 27Q72 32 77 34Q72 36 70 41Q68 36 63 34Q68 32 70 27Z"/><path class="accent" d="M124 27Q125.4 30.6 129 32Q125.4 33.4 124 37Q122.6 33.4 119 32Q122.6 30.6 124 27Z"/><circle class="accent" cx="106" cy="104" r="3"/><circle class="primary-soft" cx="40" cy="60" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-magic': MagicSymbol
  }
}
