// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * No orders symbol. A blank receipt: no orders, purchases or invoices yet.
 *
 * @tag c2-symbol-no-orders
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-no-orders')
export class NoOrdersSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="32" ry="5"/><path class="surface line" d="M50 26h60v98l-7.5-6 -7.5 6l-7.5-6 -7.5 6l-7.5-6 -7.5 6l-7.5-6 -7.5 6Z"/><path class="line-primary" d="M62 44h36"/><path class="line" d="M62 60h22M62 72h28M62 84h16M92 60h6M92 72h6M92 84h6"/><path class="line" stroke-dasharray="3 5" d="M62 98h36"/><circle class="primary line-surface" cx="112" cy="108" r="14"/><path class="line-surface" d="M106 108h12"/><path class="accent" d="M34 38Q35.7 42.3 40 44Q35.7 45.7 34 50Q32.3 45.7 28 44Q32.3 42.3 34 38Z"/><circle class="accent" cx="128" cy="38" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-no-orders': NoOrdersSymbol
  }
}
