// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * No reviews symbol. A review card with empty stars: no ratings, reviews or testimonials yet.
 *
 * @tag c2-symbol-no-reviews
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-no-reviews')
export class NoReviewsSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><rect class="surface line" x="28" y="38" width="104" height="74" rx="10"/><path class="surface line" d="M52 112l-4 16 18-16"/><path class="muted" d="M46 54L48.2 58.9L53.6 59.5L49.6 63.2L50.7 68.5L46 65.8L41.3 68.5L42.4 63.2L38.4 59.5L43.8 58.9Z"/><path class="muted" d="M63 54L65.2 58.9L70.6 59.5L66.6 63.2L67.7 68.5L63 65.8L58.3 68.5L59.4 63.2L55.4 59.5L60.8 58.9Z"/><path class="muted" d="M80 54L82.2 58.9L87.6 59.5L83.6 63.2L84.7 68.5L80 65.8L75.3 68.5L76.4 63.2L72.4 59.5L77.8 58.9Z"/><path class="muted" d="M97 54L99.2 58.9L104.6 59.5L100.6 63.2L101.7 68.5L97 65.8L92.3 68.5L93.4 63.2L89.4 59.5L94.8 58.9Z"/><path class="muted" d="M114 54L116.2 58.9L121.6 59.5L117.6 63.2L118.7 68.5L114 65.8L109.3 68.5L110.4 63.2L106.4 59.5L111.8 58.9Z"/><path class="line" d="M42 84h64M42 96h40"/><path class="accent" d="M128 21Q130 26 135 28Q130 30 128 35Q126 30 121 28Q126 26 128 21Z"/><circle class="primary-soft" cx="32" cy="128" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-no-reviews': NoReviewsSymbol
  }
}
