// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Out of office symbol. A palm tree on an island: out of office, on vacation, away or on holiday.
 *
 * @tag c2-symbol-out-of-office
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-out-of-office')
export class OutOfOfficeSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><circle class="accent" cx="46" cy="48" r="12"/><path class="line-primary" opacity="0.5" d="M28 128h104"/><path class="accent" opacity="0.7" d="M40 124c12-12 68-12 80 0Z"/><path class="ink" d="M84 122c0-24 3-44 10-62l5 2c-6 17-9 36-9 60Z"/><path class="success" d="M96 60c-10-12-30-14-40-4 14-2 28 0 40 4Z"/><path class="success" d="M96 60c4-15 22-22 36-16-14 4-26 9-36 16Z"/><path class="success" d="M96 60c14-6 30 0 36 12-12-6-25-9-36-12Z"/><path class="success" d="M96 60c-13 3-24 14-24 27 6-11 15-21 24-27Z"/><circle class="ink" cx="92" cy="64" r="3.5"/><circle class="ink" cx="99" cy="65" r="3.5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-out-of-office': OutOfOfficeSymbol
  }
}
