// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Package delivered symbol. A closed parcel with a check badge: order delivered, shipment received.
 *
 * @tag c2-symbol-package-delivered
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-package-delivered')
export class PackageDeliveredSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="42" ry="5"/><path class="primary-soft line" d="M80 32 122 50 80 68 38 50Z"/><path class="surface line" d="M38 50v50l42 22V68Z"/><path class="muted line" d="M122 50v50l-42 22V68Z"/><path class="line-accent" d="M59 41 101 59v51"/><circle class="success line-surface" cx="120" cy="112" r="14"/><path class="line-surface" d="M114.5 112.5l3.5 3.5 7-7"/><path class="primary" d="M34 28Q35.7 32.3 40 34Q35.7 35.7 34 40Q32.3 35.7 28 34Q32.3 32.3 34 28Z"/><path class="line-accent" d="M130 26v8M126 30h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-package-delivered': PackageDeliveredSymbol
  }
}
