// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Page error symbol. A browser window with a dazed face: the page crashed, failed to load or an unexpected error.
 *
 * @tag c2-symbol-page-error
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-page-error')
export class PageErrorSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><rect class="surface line" x="26" y="36" width="108" height="84" rx="8"/><path class="muted line" d="M26 44a8 8 0 0 1 8-8h92a8 8 0 0 1 8 8v8H26Z"/><circle class="error" cx="36" cy="44" r="2.5"/><circle class="accent" cx="45" cy="44" r="2.5"/><circle class="success" cx="54" cy="44" r="2.5"/><path class="line-ink" d="m60 70 8 8m0-8-8 8M92 70l8 8m0-8-8 8M66 104a16 16 0 0 1 28 0"/><path class="accent" d="M128 21Q130 26 135 28Q130 30 128 35Q126 30 121 28Q126 26 128 21Z"/><circle class="primary" cx="30" cy="128" r="4"/><path class="line-accent" d="M132 124v8M128 128h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-page-error': PageErrorSymbol
  }
}
