// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Profile symbol. An ID card: your profile, account details, identity or a member card.
 *
 * @tag c2-symbol-profile
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-profile')
export class ProfileSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="44" ry="5"/><rect class="surface line" x="24" y="42" width="112" height="76" rx="8"/><path class="primary" d="M25.5 50a6.5 6.5 0 0 1 6.5-6.5h96a6.5 6.5 0 0 1 6.5 6.5v8h-109Z"/><circle class="primary-soft line" cx="56" cy="86" r="16"/><circle class="primary" cx="56" cy="81" r="5.5"/><path class="primary" d="M46 96.5a10 9 0 0 1 20 0 16 16 0 0 1-20 0Z"/><path class="line-primary" d="M84 78h36"/><path class="line" d="M84 90h28M84 102h20"/><path class="accent" d="M130 24Q131.7 28.3 136 30Q131.7 31.7 130 36Q128.3 31.7 124 30Q128.3 28.3 130 24Z"/><circle class="accent" cx="30" cy="128" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-profile': ProfileSymbol
  }
}
