// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * QR scan symbol. A QR code in a viewfinder: scan to connect, pair a device, check in or pay.
 *
 * @tag c2-symbol-qr-scan
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-qr-scan')
export class QrScanSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><path class="line-primary" d="M36 50V40a6 6 0 0 1 6-6h10M108 34h10a6 6 0 0 1 6 6v10M124 110v10a6 6 0 0 1-6 6h-10M52 126H42a6 6 0 0 1-6-6v-10"/><rect class="surface line" x="46" y="44" width="68" height="72" rx="4"/><rect class="ink" x="52" y="50" width="18" height="18" rx="3"/><rect class="surface" x="57" y="55" width="8" height="8" rx="1"/><rect class="ink" x="90" y="50" width="18" height="18" rx="3"/><rect class="surface" x="95" y="55" width="8" height="8" rx="1"/><rect class="ink" x="52" y="90" width="18" height="18" rx="3"/><rect class="surface" x="57" y="95" width="8" height="8" rx="1"/><rect class="ink" x="76" y="52" width="6" height="6" rx="1"/><rect class="ink" x="76" y="64" width="6" height="6" rx="1"/><rect class="ink" x="90" y="74" width="6" height="6" rx="1"/><rect class="ink" x="102" y="90" width="6" height="6" rx="1"/><rect class="ink" x="90" y="98" width="6" height="6" rx="1"/><rect class="ink" x="104" y="104" width="6" height="6" rx="1"/><rect class="ink" x="76" y="88" width="6" height="6" rx="1"/><rect class="ink" x="76" y="102" width="6" height="6" rx="1"/><path class="line-error" opacity="0.8" d="M30 80h100"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-qr-scan': QrScanSymbol
  }
}
