// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Savings symbol. A piggy bank and a coin: savings, a budget, a goal or money put aside.
 *
 * @tag c2-symbol-savings
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-savings')
export class SavingsSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="40" ry="5"/><rect class="primary-soft line" x="54" y="104" width="13" height="20" rx="4"/><rect class="primary-soft line" x="88" y="104" width="13" height="20" rx="4"/><path class="line" d="M40 84c-12 0-12-12-3-12"/><path class="primary-soft line" d="M86 62 96 42l10 22Z"/><ellipse class="primary-soft line" cx="78" cy="88" rx="40" ry="30"/><rect class="primary-soft line" x="112" y="78" width="16" height="22" rx="7"/><circle class="ink" cx="118" cy="89" r="1.8"/><circle class="ink" cx="123" cy="89" r="1.8"/><circle class="ink" cx="100" cy="78" r="3"/><path class="line-ink" d="M66 64h20"/><circle class="accent" cx="76" cy="38" r="12"/><circle class="line-surface" opacity="0.6" cx="76" cy="38" r="6"/><path class="primary" d="M122 24Q123.7 28.3 128 30Q123.7 31.7 122 36Q120.3 31.7 116 30Q120.3 28.3 122 24Z"/><path class="line-accent" d="M32 40v8M28 44h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-savings': SavingsSymbol
  }
}
