// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Server symbol. A healthy server rack: infrastructure, hosting, uptime, a deployment target or all systems operational.
 *
 * @tag c2-symbol-server
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-server')
export class ServerSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="40" ry="5"/><rect class="surface line" x="36" y="34" width="88" height="26" rx="6"/><circle class="success" cx="50" cy="47" r="4"/><path class="line" d="M64 47h28"/><circle class="ink" cx="108" cy="47" r="2.5"/><rect class="surface line" x="36" y="66" width="88" height="26" rx="6"/><circle class="success" cx="50" cy="79" r="4"/><path class="line" d="M64 79h28"/><circle class="ink" cx="108" cy="79" r="2.5"/><rect class="surface line" x="36" y="98" width="88" height="26" rx="6"/><circle class="success" cx="50" cy="111" r="4"/><path class="line" d="M64 111h28"/><circle class="ink" cx="108" cy="111" r="2.5"/><path class="primary" d="M130 24Q131.7 28.3 136 30Q131.7 31.7 130 36Q128.3 31.7 124 30Q128.3 28.3 130 24Z"/><circle class="accent" cx="28" cy="60" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-server': ServerSymbol
  }
}
