// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Unlocked symbol. An open padlock: access granted, unlocked, permissions given or a feature enabled.
 *
 * @tag c2-symbol-unlocked
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-unlocked')
export class UnlockedSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="36" ry="5"/><path class="line-ink" d="M58 72V54a22 22 0 0 1 42-9"/><rect class="success" x="42" y="70" width="76" height="56" rx="10"/><path class="surface" d="M80 88a6 6 0 0 0-3 11.2V110h6V99.2A6 6 0 0 0 80 88Z"/><path class="accent" d="M126 32Q128.2 37.8 134 40Q128.2 42.2 126 48Q123.8 42.2 118 40Q123.8 37.8 126 32Z"/><path class="line-primary" d="M34 46v8M30 50h8"/><circle class="primary-soft" cx="128" cy="110" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-unlocked': UnlockedSymbol
  }
}
