// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Update available symbol. An app window with a progress bar: an update is available or installing, a new version.
 *
 * @tag c2-symbol-update-available
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-update-available')
export class UpdateAvailableSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><rect class="surface line" x="28" y="36" width="104" height="80" rx="8"/><path class="muted line" d="M28 44a8 8 0 0 1 8-8h88a8 8 0 0 1 8 8v8H28Z"/><circle class="error" cx="38" cy="44" r="2.5"/><circle class="accent" cx="47" cy="44" r="2.5"/><circle class="success" cx="56" cy="44" r="2.5"/><path class="line-primary" d="M66.8 71.2A14 14 0 0 1 92.1 69M86.5 66.9L92.1 69L93.2 63.1"/><path class="line-primary" d="M93.2 80.8A14 14 0 0 1 67.9 83M73.5 85.1L67.9 83L66.8 88.9"/><rect class="muted" x="46" y="100" width="68" height="6" rx="3"/><rect class="primary" x="46" y="100" width="40" height="6" rx="3"/><circle class="success line-surface" cx="124" cy="112" r="14"/><path class="line-surface" d="M124 106v12m-5-5 5 5 5-5"/><path class="accent" d="M30 122Q31.7 126.3 36 128Q31.7 129.7 30 134Q28.3 129.7 24 128Q28.3 126.3 30 122Z"/><path class="line-accent" d="M130 20v8M126 24h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-update-available': UpdateAvailableSymbol
  }
}
