// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Upload failed symbol. A file with an upward arrow and an error badge: the upload failed, the file is too large or invalid.
 *
 * @tag c2-symbol-upload-failed
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-upload-failed')
export class UploadFailedSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><ellipse class="muted" cx="80" cy="132" rx="32" ry="5"/><path class="surface line" d="M50 30h36l24 24v66a6 6 0 0 1-6 6H50a6 6 0 0 1-6-6V36a6 6 0 0 1 6-6Z"/><path class="muted line" d="M86 30v18a6 6 0 0 0 6 6h18"/><path class="line-primary" d="M77 100V68m-11 11 11-11 11 11"/><rect class="muted" x="56" y="110" width="42" height="5" rx="2.5"/><rect class="error" x="56" y="110" width="26" height="5" rx="2.5"/><circle class="error line-surface" cx="112" cy="110" r="14"/><path class="line-surface" d="M107.5 105.5l9 9M116.5 105.5l-9 9"/><path class="accent" d="M32 44Q33.7 48.3 38 50Q33.7 51.7 32 56Q30.3 51.7 26 50Q30.3 48.3 32 44Z"/><path class="line-primary" d="M130 36v8M126 40h8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-upload-failed': UploadFailedSymbol
  }
}
