// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Video call symbol. A video call window: a meeting, a webinar, screen sharing or a live session.
 *
 * @tag c2-symbol-video-call
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-video-call')
export class VideoCallSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><rect class="surface line" x="22" y="32" width="116" height="82" rx="8"/><rect class="primary-soft" x="29" y="39" width="102" height="68" rx="3"/><circle class="primary" cx="72" cy="64" r="13"/><path class="primary" d="M48 107a24 24 0 0 1 48 0Z"/><rect class="accent line-surface" x="100" y="76" width="26" height="24" rx="4"/><circle class="error line-surface" cx="68" cy="124" r="9"/><circle class="ink line-surface" cx="92" cy="124" r="9"/><path class="line-surface" d="M63 124h10M92 120v8"/><path class="accent" d="M132 16Q133.7 20.3 138 22Q133.7 23.7 132 28Q130.3 23.7 126 22Q130.3 20.3 132 16Z"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-video-call': VideoCallSymbol
  }
}
