// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Warning symbol. An exclamation mark in an amber triangle: something needs attention before continuing.
 *
 * @tag c2-symbol-warning
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges, the light bulb, the rocket flame.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-warning')
export class WarningSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><circle class="warning" cx="80" cy="80" r="42" opacity="0.16"/><path class="warning" d="M74.8 47a6 6 0 0 1 10.4 0l29 50a6 6 0 0 1-5.2 9H51a6 6 0 0 1-5.2-9Z"/><path class="line-surface" d="M80 66v16M80 94v.01"/><path class="line-warning" d="M34 42v10M29 47h10"/><path class="line-primary" d="M124 34v8M120 38h8"/><circle class="primary-soft" cx="40" cy="114" r="5"/><circle class="warning" cx="124" cy="110" r="3.5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-warning': WarningSymbol
  }
}
