// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * Welcome symbol. A waving hand: welcome, hello, a first visit, a greeting or a new member.
 *
 * @tag c2-symbol-welcome
 *
 * @cssproperty {length} [--c2-symbol--size=120px] - Width and height of the symbol.
 * @cssproperty {number} [--c2-symbol--stroke-width=3] - Outline width, in units of the 160x160 canvas.
 * @cssproperty {color} [--c2-symbol__backdrop--color=#f4f4f5] - Soft disc behind the artwork.
 * @cssproperty {color} [--c2-symbol__surface--color=#ffffff] - Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.
 * @cssproperty {color} [--c2-symbol__muted--color=#e4e4e7] - Secondary fills: shadows, inactive bars, the inside of a box.
 * @cssproperty {color} [--c2-symbol__line--color=#a1a1aa] - Default outline colour.
 * @cssproperty {color} [--c2-symbol__ink--color=#71717a] - Small solid details: handles, dots, clock hands.
 * @cssproperty {color} [--c2-symbol__primary--color=#0265dc] - Accent fills and strokes.
 * @cssproperty {color} [--c2-symbol__primary-soft--color=#edf1fe] - Soft accent fills: a lens, a folder back, a chat bubble.
 * @cssproperty {color} [--c2-symbol__accent--color=#fbbf24] - Decorative warm highlight: stars, coins, light bulbs, flames, confetti.
 * @cssproperty {color} [--c2-symbol__success--color=#16a34a] - Success badges and check marks.
 * @cssproperty {color} [--c2-symbol__warning--color=#f59e0b] - Warning badges and hazard signs.
 * @cssproperty {color} [--c2-symbol__error--color=#dc2626] - Error badges and strike-throughs.
 */
@customElement('c2-symbol-welcome')
export class WelcomeSymbol extends SymbolElement {
  protected override renderSymbol() {
    return svg`<circle class="backdrop" cx="80" cy="80" r="64"/><g transform="rotate(-14 80 84)"><rect class="accent" x="50" y="44" width="12" height="40" rx="6"/><rect class="accent" x="63" y="36" width="12" height="46" rx="6"/><rect class="accent" x="76" y="38" width="12" height="44" rx="6"/><rect class="accent" x="89" y="46" width="12" height="36" rx="6"/><rect class="accent" x="36" y="80" width="14" height="36" rx="7" transform="rotate(-40 43 98)"/><rect class="accent" x="50" y="68" width="51" height="56" rx="20"/><path class="line-surface" opacity="0.6" d="M60 96a14 14 0 0 0 14 12"/></g><path class="line-primary" d="M112 36a20 20 0 0 1 10 14M118 26a32 32 0 0 1 16 22M36 118a20 20 0 0 1-8-14"/><path class="primary" d="M32 33Q34 38 39 40Q34 42 32 47Q30 42 25 40Q30 38 32 33Z"/><circle class="primary-soft" cx="126" cy="112" r="4"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-symbol-welcome': WelcomeSymbol
  }
}
