// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/menu. Import once, anywhere in the program:
//
//     import '@c2n/menu/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Menu, MenuEventMap } from '@c2n/menu'
import type { MenuItem, MenuItemEventMap } from '@c2n/menu/menu-item.js'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-menu': DefineComponent<
      C2Props<Menu> & {
        'cross-offset'?: unknown
        'fit-anchor'?: unknown
        'keep-open'?: unknown
        'aria-label'?: unknown
        onMenuSelect?: (event: MenuEventMap['menu-select']) => void
        onToggle?: (event: MenuEventMap['toggle']) => void
      }
    >
    'c2-menu-item': DefineComponent<
      C2Props<MenuItem> & {
        'keep-open'?: unknown
        'reserve-indicator'?: unknown
        onMenuSelect?: (event: MenuItemEventMap['menu-select']) => void
        onCheckedChange?: (event: MenuItemEventMap['checked-change']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
