// GENERATED by @c2n/framework-types. Do not edit by hand.
// Every module of @c2n/tabs. Importing this registers each of its elements.

export * from '@c2n/tabs'
export * from '@c2n/tabs/tab-context.js'
export * from '@c2n/tabs/tab.js'
