/**
 * Generates the parts of the plugin that derive from other sources:
 * - `skills/c2n-components/references/components-cheatsheet.md` from `@c2n/mcp`'s registry (the offline fallback when
 *   the MCP server is not connected),
 * - `.claude-plugin/plugin.json` (with the `version`) and the `@c2n/mcp@<version>` pin in `.mcp.json` from `package.json`
 *   (lerna runs this through the `version` lifecycle script during `lerna publish`).
 *
 * Node 24 type stripping: erasable TypeScript only.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

interface Registry {
  c2nVersion: string
  components: Record<
    string,
    {
      id: string
      package: string
      title: string
      description: string
      category: string
      status: string
      tagPattern?: string
      icons?: string[]
      elements: {
        tag: string
        className: string
        modulePath: string
        attributes: { name: string; type: string; default?: string }[]
        slots: { name: string }[]
        events: { name: string }[]
        cssProperties: { name: string; default?: string; token?: string; property: string; state?: string }[]
      }[]
      presets?: { items: { name: string }[] }
    }
  >
  theme: { tokens: { name: string; light: string | null; description: string }[] }
}

const require = createRequire(import.meta.url)
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const version: string = JSON.parse(readFileSync(join(packageRoot, 'package.json'), 'utf8')).version
const registry = JSON.parse(readFileSync(require.resolve('@c2n/mcp/registry.json'), 'utf8')) as Registry

/** The most useful variables of an element: colours/backgrounds/borders/radius first, root part before sub-parts. */
function keyVariables(element: Registry['components'][string]['elements'][number], max = 8): string[] {
  const score = (p: { property: string; state?: string; token?: string }) =>
    (p.token ? 4 : 0) +
    (/background|color/.test(p.property) ? 3 : 0) +
    (/border|radius/.test(p.property) ? 2 : 0) +
    (/size|height|padding|font/.test(p.property) ? 1 : 0) -
    (p.state ? 2 : 0)
  return [...element.cssProperties]
    .sort((a, b) => score(b) - score(a))
    .slice(0, max)
    .map((p) => `\`${p.name}\`${p.default ? ` = \`${p.default}\`` : ''}${p.token ? ` (→ \`${p.token}\`)` : ''}`)
}

function renderCheatsheet(): string {
  const out = [
    `# c2n components cheatsheet`,
    ``,
    `GENERATED by \`packages/tools/skill/scripts/build-skill.ts\` from the @c2n/mcp registry (c2n ${registry.c2nVersion}). Do not edit by hand.`,
    `Offline fallback when the c2n MCP server is not connected; the MCP tools (\`get_component\`, \`get_examples\`) have the complete API and examples.`,
    ``,
    `Variable grammar: \`--c2-<component>__<part>[__<state>]--<property>\`; states: hover, active, focus, selected, disabled, open, error, read-only. \`(→ token)\` marks variables the base theme maps to a \`--c2-theme--*\` token.`,
    ``,
  ]
  const byCategory = new Map<string, Registry['components'][string][]>()
  for (const c of Object.values(registry.components)) byCategory.set(c.category, [...(byCategory.get(c.category) ?? []), c])
  for (const [category, components] of [...byCategory.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    out.push(`## ${category}`, ``)
    for (const c of components.sort((a, b) => a.title.localeCompare(b.title))) {
      const primary = c.elements[0]
      out.push(`### ${c.title} — \`${c.tagPattern ?? primary.tag}\``, ``)
      out.push(
        `${c.description || ''} Package \`${c.package}\`${c.status === 'undocumented' ? ' (no docs page yet)' : ''}. Register: \`import '${c.tagPattern ? primary.modulePath : c.package}'\`.`,
      )
      if (c.tagPattern)
        out.push(
          `${c.icons?.length} icons; tag \`${c.tagPattern}\`, module \`${primary.modulePath}\`. Shared variables: ${keyVariables(primary, 4).join(', ')}.`,
        )
      for (const element of c.elements) {
        if (c.elements.length > 1) out.push(``, `**\`${element.tag}\`** (\`${element.modulePath}\`)`)
        if (element.attributes.length) out.push(`- Attributes: ${element.attributes.map((a) => `\`${a.name}\`${a.type ? ` (${a.type})` : ''}`).join(', ')}`)
        if (element.slots.length) out.push(`- Slots: ${element.slots.map((s) => `\`${s.name || 'default'}\``).join(', ')}`)
        if (element.events.length) out.push(`- Events: ${element.events.map((e) => `\`${e.name}\``).join(', ')}`)
        const vars = keyVariables(element)
        if (vars.length) out.push(`- Key variables (${element.cssProperties.length} total): ${vars.join(', ')}`)
      }
      if (c.presets?.items.length) out.push(`- Presets: ${c.presets.items.map((p) => p.name).join(', ')}`)
      out.push(``)
    }
  }
  out.push(`## Theme tokens`, ``, `Set on \`:root\` after importing \`@c2n/theme/theme.css\` (dark values under \`[data-theme='dark']\` / \`.c2-dark\`).`, ``)
  for (const t of registry.theme.tokens) out.push(`- \`${t.name}\`${t.light === null ? '' : ` = \`${t.light}\``} — ${t.description}`)
  out.push(``)
  return out.join('\n')
}

async function writeFormatted(file: string, content: string): Promise<void> {
  const config = (await resolveConfig(file)) ?? {}
  writeFileSync(file, await format(content, { ...config, filepath: file }))
}

const cheatsheet = join(packageRoot, 'skills/c2n-components/references/components-cheatsheet.md')
await writeFormatted(cheatsheet, renderCheatsheet())

// plugin.json is written in full (wireit removes declared outputs before running this script).
const pluginJson = {
  name: 'c2n',
  description:
    'Build UI with the c2n web components (c2-* Lit elements from @c2n/*): theme once with @c2n/theme, use the tags directly, turn repeated looks into variant components. Bundles the @c2n/mcp server.',
  version,
  author: { name: 'code2nguyen' },
  homepage: 'https://code2nguyen.github.io/web-components/',
  repository: 'https://github.com/code2nguyen/web-components',
  license: 'MIT',
  keywords: ['web components', 'lit', 'design system', 'theme', 'c2n'],
}
await writeFormatted(join(packageRoot, '.claude-plugin/plugin.json'), JSON.stringify(pluginJson, null, 2) + '\n')

const mcpJsonFile = join(packageRoot, '.mcp.json')
await writeFormatted(
  mcpJsonFile,
  JSON.stringify({ mcpServers: { c2n: { type: 'stdio', command: 'npx', args: ['-y', `@c2n/mcp@${version}`] } } }, null, 2) + '\n',
)

console.log(`[build-skill] cheatsheet for ${Object.keys(registry.components).length} components, plugin version ${version}`)
