/**
 * Generates the parts of the plugin that derive from other sources:
 * - `skills/c2n-components/references/component-catalog.md` from `@c2n/mcp`'s registry (a compact discovery index
 *   for when the MCP server is not connected),
 * - the portable and Claude plugin manifests plus their `@c2n/mcp@<version>` pins from `package.json`
 *   (lerna runs this through the `version` lifecycle script during `lerna publish`).
 *
 * Node 24 type stripping: erasable TypeScript only.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

interface Registry {
  c2nVersion: string
  components: Record<
    string,
    {
      id: string
      package: string
      title: string
      description: string
      category: string
      tagPattern?: string
      elements: {
        tag: string
      }[]
    }
  >
}

const require = createRequire(import.meta.url)
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const version: string = JSON.parse(readFileSync(join(packageRoot, 'package.json'), 'utf8')).version
const registry = JSON.parse(readFileSync(require.resolve('@c2n/mcp/registry.json'), 'utf8')) as Registry

function renderCatalog(): string {
  const out = [
    `# c2n component catalog`,
    ``,
    `GENERATED by \`packages/tools/skill/scripts/build-skill.ts\` from the @c2n/mcp registry (c2n ${registry.c2nVersion}). Do not edit by hand.`,
    `Use this compact index only to discover a likely component when the c2n MCP server is unavailable. It intentionally omits component APIs and examples. Read the selected installed package's \`custom-elements.json\` for exact attributes, slots, events, CSS parts and CSS properties.`,
    ``,
  ]
  const byCategory = new Map<string, Registry['components'][string][]>()
  for (const c of Object.values(registry.components)) byCategory.set(c.category, [...(byCategory.get(c.category) ?? []), c])
  for (const [category, components] of [...byCategory.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    out.push(`## ${category}`, ``)
    for (const c of components.sort((a, b) => a.title.localeCompare(b.title))) {
      const tags = c.tagPattern ?? c.elements.map((element) => element.tag).join(', ')
      const description = c.description || `${c.title} component for c2n applications.`
      out.push(`- **${c.title}** — \`${tags}\` · \`${c.package}\` — ${description}`)
    }
    out.push(``)
  }
  return out.join('\n')
}

async function writeFormatted(file: string, content: string): Promise<void> {
  const config = (await resolveConfig(file)) ?? {}
  writeFileSync(file, await format(content, { ...config, filepath: file }))
}

const catalog = join(packageRoot, 'skills/c2n-components/references/component-catalog.md')
await writeFormatted(catalog, renderCatalog())

// plugin.json is written in full (wireit removes declared outputs before running this script).
const pluginJson = {
  name: 'c2n',
  description:
    'Build UI with the c2n web components (c2-* Lit elements from @c2n/*): theme once with @c2n/theme, use the tags directly, turn repeated looks into variant components. Bundles the @c2n/mcp server.',
  version,
  author: { name: 'code2nguyen' },
  homepage: 'https://code2nguyen.github.io/web-components/',
  repository: 'https://github.com/code2nguyen/web-components',
  license: 'MIT',
  keywords: ['web components', 'lit', 'design system', 'theme', 'c2n'],
}
await writeFormatted(join(packageRoot, '.claude-plugin/plugin.json'), JSON.stringify(pluginJson, null, 2) + '\n')

const mcpServer = { type: 'stdio', command: 'npx', args: ['-y', `@c2n/mcp@${version}`] }
await writeFormatted(join(packageRoot, '.mcp.json'), JSON.stringify({ mcpServers: { c2n: mcpServer } }, null, 2) + '\n')
await writeFormatted(
  join(packageRoot, 'plugin.json'),
  JSON.stringify(
    {
      $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
      ...pluginJson,
      extensions: {
        'com.openai': {
          interface: {
            displayName: 'c2n Web Components',
            shortDescription: 'Build and theme applications with c2n components',
            longDescription: 'Component APIs, examples, theme guidance and reusable workflows for applications built with @c2n web components.',
            developerName: 'code2nguyen',
            category: 'Developer Tools',
            capabilities: ['Read'],
            websiteURL: 'https://code2nguyen.github.io/web-components/',
            defaultPrompt: ['Use c2n Web Components to build this interface with the appropriate c2-* elements and theme tokens.'],
          },
        },
      },
    },
    null,
    2,
  ) + '\n',
)
await writeFormatted(
  join(packageRoot, 'mcp.json'),
  JSON.stringify({ $schema: 'https://agent-plugins.org/schemas/1.0.0/mcp.schema.json', mcpServers: { c2n: mcpServer } }, null, 2) + '\n',
)

console.log(`[build-skill] catalog for ${Object.keys(registry.components).length} components, plugin version ${version}`)
