/**
 * Symbol generator for `@c2n/symbols`.
 *
 * Unlike the icon packages, the artwork is authored in this package: `svg/<name>.svg` holds one hand-drawn
 * 160x160 illustration and `svg/catalog.json` its title, category and description. The generator validates every
 * source against the colour-role contract of `src/symbol.scss` (fills and strokes come from `class` only, never
 * from a hard-coded colour, so a theme recolours the whole set), strips the shared `<svg>` wrapper (which the
 * `SymbolElement` base class owns) and emits one Lit custom element per symbol into `src/symbols/<name>.ts`, plus
 * the `src/index.ts` barrel and `src/symbol-names.ts`.
 *
 * Output is formatted with the repo's prettier config so the committed files pass `format:check`.
 *
 * Run with `npm run generate -w packages/icons/symbols` (Node >= 22.18 / 24: native type stripping, so keep this
 * file to erasable TypeScript syntax only).
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

const TAG_PREFIX = 'c2-symbol-'
const CLASS_SUFFIX = 'Symbol'
const CATEGORIES = ['empty', 'status', 'error', 'security', 'commerce', 'communication', 'files', 'onboarding'] as const

// Every public variable of the set, in documentation order. The generator checks this list against the `$theme`
// map of `src/symbol.scss` so the JSDoc defaults cannot drift from the stylesheet.
const CSS_PROPERTIES: { name: string; type: string; description: string }[] = [
  { name: 'size', type: 'length', description: 'Width and height of the symbol.' },
  { name: 'stroke-width', type: 'number', description: 'Outline width, in units of the 160x160 canvas.' },
  { name: 'backdrop--color', type: 'color', description: 'Soft disc behind the artwork.' },
  { name: 'surface--color', type: 'color', description: 'Faces of objects (paper, screens, boxes) and marks drawn on coloured shapes.' },
  { name: 'muted--color', type: 'color', description: 'Secondary fills: shadows, inactive bars, the inside of a box.' },
  { name: 'line--color', type: 'color', description: 'Default outline colour.' },
  { name: 'ink--color', type: 'color', description: 'Small solid details: handles, dots, clock hands.' },
  { name: 'primary--color', type: 'color', description: 'Accent fills and strokes.' },
  { name: 'primary-soft--color', type: 'color', description: 'Soft accent fills: a lens, a folder back, a chat bubble.' },
  { name: 'accent--color', type: 'color', description: 'Decorative warm highlight: stars, coins, light bulbs, flames, confetti.' },
  { name: 'success--color', type: 'color', description: 'Success badges and check marks.' },
  { name: 'warning--color', type: 'color', description: 'Warning badges and hazard signs.' },
  { name: 'error--color', type: 'color', description: 'Error badges and strike-throughs.' },
]

const FILL_ROLES = ['backdrop', 'surface', 'muted', 'ink', 'primary', 'primary-soft', 'accent', 'success', 'warning', 'error']
const ALLOWED_CLASSES = new Set(['line', ...FILL_ROLES, ...FILL_ROLES.map((role) => `line-${role}`)])
const ALLOWED_ELEMENTS = new Set(['g', 'path', 'circle', 'ellipse', 'rect', 'line', 'polyline', 'polygon'])
const FORBIDDEN_ATTRIBUTES = /\s(fill|stroke|stroke-width|style|color|href|xlink:href|on[a-z]+)=/
const WRAPPER = /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg" viewBox="0 0 160 160">([\s\S]*)<\/svg>\s*$/

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const svgDir = join(packageRoot, 'svg')
const srcDir = join(packageRoot, 'src')
const symbolsOutDir = join(srcDir, 'symbols')

const header = '// GENERATED by scripts/symbol-generator from svg/. Do not edit by hand.'

type Category = (typeof CATEGORIES)[number]

interface CatalogEntry {
  title: string
  category: Category
  description: string
}

interface SymbolSource extends CatalogEntry {
  /** Symbol name, e.g. `empty-inbox`. */
  name: string
  /** Inner SVG markup without the `<svg>` wrapper. */
  body: string
}

function toPascalCase(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')
}

function toClassName(name: string): string {
  return `${toPascalCase(name)}${CLASS_SUFFIX}`
}

function toTemplateLiteralBody(markup: string): string {
  return markup.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function readThemeDefaults(): Map<string, string> {
  const scss = readFileSync(join(srcDir, 'symbol.scss'), 'utf8')
  const map = /\$theme:\s*\(([\s\S]*?)\n\s*\)/.exec(scss)
  if (!map) throw new Error('[symbol-generator] src/symbol.scss: no $theme map')
  const defaults = new Map<string, string>()
  for (const line of map[1].split('\n')) {
    const entry = /^\s*([a-z-]+):\s*(.+?),?\s*$/.exec(line)
    if (entry) defaults.set(entry[1], entry[2])
  }
  const documented = CSS_PROPERTIES.map((p) => p.name)
  const missing = [...defaults.keys()].filter((name) => !documented.includes(name))
  const stale = documented.filter((name) => !defaults.has(name))
  if (missing.length || stale.length) {
    throw new Error(
      `[symbol-generator] CSS_PROPERTIES and the $theme map disagree: undocumented ${missing.join(', ') || '-'}; unknown ${stale.join(', ') || '-'}`,
    )
  }
  return defaults
}

/** Enforce the colour-role contract: every colour comes from a class the stylesheet knows. */
function validateBody(file: string, body: string): void {
  const fail = (reason: string) => {
    throw new Error(`[symbol-generator] svg/${file}: ${reason}`)
  }
  for (const [, element] of body.matchAll(/<([a-zA-Z][\w:-]*)/g)) {
    if (!ALLOWED_ELEMENTS.has(element)) fail(`<${element}> is not allowed (use ${[...ALLOWED_ELEMENTS].join(', ')})`)
  }
  const attribute = FORBIDDEN_ATTRIBUTES.exec(body)
  if (attribute) fail(`the ${attribute[1]} attribute is not allowed: colour and stroke come from a class`)
  for (const [, classList] of body.matchAll(/\sclass="([^"]*)"/g)) {
    for (const name of classList.split(/\s+/).filter(Boolean)) {
      if (!ALLOWED_CLASSES.has(name)) fail(`unknown class "${name}" (use ${[...ALLOWED_CLASSES].join(', ')})`)
    }
  }
}

function readSymbolSources(): SymbolSource[] {
  const catalog: Record<string, CatalogEntry> = JSON.parse(readFileSync(join(svgDir, 'catalog.json'), 'utf8'))
  const files = readdirSync(svgDir)
    .filter((file) => file.endsWith('.svg'))
    .sort()
  const names = files.map((file) => basename(file, '.svg'))
  const uncatalogued = names.filter((name) => !catalog[name])
  const orphaned = Object.keys(catalog).filter((name) => !names.includes(name))
  if (uncatalogued.length) throw new Error(`[symbol-generator] missing from svg/catalog.json: ${uncatalogued.join(', ')}`)
  if (orphaned.length) throw new Error(`[symbol-generator] svg/catalog.json lists symbols without an SVG: ${orphaned.join(', ')}`)

  return files.map((file) => {
    const name = basename(file, '.svg')
    if (!/^[a-z][a-z0-9-]*$/.test(name)) throw new Error(`[symbol-generator] svg/${file}: file names are kebab-case`)
    const entry = catalog[name]
    if (!CATEGORIES.includes(entry.category)) throw new Error(`[symbol-generator] ${name}: unknown category "${entry.category}"`)
    const match = WRAPPER.exec(readFileSync(join(svgDir, file), 'utf8').trim())
    if (!match) throw new Error(`[symbol-generator] svg/${file}: expected <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160">`)
    const body = match[1]
      .trim()
      .split('\n')
      .map((line) => line.trim())
      .join('')
    validateBody(file, body)
    return { name, body, ...entry }
  })
}

function renderSymbolModule({ name, title, description, body }: SymbolSource, defaults: Map<string, string>): string {
  const tag = `${TAG_PREFIX}${name}`
  const className = toClassName(name)
  const cssProperties = CSS_PROPERTIES.map(({ name: property, type, description: text }) => {
    const variable = property.includes('--') ? `--c2-symbol__${property}` : `--c2-symbol--${property}`
    return ` * @cssproperty {${type}} [${variable}=${defaults.get(property)}] - ${text}`
  }).join('\n')
  return `${header}
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { SymbolElement } from '../symbol'

/**
 * ${title} symbol. ${description}
 *
 * @tag ${tag}
 *
${cssProperties}
 */
@customElement('${tag}')
export class ${className} extends SymbolElement {
  protected override renderSymbol() {
    return svg\`${toTemplateLiteralBody(body)}\`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    '${tag}': ${className}
  }
}
`
}

function renderIndexModule(sources: SymbolSource[]): string {
  const exports = sources.map(({ name }) => `export * from './symbols/${name}'`).join('\n')
  return `${header}
// Importing this barrel registers every symbol element. Prefer importing individual symbols
// (\`@c2n/symbols/symbols/<name>.js\`) in production bundles.
export * from './symbol'
export * from './symbol-names'
${exports}
`
}

function renderSymbolNamesModule(sources: SymbolSource[]): string {
  const names = sources.map(({ name }) => `'${name}'`).join(', ')
  const catalog = sources
    .map(
      ({ name, title, category, description }) =>
        `{ name: '${name}', title: ${JSON.stringify(title)}, category: '${category}', description: ${JSON.stringify(description)} }`,
    )
    .join(',\n')
  return `${header}
export const symbolTagPrefix = '${TAG_PREFIX}'

export const symbolNames = [${names}] as const

export type SymbolName = (typeof symbolNames)[number]

export const symbolCategories = [${CATEGORIES.map((c) => `'${c}'`).join(', ')}] as const

export type SymbolCategory = (typeof symbolCategories)[number]

export interface SymbolInfo {
  name: SymbolName
  title: string
  category: SymbolCategory
  description: string
}

/** Title, category and description of every symbol, for pickers and galleries. */
export const symbolCatalog: readonly SymbolInfo[] = [
${catalog}
]

/** Custom element tag name for a symbol, e.g. \`empty-inbox\` -> \`${TAG_PREFIX}empty-inbox\`. */
export function symbolTag(name: SymbolName): \`${TAG_PREFIX}\${SymbolName}\` {
  return \`${TAG_PREFIX}\${name}\`
}
`
}

async function writeFormatted(filePath: string, code: string): Promise<void> {
  const config = (await resolveConfig(filePath)) ?? {}
  const formatted = await format(code, { ...config, filepath: filePath })
  writeFileSync(filePath, formatted)
}

async function main(): Promise<void> {
  const defaults = readThemeDefaults()
  const sources = readSymbolSources()
  if (sources.length === 0) throw new Error('[symbol-generator] no symbols found in svg/')

  rmSync(symbolsOutDir, { recursive: true, force: true })
  mkdirSync(symbolsOutDir, { recursive: true })

  await Promise.all([
    ...sources.map((source) => writeFormatted(join(symbolsOutDir, `${source.name}.ts`), renderSymbolModule(source, defaults))),
    writeFormatted(join(srcDir, 'index.ts'), renderIndexModule(sources)),
    writeFormatted(join(srcDir, 'symbol-names.ts'), renderSymbolNamesModule(sources)),
  ])

  console.log(`[symbol-generator] Generated ${sources.length} symbols from svg/`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
