// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/description-list. Import once, anywhere in the program:
//
//     import '@c2n/description-list/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { DescriptionItem } from '@c2n/description-list/description-item.js'
import type { DescriptionList } from '@c2n/description-list'
import type { DescriptionValue } from '@c2n/description-list/description-value.js'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-description-item': DefineComponent<
      C2Props<DescriptionItem> & {
        'empty-text'?: unknown
      }
    >
    'c2-description-list': DefineComponent<
      C2Props<DescriptionList> & {
        'value-labels'?: unknown
        'label-heading'?: unknown
      }
    >
    'c2-description-value': DefineComponent<C2Props<DescriptionValue>>
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
