// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/number-input. Import once, anywhere in the program:
//
//     import '@c2n/number-input/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { NumberInput, NumberInputEventMap } from '@c2n/number-input'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-number-input': DefineComponent<
      C2Props<NumberInput> & {
        readonly?: unknown
        'hide-steppers'?: unknown
        'error-text'?: unknown
        'aria-label'?: unknown
        onInput?: (event: NumberInputEventMap['input']) => void
        onChange?: (event: NumberInputEventMap['change']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
