/**
 * Task icon generator for `@c2n/task-icons`.
 *
 * Like `@c2n/symbols`, the artwork is authored in this package: `svg/<name>.svg` holds one hand-drawn 24x24 duotone
 * icon and `svg/catalog.json` its title, category and keywords. The generator validates every source against the
 * styling contract of `src/task-icon.scss` (an element is an outline unless its class makes it `tone`, `fill` or
 * `solid`; no hard-coded colour or stroke, so the icon follows `currentColor` and the theme), strips the shared
 * `<svg>` wrapper (which the `TaskIconElement` base class owns) and emits one Lit custom element per icon into
 * `src/icons/<name>.ts`, plus the `src/index.ts` barrel and `src/task-icon-names.ts`.
 *
 * Output is formatted with the repo's prettier config so the committed files pass `format:check`.
 *
 * Run with `npm run generate -w packages/icons/task-icons` (Node >= 22.18 / 24: native type stripping, so keep this
 * file to erasable TypeScript syntax only).
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

const TAG_PREFIX = 'c2-task-icon-'
const CLASS_SUFFIX = 'TaskIcon'
const CATEGORIES = [
  'work',
  'communication',
  'tech',
  'learning',
  'health',
  'sport',
  'home',
  'family',
  'food',
  'shopping',
  'finance',
  'travel',
  'leisure',
  'nature',
  'planning',
] as const

// Every public variable of the set, in documentation order. The generator checks this list against the `$theme`
// map of `src/task-icon.scss` so the JSDoc defaults cannot drift from the stylesheet.
const CSS_PROPERTIES: { name: string; type: string; description: string }[] = [
  { name: 'size', type: 'length', description: 'Width and height of the icon.' },
  { name: 'color', type: 'color', description: 'Outline and solid colour. Inherits the text colour by default.' },
  { name: 'stroke-width', type: 'number', description: 'Outline width, in units of the 24x24 canvas.' },
  { name: 'tone--color', type: 'color', description: 'Colour of the soft duotone fill.' },
  { name: 'tone--opacity', type: 'number', description: 'Opacity of the soft duotone fill; 0 draws outlines only.' },
]

const ALLOWED_CLASSES = new Set(['tone', 'fill', 'solid'])
const ALLOWED_ELEMENTS = new Set(['g', 'path', 'circle', 'ellipse', 'rect', 'line', 'polyline', 'polygon'])
const FORBIDDEN_ATTRIBUTES = /\s(fill|stroke|stroke-width|style|color|opacity|href|xlink:href|on[a-z]+)=/
const WRAPPER = /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg" viewBox="0 0 24 24">([\s\S]*)<\/svg>\s*$/

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const svgDir = join(packageRoot, 'svg')
const srcDir = join(packageRoot, 'src')
const iconsOutDir = join(srcDir, 'icons')

const header = '// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.'

type Category = (typeof CATEGORIES)[number]

interface CatalogEntry {
  title: string
  category: Category
  keywords: string[]
}

interface IconSource extends CatalogEntry {
  /** Icon name, e.g. `video-call`. */
  name: string
  /** Inner SVG markup without the `<svg>` wrapper. */
  body: string
}

function toPascalCase(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')
}

function toClassName(name: string): string {
  return `${toPascalCase(name)}${CLASS_SUFFIX}`
}

function toTemplateLiteralBody(markup: string): string {
  return markup.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function readThemeDefaults(): Map<string, string> {
  const scss = readFileSync(join(srcDir, 'task-icon.scss'), 'utf8')
  const map = /\$theme:\s*\(([\s\S]*?)\n\s*\)/.exec(scss)
  if (!map) throw new Error('[task-icon-generator] src/task-icon.scss: no $theme map')
  const defaults = new Map<string, string>()
  for (const line of map[1].split('\n')) {
    const entry = /^\s*([a-z-]+):\s*(.+?),?\s*$/.exec(line)
    if (entry) defaults.set(entry[1], entry[2])
  }
  const documented = CSS_PROPERTIES.map((p) => p.name)
  const missing = [...defaults.keys()].filter((name) => !documented.includes(name))
  const stale = documented.filter((name) => !defaults.has(name))
  if (missing.length || stale.length) {
    throw new Error(
      `[task-icon-generator] CSS_PROPERTIES and the $theme map disagree: undocumented ${missing.join(', ') || '-'}; unknown ${stale.join(', ') || '-'}`,
    )
  }
  return defaults
}

/** Enforce the styling contract: colour and stroke come from the stylesheet, never from the drawing. */
function validateBody(file: string, body: string): void {
  const fail = (reason: string) => {
    throw new Error(`[task-icon-generator] svg/${file}: ${reason}`)
  }
  for (const [, element] of body.matchAll(/<([a-zA-Z][\w:-]*)/g)) {
    if (!ALLOWED_ELEMENTS.has(element)) fail(`<${element}> is not allowed (use ${[...ALLOWED_ELEMENTS].join(', ')})`)
  }
  const attribute = FORBIDDEN_ATTRIBUTES.exec(body)
  if (attribute) fail(`the ${attribute[1]} attribute is not allowed: colour and stroke come from the stylesheet`)
  for (const [, classList] of body.matchAll(/\sclass="([^"]*)"/g)) {
    for (const name of classList.split(/\s+/).filter(Boolean)) {
      if (!ALLOWED_CLASSES.has(name)) fail(`unknown class "${name}" (use ${[...ALLOWED_CLASSES].join(', ')})`)
    }
  }
}

function readIconSources(): IconSource[] {
  const catalog: Record<string, CatalogEntry> = JSON.parse(readFileSync(join(svgDir, 'catalog.json'), 'utf8'))
  const files = readdirSync(svgDir)
    .filter((file) => file.endsWith('.svg'))
    .sort()
  const names = files.map((file) => basename(file, '.svg'))
  const uncatalogued = names.filter((name) => !catalog[name])
  const orphaned = Object.keys(catalog).filter((name) => !names.includes(name))
  if (uncatalogued.length) throw new Error(`[task-icon-generator] missing from svg/catalog.json: ${uncatalogued.join(', ')}`)
  if (orphaned.length) throw new Error(`[task-icon-generator] svg/catalog.json lists icons without an SVG: ${orphaned.join(', ')}`)

  return files.map((file) => {
    const name = basename(file, '.svg')
    if (!/^[a-z][a-z0-9-]*$/.test(name)) throw new Error(`[task-icon-generator] svg/${file}: file names are kebab-case`)
    const entry = catalog[name]
    if (!CATEGORIES.includes(entry.category)) throw new Error(`[task-icon-generator] ${name}: unknown category "${entry.category}"`)
    if (!Array.isArray(entry.keywords) || entry.keywords.some((keyword) => !/^[a-z0-9][a-z0-9:-]*$/.test(keyword))) {
      throw new Error(`[task-icon-generator] ${name}: keywords are lower-case words`)
    }
    const match = WRAPPER.exec(readFileSync(join(svgDir, file), 'utf8').trim())
    if (!match) throw new Error(`[task-icon-generator] svg/${file}: expected <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">`)
    const body = match[1]
      .trim()
      .split('\n')
      .map((line) => line.trim())
      .join('')
    validateBody(file, body)
    return { name, body, ...entry }
  })
}

function renderIconModule({ name, title, keywords, body }: IconSource, defaults: Map<string, string>): string {
  const tag = `${TAG_PREFIX}${name}`
  const className = toClassName(name)
  const cssProperties = CSS_PROPERTIES.map(({ name: property, type, description: text }) => {
    const variable = property.includes('--') ? `--c2-task-icon__${property}` : `--c2-task-icon--${property}`
    return ` * @cssproperty {${type}} [${variable}=${defaults.get(property)}] - ${text}`
  }).join('\n')
  return `${header}
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * ${title} task icon. For tasks about: ${keywords.join(', ')}.
 *
 * @tag ${tag}
 *
${cssProperties}
 */
@customElement('${tag}')
export class ${className} extends TaskIconElement {
  protected override renderIcon() {
    return svg\`${toTemplateLiteralBody(body)}\`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    '${tag}': ${className}
  }
}
`
}

function renderIndexModule(sources: IconSource[]): string {
  const exports = sources.map(({ name }) => `export * from './icons/${name}'`).join('\n')
  return `${header}
// Importing this barrel registers every task icon element. Prefer importing individual icons
// (\`@c2n/task-icons/icons/<name>.js\`) in production bundles.
export * from './task-icon'
export * from './task-icon-names'
export * from './suggest-task-icon'
${exports}
`
}

function renderNamesModule(sources: IconSource[]): string {
  const names = sources.map(({ name }) => `'${name}'`).join(', ')
  const catalog = sources
    .map(
      ({ name, title, category, keywords }) =>
        `{ name: '${name}', title: ${JSON.stringify(title)}, category: '${category}', keywords: ${JSON.stringify(keywords)} }`,
    )
    .join(',\n')
  return `${header}
export const taskIconTagPrefix = '${TAG_PREFIX}'

export const taskIconNames = [${names}] as const

export type TaskIconName = (typeof taskIconNames)[number]

export const taskIconCategories = [${CATEGORIES.map((c) => `'${c}'`).join(', ')}] as const

export type TaskIconCategory = (typeof taskIconCategories)[number]

export interface TaskIconInfo {
  name: TaskIconName
  title: string
  category: TaskIconCategory
  /** Subjects the icon stands for, used by search fields and \`suggestTaskIcon()\`. */
  keywords: readonly string[]
}

/** Title, category and keywords of every task icon, for pickers and galleries. */
export const taskIconCatalog: readonly TaskIconInfo[] = [
${catalog}
]

/** Whether a string names a task icon of this set. */
export function isTaskIconName(name: string): name is TaskIconName {
  return (taskIconNames as readonly string[]).includes(name)
}

/** Custom element tag name for a task icon, e.g. \`video-call\` -> \`${TAG_PREFIX}video-call\`. */
export function taskIconTag(name: TaskIconName): \`${TAG_PREFIX}\${TaskIconName}\` {
  return \`${TAG_PREFIX}\${name}\`
}
`
}

async function writeFormatted(filePath: string, code: string): Promise<void> {
  const config = (await resolveConfig(filePath)) ?? {}
  const formatted = await format(code, { ...config, filepath: filePath })
  writeFileSync(filePath, formatted)
}

async function main(): Promise<void> {
  const defaults = readThemeDefaults()
  const sources = readIconSources()
  if (sources.length === 0) throw new Error('[task-icon-generator] no icons found in svg/')

  rmSync(iconsOutDir, { recursive: true, force: true })
  mkdirSync(iconsOutDir, { recursive: true })

  await Promise.all([
    ...sources.map((source) => writeFormatted(join(iconsOutDir, `${source.name}.ts`), renderIconModule(source, defaults))),
    writeFormatted(join(srcDir, 'index.ts'), renderIndexModule(sources)),
    writeFormatted(join(srcDir, 'task-icon-names.ts'), renderNamesModule(sources)),
  ])

  console.log(`[task-icon-generator] Generated ${sources.length} task icons from svg/`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
