// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/reorder-list. Import once, anywhere in the program:
//
//     import '@c2n/reorder-list/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { EventMapOf } from '@c2n/core/event-helper.js'
import type { ReorderList } from '@c2n/reorder-list'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes
/** The event an element fires under `name`, read from the map its `addEventListener` carries (its own or inherited). */
type EventOf<T extends EventTarget, Name extends string> = Name extends keyof EventMapOf<T> ? EventMapOf<T>[Name] : CustomEvent

declare module 'vue' {
  interface GlobalComponents {
    'c2-reorder-list': DefineComponent<
      C2Props<ReorderList> & {
        dragstartthreshold?: unknown
        autoscrolldisabled?: unknown
        'swipe-actions'?: unknown
        onSwipeAction?: (event: EventOf<ReorderList, 'swipe-action'>) => void
        onReorder?: (event: EventOf<ReorderList, 'reorder'>) => void
        onChange?: (event: EventOf<ReorderList, 'change'>) => void
        onReorderError?: (event: EventOf<ReorderList, 'reorder-error'>) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
