import { test, expect, props, watch, accessible } from '../../../../tests/component-fixture'

test('editing emits input/change, exposes a name, and reset restores the default', async ({ page, renderScenario }) => {
  await renderScenario('<c2-text-field aria-label="Message" value="Original" help="Describe the issue"></c2-text-field><button>Commit</button>')
  const host = page.locator('c2-text-field')
  const input = page.getByRole('textbox', { name: 'Message' })
  await watch(host, 'change')
  await input.fill('Edited')
  await page.getByRole('button', { name: 'Commit' }).click()
  await expect(host).toHaveJSProperty('value', 'Edited')
  await expect(host).toHaveAttribute('data-events', '[null]')
  await host.evaluate((el) => (el as HTMLElement & { reset(): void }).reset())
  await expect(input).toHaveValue('Original')
  await accessible(page)
})
test('readonly and disabled enforce native restrictions', async ({ page, renderScenario }) => {
  await renderScenario('<c2-text-field aria-label="Message" value="Keep" readonly></c2-text-field>')
  const host = page.locator('c2-text-field')
  const input = page.getByRole('textbox')
  await expect(input).not.toBeEditable()
  await input.press('x')
  await expect(input).toHaveValue('Keep')
  await props(host, { readOnly: false, disabled: true })
  await expect(input).toBeDisabled()
  await props(host, { disabled: false, value: 'New' })
  await expect(input).toHaveValue('New')
})
test('maximum length limits real typing and error feedback is visible', async ({ page, renderScenario }) => {
  await renderScenario('<c2-text-field aria-label="Message" maxlength="5" error error-text="Please revise"></c2-text-field>')
  const input = page.getByRole('textbox')
  await input.pressSequentially('1234567')
  await expect(input).toHaveValue('12345')
  await expect(input).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByText('Please revise', { exact: true })).toBeVisible()
  await expect(page.getByText('5 / 5', { exact: true })).toBeVisible()
})

test('clear emits the value change and returns focus to the input', async ({ page, renderScenario }) => {
  await renderScenario('<c2-text-field aria-label="Search" value="query" clearable></c2-text-field>')
  const host = page.locator('c2-text-field')
  await watch(host, 'clear')
  await page.getByRole('button', { name: 'Clear', exact: true }).click()
  await expect(page.getByRole('textbox')).toHaveValue('')
  await expect(page.getByRole('textbox')).toBeFocused()
  await expect(host).toHaveAttribute('data-events', '[null]')
})
