// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/task-icons. Import once, anywhere in the program:
//
//     import '@c2n/task-icons/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below. Structured converter-backed values
// also accept their serialized string form, so server JSX can emit the same JSON/CSV attribute used by HTML.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type {
  AlarmTaskIcon,
  AnnounceTaskIcon,
  AppleTaskIcon,
  AppointmentTaskIcon,
  BabyTaskIcon,
  BackupTaskIcon,
  BagTaskIcon,
  BakeTaskIcon,
  BalloonTaskIcon,
  BankTaskIcon,
  BasketballTaskIcon,
  BathTaskIcon,
  BeachTaskIcon,
  BedTaskIcon,
  BellTaskIcon,
  BikeTaskIcon,
  BillTaskIcon,
  BirthdayTaskIcon,
  BoatTaskIcon,
  BookTaskIcon,
  BookmarkTaskIcon,
  BooksTaskIcon,
  BottleTaskIcon,
  BranchTaskIcon,
  BreadTaskIcon,
  BriefcaseTaskIcon,
  BugTaskIcon,
  BurgerTaskIcon,
  BusTaskIcon,
  CalculatorTaskIcon,
  CalendarTaskIcon,
  CallTaskIcon,
  CameraTaskIcon,
  CampingTaskIcon,
  CarTaskIcon,
  CardTaskIcon,
  CartTaskIcon,
  ChargeTaskIcon,
  ChatTaskIcon,
  CheckCircleTaskIcon,
  ChecklistTaskIcon,
  CheeseTaskIcon,
  CleanTaskIcon,
  ClockTaskIcon,
  ClothesTaskIcon,
  CloudTaskIcon,
  CodeTaskIcon,
  CoffeeTaskIcon,
  CoinTaskIcon,
  CompassTaskIcon,
  ContactTaskIcon,
  ConversationTaskIcon,
  CookTaskIcon,
  CookieTaskIcon,
  CraftTaskIcon,
  DatabaseTaskIcon,
  DeliveryTaskIcon,
  DishesTaskIcon,
  DoctorTaskIcon,
  DocumentTaskIcon,
  DownloadTaskIcon,
  EggTaskIcon,
  EyeTaskIcon,
  FamilyTaskIcon,
  FireTaskIcon,
  FirstAidTaskIcon,
  FishTaskIcon,
  FlagTaskIcon,
  FlaskTaskIcon,
  FlightTaskIcon,
  FlowerTaskIcon,
  FolderTaskIcon,
  FootballTaskIcon,
  FrozenTaskIcon,
  FuelTaskIcon,
  GameTaskIcon,
  GiftTaskIcon,
  GlobeTaskIcon,
  GraduationTaskIcon,
  GrainTaskIcon,
  GrapesTaskIcon,
  GymTaskIcon,
  HeadphonesTaskIcon,
  HealthTaskIcon,
  HeartTaskIcon,
  HikeTaskIcon,
  HomeTaskIcon,
  HourglassTaskIcon,
  IceCreamTaskIcon,
  IdeaTaskIcon,
  InboxTaskIcon,
  InvestTaskIcon,
  JarTaskIcon,
  KeyTaskIcon,
  LanguageTaskIcon,
  LaptopTaskIcon,
  LaundryTaskIcon,
  LeafTaskIcon,
  LegumesTaskIcon,
  LessonTaskIcon,
  LikeTaskIcon,
  ListTaskIcon,
  LockTaskIcon,
  LuggageTaskIcon,
  MailTaskIcon,
  MapTaskIcon,
  MeatTaskIcon,
  MedalTaskIcon,
  MeditateTaskIcon,
  MeetingTaskIcon,
  MicrophoneTaskIcon,
  MilkTaskIcon,
  MoneyTaskIcon,
  MonitorTaskIcon,
  MoodTaskIcon,
  MoonTaskIcon,
  MovieTaskIcon,
  MusicTaskIcon,
  NewsTaskIcon,
  NoteTaskIcon,
  NotebookTaskIcon,
  OpenBookTaskIcon,
  PackageTaskIcon,
  PaintTaskIcon,
  PassportTaskIcon,
  PencilTaskIcon,
  PersonTaskIcon,
  PetTaskIcon,
  PillTaskIcon,
  PinTaskIcon,
  PizzaTaskIcon,
  PlantTaskIcon,
  PresentationTaskIcon,
  PrintTaskIcon,
  PuzzleTaskIcon,
  RainTaskIcon,
  RepairTaskIcon,
  RepeatTaskIcon,
  ReplyTaskIcon,
  ReportTaskIcon,
  RestaurantTaskIcon,
  RobotTaskIcon,
  RocketTaskIcon,
  RunTaskIcon,
  SaladTaskIcon,
  SavingsTaskIcon,
  SearchTaskIcon,
  SendTaskIcon,
  ServerTaskIcon,
  SettingsTaskIcon,
  ShareTaskIcon,
  ShieldTaskIcon,
  ShopTaskIcon,
  SignatureTaskIcon,
  SleepTaskIcon,
  SmartphoneTaskIcon,
  SofaTaskIcon,
  SparklesTaskIcon,
  StarTaskIcon,
  StopwatchTaskIcon,
  SunTaskIcon,
  SweepTaskIcon,
  SwimTaskIcon,
  TagTaskIcon,
  TargetTaskIcon,
  TaxTaskIcon,
  TeaTaskIcon,
  TeamTaskIcon,
  TennisTaskIcon,
  TerminalTaskIcon,
  TicketTaskIcon,
  ToiletriesTaskIcon,
  ToolboxTaskIcon,
  ToothTaskIcon,
  TrainTaskIcon,
  TrashTaskIcon,
  TreeTaskIcon,
  TrophyTaskIcon,
  TvTaskIcon,
  UrgentTaskIcon,
  VegetablesTaskIcon,
  VideoCallTaskIcon,
  VolunteerTaskIcon,
  WalkTaskIcon,
  WalletTaskIcon,
  WaterTaskIcon,
  WeddingTaskIcon,
  WifiTaskIcon,
  WineTaskIcon,
  WriteTaskIcon,
  ZapTaskIcon,
} from '@c2n/task-icons'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-task-icon-alarm': C2Props<AlarmTaskIcon>
      'c2-task-icon-announce': C2Props<AnnounceTaskIcon>
      'c2-task-icon-apple': C2Props<AppleTaskIcon>
      'c2-task-icon-appointment': C2Props<AppointmentTaskIcon>
      'c2-task-icon-baby': C2Props<BabyTaskIcon>
      'c2-task-icon-backup': C2Props<BackupTaskIcon>
      'c2-task-icon-bag': C2Props<BagTaskIcon>
      'c2-task-icon-bake': C2Props<BakeTaskIcon>
      'c2-task-icon-balloon': C2Props<BalloonTaskIcon>
      'c2-task-icon-bank': C2Props<BankTaskIcon>
      'c2-task-icon-basketball': C2Props<BasketballTaskIcon>
      'c2-task-icon-bath': C2Props<BathTaskIcon>
      'c2-task-icon-beach': C2Props<BeachTaskIcon>
      'c2-task-icon-bed': C2Props<BedTaskIcon>
      'c2-task-icon-bell': C2Props<BellTaskIcon>
      'c2-task-icon-bike': C2Props<BikeTaskIcon>
      'c2-task-icon-bill': C2Props<BillTaskIcon>
      'c2-task-icon-birthday': C2Props<BirthdayTaskIcon>
      'c2-task-icon-boat': C2Props<BoatTaskIcon>
      'c2-task-icon-book': C2Props<BookTaskIcon>
      'c2-task-icon-bookmark': C2Props<BookmarkTaskIcon>
      'c2-task-icon-books': C2Props<BooksTaskIcon>
      'c2-task-icon-bottle': C2Props<BottleTaskIcon>
      'c2-task-icon-branch': C2Props<BranchTaskIcon>
      'c2-task-icon-bread': C2Props<BreadTaskIcon>
      'c2-task-icon-briefcase': C2Props<BriefcaseTaskIcon>
      'c2-task-icon-bug': C2Props<BugTaskIcon>
      'c2-task-icon-burger': C2Props<BurgerTaskIcon>
      'c2-task-icon-bus': C2Props<BusTaskIcon>
      'c2-task-icon-calculator': C2Props<CalculatorTaskIcon>
      'c2-task-icon-calendar': C2Props<CalendarTaskIcon>
      'c2-task-icon-call': C2Props<CallTaskIcon>
      'c2-task-icon-camera': C2Props<CameraTaskIcon>
      'c2-task-icon-camping': C2Props<CampingTaskIcon>
      'c2-task-icon-car': C2Props<CarTaskIcon>
      'c2-task-icon-card': C2Props<CardTaskIcon>
      'c2-task-icon-cart': C2Props<CartTaskIcon>
      'c2-task-icon-charge': C2Props<ChargeTaskIcon>
      'c2-task-icon-chat': C2Props<ChatTaskIcon>
      'c2-task-icon-check-circle': C2Props<CheckCircleTaskIcon>
      'c2-task-icon-checklist': C2Props<ChecklistTaskIcon>
      'c2-task-icon-cheese': C2Props<CheeseTaskIcon>
      'c2-task-icon-clean': C2Props<CleanTaskIcon>
      'c2-task-icon-clock': C2Props<ClockTaskIcon>
      'c2-task-icon-clothes': C2Props<ClothesTaskIcon>
      'c2-task-icon-cloud': C2Props<CloudTaskIcon>
      'c2-task-icon-code': C2Props<CodeTaskIcon>
      'c2-task-icon-coffee': C2Props<CoffeeTaskIcon>
      'c2-task-icon-coin': C2Props<CoinTaskIcon>
      'c2-task-icon-compass': C2Props<CompassTaskIcon>
      'c2-task-icon-contact': C2Props<ContactTaskIcon>
      'c2-task-icon-conversation': C2Props<ConversationTaskIcon>
      'c2-task-icon-cook': C2Props<CookTaskIcon>
      'c2-task-icon-cookie': C2Props<CookieTaskIcon>
      'c2-task-icon-craft': C2Props<CraftTaskIcon>
      'c2-task-icon-database': C2Props<DatabaseTaskIcon>
      'c2-task-icon-delivery': C2Props<DeliveryTaskIcon>
      'c2-task-icon-dishes': C2Props<DishesTaskIcon>
      'c2-task-icon-doctor': C2Props<DoctorTaskIcon>
      'c2-task-icon-document': C2Props<DocumentTaskIcon>
      'c2-task-icon-download': C2Props<DownloadTaskIcon>
      'c2-task-icon-egg': C2Props<EggTaskIcon>
      'c2-task-icon-eye': C2Props<EyeTaskIcon>
      'c2-task-icon-family': C2Props<FamilyTaskIcon>
      'c2-task-icon-fire': C2Props<FireTaskIcon>
      'c2-task-icon-first-aid': C2Props<FirstAidTaskIcon>
      'c2-task-icon-fish': C2Props<FishTaskIcon>
      'c2-task-icon-flag': C2Props<FlagTaskIcon>
      'c2-task-icon-flask': C2Props<FlaskTaskIcon>
      'c2-task-icon-flight': C2Props<FlightTaskIcon>
      'c2-task-icon-flower': C2Props<FlowerTaskIcon>
      'c2-task-icon-folder': C2Props<FolderTaskIcon>
      'c2-task-icon-football': C2Props<FootballTaskIcon>
      'c2-task-icon-frozen': C2Props<FrozenTaskIcon>
      'c2-task-icon-fuel': C2Props<FuelTaskIcon>
      'c2-task-icon-game': C2Props<GameTaskIcon>
      'c2-task-icon-gift': C2Props<GiftTaskIcon>
      'c2-task-icon-globe': C2Props<GlobeTaskIcon>
      'c2-task-icon-graduation': C2Props<GraduationTaskIcon>
      'c2-task-icon-grain': C2Props<GrainTaskIcon>
      'c2-task-icon-grapes': C2Props<GrapesTaskIcon>
      'c2-task-icon-gym': C2Props<GymTaskIcon>
      'c2-task-icon-headphones': C2Props<HeadphonesTaskIcon>
      'c2-task-icon-health': C2Props<HealthTaskIcon>
      'c2-task-icon-heart': C2Props<HeartTaskIcon>
      'c2-task-icon-hike': C2Props<HikeTaskIcon>
      'c2-task-icon-home': C2Props<HomeTaskIcon>
      'c2-task-icon-hourglass': C2Props<HourglassTaskIcon>
      'c2-task-icon-ice-cream': C2Props<IceCreamTaskIcon>
      'c2-task-icon-idea': C2Props<IdeaTaskIcon>
      'c2-task-icon-inbox': C2Props<InboxTaskIcon>
      'c2-task-icon-invest': C2Props<InvestTaskIcon>
      'c2-task-icon-jar': C2Props<JarTaskIcon>
      'c2-task-icon-key': C2Props<KeyTaskIcon>
      'c2-task-icon-language': C2Props<LanguageTaskIcon>
      'c2-task-icon-laptop': C2Props<LaptopTaskIcon>
      'c2-task-icon-laundry': C2Props<LaundryTaskIcon>
      'c2-task-icon-leaf': C2Props<LeafTaskIcon>
      'c2-task-icon-legumes': C2Props<LegumesTaskIcon>
      'c2-task-icon-lesson': C2Props<LessonTaskIcon>
      'c2-task-icon-like': C2Props<LikeTaskIcon>
      'c2-task-icon-list': C2Props<ListTaskIcon>
      'c2-task-icon-lock': C2Props<LockTaskIcon>
      'c2-task-icon-luggage': C2Props<LuggageTaskIcon>
      'c2-task-icon-mail': C2Props<MailTaskIcon>
      'c2-task-icon-map': C2Props<MapTaskIcon>
      'c2-task-icon-meat': C2Props<MeatTaskIcon>
      'c2-task-icon-medal': C2Props<MedalTaskIcon>
      'c2-task-icon-meditate': C2Props<MeditateTaskIcon>
      'c2-task-icon-meeting': C2Props<MeetingTaskIcon>
      'c2-task-icon-microphone': C2Props<MicrophoneTaskIcon>
      'c2-task-icon-milk': C2Props<MilkTaskIcon>
      'c2-task-icon-money': C2Props<MoneyTaskIcon>
      'c2-task-icon-monitor': C2Props<MonitorTaskIcon>
      'c2-task-icon-mood': C2Props<MoodTaskIcon>
      'c2-task-icon-moon': C2Props<MoonTaskIcon>
      'c2-task-icon-movie': C2Props<MovieTaskIcon>
      'c2-task-icon-music': C2Props<MusicTaskIcon>
      'c2-task-icon-news': C2Props<NewsTaskIcon>
      'c2-task-icon-note': C2Props<NoteTaskIcon>
      'c2-task-icon-notebook': C2Props<NotebookTaskIcon>
      'c2-task-icon-open-book': C2Props<OpenBookTaskIcon>
      'c2-task-icon-package': C2Props<PackageTaskIcon>
      'c2-task-icon-paint': C2Props<PaintTaskIcon>
      'c2-task-icon-passport': C2Props<PassportTaskIcon>
      'c2-task-icon-pencil': C2Props<PencilTaskIcon>
      'c2-task-icon-person': C2Props<PersonTaskIcon>
      'c2-task-icon-pet': C2Props<PetTaskIcon>
      'c2-task-icon-pill': C2Props<PillTaskIcon>
      'c2-task-icon-pin': C2Props<PinTaskIcon>
      'c2-task-icon-pizza': C2Props<PizzaTaskIcon>
      'c2-task-icon-plant': C2Props<PlantTaskIcon>
      'c2-task-icon-presentation': C2Props<PresentationTaskIcon>
      'c2-task-icon-print': C2Props<PrintTaskIcon>
      'c2-task-icon-puzzle': C2Props<PuzzleTaskIcon>
      'c2-task-icon-rain': C2Props<RainTaskIcon>
      'c2-task-icon-repair': C2Props<RepairTaskIcon>
      'c2-task-icon-repeat': C2Props<RepeatTaskIcon>
      'c2-task-icon-reply': C2Props<ReplyTaskIcon>
      'c2-task-icon-report': C2Props<ReportTaskIcon>
      'c2-task-icon-restaurant': C2Props<RestaurantTaskIcon>
      'c2-task-icon-robot': C2Props<RobotTaskIcon>
      'c2-task-icon-rocket': C2Props<RocketTaskIcon>
      'c2-task-icon-run': C2Props<RunTaskIcon>
      'c2-task-icon-salad': C2Props<SaladTaskIcon>
      'c2-task-icon-savings': C2Props<SavingsTaskIcon>
      'c2-task-icon-search': C2Props<SearchTaskIcon>
      'c2-task-icon-send': C2Props<SendTaskIcon>
      'c2-task-icon-server': C2Props<ServerTaskIcon>
      'c2-task-icon-settings': C2Props<SettingsTaskIcon>
      'c2-task-icon-share': C2Props<ShareTaskIcon>
      'c2-task-icon-shield': C2Props<ShieldTaskIcon>
      'c2-task-icon-shop': C2Props<ShopTaskIcon>
      'c2-task-icon-signature': C2Props<SignatureTaskIcon>
      'c2-task-icon-sleep': C2Props<SleepTaskIcon>
      'c2-task-icon-smartphone': C2Props<SmartphoneTaskIcon>
      'c2-task-icon-sofa': C2Props<SofaTaskIcon>
      'c2-task-icon-sparkles': C2Props<SparklesTaskIcon>
      'c2-task-icon-star': C2Props<StarTaskIcon>
      'c2-task-icon-stopwatch': C2Props<StopwatchTaskIcon>
      'c2-task-icon-sun': C2Props<SunTaskIcon>
      'c2-task-icon-sweep': C2Props<SweepTaskIcon>
      'c2-task-icon-swim': C2Props<SwimTaskIcon>
      'c2-task-icon-tag': C2Props<TagTaskIcon>
      'c2-task-icon-target': C2Props<TargetTaskIcon>
      'c2-task-icon-tax': C2Props<TaxTaskIcon>
      'c2-task-icon-tea': C2Props<TeaTaskIcon>
      'c2-task-icon-team': C2Props<TeamTaskIcon>
      'c2-task-icon-tennis': C2Props<TennisTaskIcon>
      'c2-task-icon-terminal': C2Props<TerminalTaskIcon>
      'c2-task-icon-ticket': C2Props<TicketTaskIcon>
      'c2-task-icon-toiletries': C2Props<ToiletriesTaskIcon>
      'c2-task-icon-toolbox': C2Props<ToolboxTaskIcon>
      'c2-task-icon-tooth': C2Props<ToothTaskIcon>
      'c2-task-icon-train': C2Props<TrainTaskIcon>
      'c2-task-icon-trash': C2Props<TrashTaskIcon>
      'c2-task-icon-tree': C2Props<TreeTaskIcon>
      'c2-task-icon-trophy': C2Props<TrophyTaskIcon>
      'c2-task-icon-tv': C2Props<TvTaskIcon>
      'c2-task-icon-urgent': C2Props<UrgentTaskIcon>
      'c2-task-icon-vegetables': C2Props<VegetablesTaskIcon>
      'c2-task-icon-video-call': C2Props<VideoCallTaskIcon>
      'c2-task-icon-volunteer': C2Props<VolunteerTaskIcon>
      'c2-task-icon-walk': C2Props<WalkTaskIcon>
      'c2-task-icon-wallet': C2Props<WalletTaskIcon>
      'c2-task-icon-water': C2Props<WaterTaskIcon>
      'c2-task-icon-wedding': C2Props<WeddingTaskIcon>
      'c2-task-icon-wifi': C2Props<WifiTaskIcon>
      'c2-task-icon-wine': C2Props<WineTaskIcon>
      'c2-task-icon-write': C2Props<WriteTaskIcon>
      'c2-task-icon-zap': C2Props<ZapTaskIcon>
    }
  }
}

export {}
