// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/command. Import once, anywhere in the program:
//
//     import '@c2n/command/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below. Structured converter-backed values
// also accept their serialized string form, so server JSX can emit the same JSON/CSV attribute used by HTML.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { Command } from '@c2n/command'
import type { CommandGroup } from '@c2n/command/command-group.js'
import type { CommandItem } from '@c2n/command/command-item.js'
import type { CommandSeparator } from '@c2n/command/command-separator.js'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>
/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */
type Attribute = string | number | boolean

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-command': C2Props<Command> & {
        'manual-filter'?: Attribute
      }
      'c2-command-group': C2Props<CommandGroup>
      'c2-command-item': C2Props<CommandItem>
      'c2-command-separator': C2Props<CommandSeparator>
    }
  }
}

export {}
