/**
 * Icon generator for `@c2n/feather-icons`.
 *
 * Reads every SVG shipped in the `feather-icons` npm package (`dist/icons/*.svg`), strips the
 * shared `<svg>` wrapper (which the `FeatherIcon` base class owns) and emits one Lit custom element
 * per icon into `src/icons/<name>.ts`, plus the `src/index.ts` barrel and `src/icon-names.ts`.
 *
 * Output is formatted with the repo's prettier config so the committed files pass `format:check`.
 *
 * Run with `npm run generate -w packages/icons/feather-icons` (Node >= 22.18 / 24: native type stripping,
 * so keep this file to erasable TypeScript syntax only).
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

const TAG_PREFIX = 'c2-feather-'
const CLASS_PREFIX = 'Feather'
const CLASS_SUFFIX = 'Icon'

// Every Feather icon uses this exact wrapper; the base class re-creates it, so only the inner markup is kept.
const STRICT_WRAPPER =
  /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-[a-z0-9-]+">([\s\S]*)<\/svg>\s*$/
const LOOSE_WRAPPER = /^<svg\b[^>]*>([\s\S]*)<\/svg>\s*$/

const require = createRequire(import.meta.url)
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const srcDir = join(packageRoot, 'src')
const iconsOutDir = join(srcDir, 'icons')

const featherPackageJsonPath = require.resolve('feather-icons/package.json')
const featherVersion: string = JSON.parse(readFileSync(featherPackageJsonPath, 'utf8')).version
const featherIconsDir = join(dirname(featherPackageJsonPath), 'dist', 'icons')

const header = `// GENERATED by scripts/icon-generator from feather-icons@${featherVersion}. Do not edit by hand.`

interface IconSource {
  /** Feather icon name, e.g. `arrow-right`. */
  name: string
  /** Inner SVG markup without the `<svg>` wrapper. */
  body: string
}

function toPascalCase(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')
}

function toClassName(name: string): string {
  const pascal = toPascalCase(name)
  // Identifiers cannot start with a digit; Feather has none today, but stay safe.
  const safe = /^[0-9]/.test(pascal) ? `${CLASS_SUFFIX}${pascal}` : pascal
  return `${CLASS_PREFIX}${safe}${CLASS_SUFFIX}`
}

/** Escape the SVG body so it can be embedded in a JS template literal. */
function toTemplateLiteralBody(markup: string): string {
  return markup.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function readIconSources(): IconSource[] {
  const files = readdirSync(featherIconsDir)
    .filter((file) => file.endsWith('.svg'))
    .sort()
  return files.map((file) => {
    const name = basename(file, '.svg')
    const svg = readFileSync(join(featherIconsDir, file), 'utf8').trim()
    let match = STRICT_WRAPPER.exec(svg)
    if (!match) {
      console.warn(`[icon-generator] ${file}: unexpected <svg> wrapper, keeping inner markup as-is`)
      match = LOOSE_WRAPPER.exec(svg)
    }
    if (!match) throw new Error(`[icon-generator] ${file}: could not parse SVG`)
    return { name, body: match[1].trim() }
  })
}

function renderIconModule({ name, body }: IconSource): string {
  const tag = `${TAG_PREFIX}${name}`
  const className = toClassName(name)
  return `${header}
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather \`${name}\` icon.
 *
 * @tag ${tag}
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('${tag}')
export class ${className} extends FeatherIcon {
  protected override renderIcon() {
    return svg\`${toTemplateLiteralBody(body)}\`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    '${tag}': ${className}
  }
}
`
}

function renderIndexModule(icons: IconSource[]): string {
  const exports = icons.map(({ name }) => `export * from './icons/${name}'`).join('\n')
  return `${header}
// Importing this barrel registers every Feather icon element. Prefer importing
// individual icons (\`@c2n/feather-icons/icons/<name>.js\`) in production bundles.
export * from './feather-icon'
export * from './icon-names'
${exports}
`
}

function renderIconNamesModule(icons: IconSource[]): string {
  const names = icons.map(({ name }) => `'${name}'`).join(', ')
  return `${header}
export const featherIconTagPrefix = '${TAG_PREFIX}'

export const featherIconNames = [${names}] as const

export type FeatherIconName = (typeof featherIconNames)[number]

/** Custom element tag name for a Feather icon, e.g. \`arrow-right\` -> \`${TAG_PREFIX}arrow-right\`. */
export function featherIconTag(name: FeatherIconName): \`${TAG_PREFIX}\${FeatherIconName}\` {
  return \`${TAG_PREFIX}\${name}\`
}
`
}

async function writeFormatted(filePath: string, code: string): Promise<void> {
  const config = (await resolveConfig(filePath)) ?? {}
  const formatted = await format(code, { ...config, filepath: filePath })
  writeFileSync(filePath, formatted)
}

async function main(): Promise<void> {
  const icons = readIconSources()
  if (icons.length === 0) throw new Error(`[icon-generator] no SVG files found in ${featherIconsDir}`)

  rmSync(iconsOutDir, { recursive: true, force: true })
  mkdirSync(iconsOutDir, { recursive: true })

  await Promise.all([
    ...icons.map((icon) => writeFormatted(join(iconsOutDir, `${icon.name}.ts`), renderIconModule(icon))),
    writeFormatted(join(srcDir, 'index.ts'), renderIndexModule(icons)),
    writeFormatted(join(srcDir, 'icon-names.ts'), renderIconNamesModule(icons)),
  ])

  console.log(`[icon-generator] Generated ${icons.length} icons from feather-icons@${featherVersion} into ${iconsOutDir}`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
