// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `arrow-left-circle` icon.
 *
 * @tag c2-feather-arrow-left-circle
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-arrow-left-circle')
export class FeatherArrowLeftCircleIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<circle cx="12" cy="12" r="10"></circle><polyline points="12 8 8 12 12 16"></polyline><line x1="16" y1="12" x2="8" y2="12"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-arrow-left-circle': FeatherArrowLeftCircleIcon
  }
}
