// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `arrow-up-left` icon.
 *
 * @tag c2-feather-arrow-up-left
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-arrow-up-left')
export class FeatherArrowUpLeftIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<line x1="17" y1="17" x2="7" y2="7"></line><polyline points="7 17 7 7 17 7"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-arrow-up-left': FeatherArrowUpLeftIcon
  }
}
