// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `arrow-down-right` icon.
 *
 * @tag c2-feather-arrow-down-right
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-arrow-down-right')
export class FeatherArrowDownRightIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<line x1="7" y1="7" x2="17" y2="17"></line><polyline points="17 7 17 17 7 17"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-arrow-down-right': FeatherArrowDownRightIcon
  }
}
