// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `arrow-right` icon.
 *
 * @tag c2-feather-arrow-right
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-arrow-right')
export class FeatherArrowRightIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-arrow-right': FeatherArrowRightIcon
  }
}
