// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `check-circle` icon.
 *
 * @tag c2-feather-check-circle
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-check-circle')
export class FeatherCheckCircleIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-check-circle': FeatherCheckCircleIcon
  }
}
