// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `chevron-right` icon.
 *
 * @tag c2-feather-chevron-right
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-chevron-right')
export class FeatherChevronRightIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="9 18 15 12 9 6"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-chevron-right': FeatherChevronRightIcon
  }
}
