// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `chevron-down` icon.
 *
 * @tag c2-feather-chevron-down
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-chevron-down')
export class FeatherChevronDownIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="6 9 12 15 18 9"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-chevron-down': FeatherChevronDownIcon
  }
}
