// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `chevrons-up` icon.
 *
 * @tag c2-feather-chevrons-up
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-chevrons-up')
export class FeatherChevronsUpIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="17 11 12 6 7 11"></polyline><polyline points="17 18 12 13 7 18"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-chevrons-up': FeatherChevronsUpIcon
  }
}
