// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `cloud-off` icon.
 *
 * @tag c2-feather-cloud-off
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-cloud-off')
export class FeatherCloudOffIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M22.61 16.95A5 5 0 0 0 18 10h-1.26a8 8 0 0 0-7.05-6M5 5a8 8 0 0 0 4 15h9a5 5 0 0 0 1.7-.3"></path><line x1="1" y1="1" x2="23" y2="23"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-cloud-off': FeatherCloudOffIcon
  }
}
