// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `corner-right-down` icon.
 *
 * @tag c2-feather-corner-right-down
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-corner-right-down')
export class FeatherCornerRightDownIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="10 15 15 20 20 15"></polyline><path d="M4 4h7a4 4 0 0 1 4 4v12"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-corner-right-down': FeatherCornerRightDownIcon
  }
}
