// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `corner-down-right` icon.
 *
 * @tag c2-feather-corner-down-right
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-corner-down-right')
export class FeatherCornerDownRightIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="15 10 20 15 15 20"></polyline><path d="M4 4v7a4 4 0 0 0 4 4h12"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-corner-down-right': FeatherCornerDownRightIcon
  }
}
