// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `corner-down-left` icon.
 *
 * @tag c2-feather-corner-down-left
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-corner-down-left')
export class FeatherCornerDownLeftIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="9 10 4 15 9 20"></polyline><path d="M20 4v7a4 4 0 0 1-4 4H4"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-corner-down-left': FeatherCornerDownLeftIcon
  }
}
