// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `corner-up-right` icon.
 *
 * @tag c2-feather-corner-up-right
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-corner-up-right')
export class FeatherCornerUpRightIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="15 14 20 9 15 4"></polyline><path d="M4 20v-7a4 4 0 0 1 4-4h12"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-corner-up-right': FeatherCornerUpRightIcon
  }
}
