// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `dribbble` icon.
 *
 * @tag c2-feather-dribbble
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-dribbble')
export class FeatherDribbbleIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<circle cx="12" cy="12" r="10"></circle><path d="M8.56 2.75c4.37 6.03 6.02 9.42 8.03 17.72m2.54-15.38c-3.72 4.35-8.94 5.66-16.88 5.85m19.5 1.9c-3.5-.93-6.63-.82-8.94 0-2.58.92-5.01 2.86-7.44 6.32"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-dribbble': FeatherDribbbleIcon
  }
}
