// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `facebook` icon.
 *
 * @tag c2-feather-facebook
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-facebook')
export class FeatherFacebookIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-facebook': FeatherFacebookIcon
  }
}
