// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `framer` icon.
 *
 * @tag c2-feather-framer
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-framer')
export class FeatherFramerIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M5 16V9h14V2H5l14 14h-7m-7 0l7 7v-7m-7 0h7"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-framer': FeatherFramerIcon
  }
}
