// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `git-merge` icon.
 *
 * @tag c2-feather-git-merge
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-git-merge')
export class FeatherGitMergeIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<circle cx="18" cy="18" r="3"></circle><circle cx="6" cy="6" r="3"></circle><path d="M6 21V9a9 9 0 0 0 9 9"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-git-merge': FeatherGitMergeIcon
  }
}
