// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `lock` icon.
 *
 * @tag c2-feather-lock
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-lock')
export class FeatherLockIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-lock': FeatherLockIcon
  }
}
