// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `map-pin` icon.
 *
 * @tag c2-feather-map-pin
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-map-pin')
export class FeatherMapPinIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-map-pin': FeatherMapPinIcon
  }
}
