// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `minus-square` icon.
 *
 * @tag c2-feather-minus-square
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-minus-square')
export class FeatherMinusSquareIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="8" y1="12" x2="16" y2="12"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-minus-square': FeatherMinusSquareIcon
  }
}
