// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `monitor` icon.
 *
 * @tag c2-feather-monitor
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-monitor')
export class FeatherMonitorIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-monitor': FeatherMonitorIcon
  }
}
