// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `pause` icon.
 *
 * @tag c2-feather-pause
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-pause')
export class FeatherPauseIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-pause': FeatherPauseIcon
  }
}
