// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `pie-chart` icon.
 *
 * @tag c2-feather-pie-chart
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-pie-chart')
export class FeatherPieChartIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path><path d="M22 12A10 10 0 0 0 12 2v10z"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-pie-chart': FeatherPieChartIcon
  }
}
