// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `play` icon.
 *
 * @tag c2-feather-play
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-play')
export class FeatherPlayIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polygon points="5 3 19 12 5 21 5 3"></polygon>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-play': FeatherPlayIcon
  }
}
