// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `plus` icon.
 *
 * @tag c2-feather-plus
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-plus')
export class FeatherPlusIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-plus': FeatherPlusIcon
  }
}
