// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `refresh-cw` icon.
 *
 * @tag c2-feather-refresh-cw
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-refresh-cw')
export class FeatherRefreshCwIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="23 4 23 10 17 10"></polyline><polyline points="1 20 1 14 7 14"></polyline><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-refresh-cw': FeatherRefreshCwIcon
  }
}
