// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `rotate-cw` icon.
 *
 * @tag c2-feather-rotate-cw
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-rotate-cw')
export class FeatherRotateCwIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="23 4 23 10 17 10"></polyline><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-rotate-cw': FeatherRotateCwIcon
  }
}
