// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `shopping-bag` icon.
 *
 * @tag c2-feather-shopping-bag
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-shopping-bag')
export class FeatherShoppingBagIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-shopping-bag': FeatherShoppingBagIcon
  }
}
