// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `skip-back` icon.
 *
 * @tag c2-feather-skip-back
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-skip-back')
export class FeatherSkipBackIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polygon points="19 20 9 12 19 4 19 20"></polygon><line x1="5" y1="19" x2="5" y2="5"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-skip-back': FeatherSkipBackIcon
  }
}
