// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `speaker` icon.
 *
 * @tag c2-feather-speaker
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-speaker')
export class FeatherSpeakerIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<rect x="4" y="2" width="16" height="20" rx="2" ry="2"></rect><circle cx="12" cy="14" r="4"></circle><line x1="12" y1="6" x2="12.01" y2="6"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-speaker': FeatherSpeakerIcon
  }
}
