// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `tag` icon.
 *
 * @tag c2-feather-tag
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-tag')
export class FeatherTagIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path><line x1="7" y1="7" x2="7.01" y2="7"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-tag': FeatherTagIcon
  }
}
