// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `terminal` icon.
 *
 * @tag c2-feather-terminal
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-terminal')
export class FeatherTerminalIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="4 17 10 11 4 5"></polyline><line x1="12" y1="19" x2="20" y2="19"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-terminal': FeatherTerminalIcon
  }
}
