// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `upload-cloud` icon.
 *
 * @tag c2-feather-upload-cloud
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-upload-cloud')
export class FeatherUploadCloudIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<polyline points="16 16 12 12 8 16"></polyline><line x1="12" y1="12" x2="12" y2="21"></line><path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"></path><polyline points="16 16 12 12 8 16"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-upload-cloud': FeatherUploadCloudIcon
  }
}
