// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `user-check` icon.
 *
 * @tag c2-feather-user-check
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-user-check')
export class FeatherUserCheckIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><polyline points="17 11 19 13 23 9"></polyline>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-user-check': FeatherUserCheckIcon
  }
}
