// GENERATED by scripts/icon-generator from feather-icons@4.29.2. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from 'lit/decorators.js'
import { FeatherIcon } from '../feather-icon'

/**
 * Feather `voicemail` icon.
 *
 * @tag c2-feather-voicemail
 *
 * @cssproperty {pixel} [--c2-feather-icon--size=24px]
 * @cssproperty {color} [--c2-feather-icon--color=currentColor]
 * @cssproperty {number} [--c2-feather-icon--stroke-width=2]
 */
@customElement('c2-feather-voicemail')
export class FeatherVoicemailIcon extends FeatherIcon {
  protected override renderIcon() {
    return svg`<circle cx="5.5" cy="11.5" r="4.5"></circle><circle cx="18.5" cy="11.5" r="4.5"></circle><line x1="5.5" y1="16" x2="18.5" y2="16"></line>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-feather-voicemail': FeatherVoicemailIcon
  }
}
