import { test, expect, props, watch, accessible, pointerClick } from '../../../../tests/component-fixture'

test('keyboard steps publish input and change, and Home/End reach bounds', async ({ page, renderScenario }) => {
  await renderScenario('<c2-slider aria-label="Volume" min="10" max="30" step="5" value="15" show-value ticks></c2-slider>')
  const host = page.locator('c2-slider')
  const slider = page.getByRole('slider', { name: 'Volume' })
  await watch(host, 'change')
  await slider.press('ArrowRight')
  await expect(host).toHaveJSProperty('value', 20)
  await expect(slider).toHaveAttribute('aria-valuetext', '20')
  await expect(host).toHaveAttribute('data-events', '[null]')
  await slider.press('End')
  await expect(slider).toHaveValue('30')
  await slider.press('Home')
  await expect(slider).toHaveValue('10')
  await accessible(page)
})
test('disabled prevents keyboard changes and vertical semantics are exposed', async ({ page, renderScenario }) => {
  await renderScenario('<c2-slider aria-label="Volume" value="40" orientation="vertical"></c2-slider>')
  const slider = page.getByRole('slider')
  await expect(slider).toHaveAttribute('aria-orientation', 'vertical')
  await props(page.locator('c2-slider'), { disabled: true })
  await expect(slider).toBeDisabled()
  await pointerClick(slider)
  await expect(slider).toHaveValue('40')
})
test('out-of-range values keep the display and accessibility value in sync', async ({ page, renderScenario }) => {
  await renderScenario('<c2-slider aria-label="Volume" min="10" max="30" value="100" show-value></c2-slider>')
  const slider = page.getByRole('slider')
  await expect(slider).toHaveValue('30')
  await expect(slider).toHaveAttribute('aria-valuetext', '30')
  await expect(page.locator('c2-slider [part="value"]')).toHaveText('30')
})
test('participates in forms, restores its default and exposes custom validity', async ({ page, renderScenario }) => {
  await renderScenario('<form><c2-slider name="volume" aria-label="Volume" min="0" max="100" step="5" value="25"></c2-slider></form>')
  const host = page.locator('c2-slider')
  const slider = page.getByRole('slider')
  const form = page.locator('form')
  await slider.press('ArrowRight')
  await expect.poll(() => form.evaluate((element) => new FormData(element as HTMLFormElement).get('volume'))).toBe('30')
  await form.evaluate((element) => (element as HTMLFormElement).reset())
  await expect(slider).toHaveValue('25')
  await host.evaluate((element) => (element as HTMLElement & { setCustomValidity(message: string): void }).setCustomValidity('Choose another volume'))
  await expect.poll(() => host.evaluate((element) => (element as HTMLElement & { checkValidity(): boolean }).checkValidity())).toBe(false)
  await host.evaluate((element) => (element as HTMLElement & { setCustomValidity(message: string): void }).setCustomValidity(''))
  await expect.poll(() => host.evaluate((element) => (element as HTMLElement & { checkValidity(): boolean }).checkValidity())).toBe(true)
})
test('fieldset disabled state removes the slider from FormData', async ({ page, renderScenario }) => {
  await renderScenario('<form><fieldset disabled><c2-slider name="volume" aria-label="Volume" value="40"></c2-slider></fieldset></form>')
  await expect(page.getByRole('slider')).toBeDisabled()
  await expect.poll(() => page.locator('form').evaluate((element) => new FormData(element as HTMLFormElement).has('volume'))).toBe(false)
})
