// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/theme-select. Import once, anywhere in the program:
//
//     import '@c2n/theme-select/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { EventMapOf } from '@c2n/core/event-helper.js'
import type { ThemeSelect } from '@c2n/theme-select'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes
/** The event an element fires under `name`, read from the map its `addEventListener` carries (its own or inherited). */
type EventOf<T extends EventTarget, Name extends string> = Name extends keyof EventMapOf<T> ? EventMapOf<T>[Name] : CustomEvent

declare module 'vue' {
  interface GlobalComponents {
    'c2-theme-select': DefineComponent<
      C2Props<ThemeSelect> & {
        'show-label'?: unknown
        'theme-attribute'?: unknown
        'storage-key'?: unknown
        'open-delay'?: unknown
        'close-delay'?: unknown
        'aria-label'?: unknown
        onThemeChange?: (event: EventOf<ThemeSelect, 'theme-change'>) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
