// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/json-viewer. Import once, anywhere in the program:
//
//     import '@c2n/json-viewer/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { EventMapOf } from '@c2n/core/event-helper.js'
import type { JsonViewer } from '@c2n/json-viewer'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes
/** The event an element fires under `name`, read from the map its `addEventListener` carries (its own or inherited). */
type EventOf<T extends EventTarget, Name extends string> = Name extends keyof EventMapOf<T> ? EventMapOf<T>[Name] : CustomEvent

declare module 'vue' {
  interface GlobalComponents {
    'c2-json-viewer': DefineComponent<
      C2Props<JsonViewer> & {
        'expand-depth'?: unknown
        'sort-keys'?: unknown
        'path-format'?: unknown
        'page-size'?: unknown
        onExpansionChange?: (event: EventOf<JsonViewer, 'expansion-change'>) => void
        onCopyError?: (event: EventOf<JsonViewer, 'copy-error'>) => void
        onCopied?: (event: EventOf<JsonViewer, 'copied'>) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
