// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Party task icon. For tasks about: party, celebrate, invite, event, balloon, fun.
 *
 * @tag c2-task-icon-balloon
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-balloon')
export class BalloonTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M12 2.5c3.3 0 6 2.8 6 6.3 0 4-3.2 7.2-6 7.2s-6-3.2-6-7.2c0-3.5 2.7-6.3 6-6.3z"/><path d="M11 16l1 1.5 1-1.5M12 17.5c0 1.5-1.5 2-1.5 3s1 1.5 1.5 1.5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-balloon': BalloonTaskIcon
  }
}
