// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Bath task icon. For tasks about: bath, shower, self-care, bathroom, spa.
 *
 * @tag c2-task-icon-bath
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-bath')
export class BathTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M3 12h18v2.5a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5z"/><path d="M6 12V5.5a2 2 0 0 1 2-2c1 0 1.8.6 2 1.5M8 19.5l-1 2M16 19.5l1 2"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-bath': BathTaskIcon
  }
}
