// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Bed task icon. For tasks about: bed, make, bed, bedroom, hotel, sheets, guest.
 *
 * @tag c2-task-icon-bed
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-bed')
export class BedTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="fill" d="M10.5 10.5h8a3 3 0 0 1 3 3v3h-11z"/><path d="M2.5 5v15M2.5 16.5h19V20M21.5 16.5v-3a3 3 0 0 0-3-3h-8v6"/><circle class="tone" cx="6.5" cy="13" r="2"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-bed': BedTaskIcon
  }
}
