// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Bug task icon. For tasks about: bug, fix, issue, debug, error, crash, qa, test.
 *
 * @tag c2-task-icon-bug
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-bug')
export class BugTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<rect class="tone" x="7" y="8" width="10" height="12" rx="5"/><path d="M9.5 8.5V7a2.5 2.5 0 0 1 5 0v1.5M12 12v8M3.5 13H7M17 13h3.5M4.5 8.5l3 1.5M19.5 8.5l-3 1.5M4.5 19l3-2M19.5 19l-3-2"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-bug': BugTaskIcon
  }
}
