// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Bus task icon. For tasks about: bus, school, run, commute, transit, shuttle.
 *
 * @tag c2-task-icon-bus
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-bus')
export class BusTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<rect class="tone" x="4" y="3" width="16" height="15" rx="2.5"/><path d="M4 12h16M4 7h16M7 18v2.5M17 18v2.5"/><circle class="solid" cx="7.5" cy="15" r="1"/><circle class="solid" cx="16.5" cy="15" r="1"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-bus': BusTaskIcon
  }
}
