// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Math task icon. For tasks about: math, calculate, numbers, accounting, budget.
 *
 * @tag c2-task-icon-calculator
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-calculator')
export class CalculatorTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<rect class="tone" x="4.5" y="2.5" width="15" height="19" rx="2"/><rect x="7.5" y="5.5" width="9" height="4" rx="1"/><circle class="solid" cx="8.5" cy="13.5" r="1"/><circle class="solid" cx="12" cy="13.5" r="1"/><circle class="solid" cx="15.5" cy="13.5" r="1"/><circle class="solid" cx="8.5" cy="17.5" r="1"/><circle class="solid" cx="12" cy="17.5" r="1"/><circle class="solid" cx="15.5" cy="17.5" r="1"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-calculator': CalculatorTaskIcon
  }
}
