// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Car task icon. For tasks about: car, drive, service, mot, garage, road, trip, parking.
 *
 * @tag c2-task-icon-car
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-car')
export class CarTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M3 16.5V13l2-5a2 2 0 0 1 1.9-1.3h10.2A2 2 0 0 1 19 8l2 5v3.5a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M3.5 12.5h17M5.5 17.5v2M18.5 17.5v2"/><circle class="solid" cx="7" cy="14.8" r="1"/><circle class="solid" cx="17" cy="14.8" r="1"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-car': CarTaskIcon
  }
}
