// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Cheese task icon. For tasks about: cheese, dairy, fromage, deli.
 *
 * @tag c2-task-icon-cheese
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-cheese')
export class CheeseTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M3 16.5L14 6l7 4.5v6z"/><path d="M3 16.5V19a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-8.5"/><circle cx="10" cy="14" r="1.2"/><circle cx="15.5" cy="11.5" r="1"/><circle cx="16.5" cy="17.5" r="1.1"/><circle cx="7.5" cy="18" r=".9"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-cheese': CheeseTaskIcon
  }
}
