// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Clean task icon. For tasks about: clean, spray, wipe, tidy, dust, bathroom, kitchen.
 *
 * @tag c2-task-icon-clean
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-clean')
export class CleanTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M8 9h6l1.5 3v8a1 1 0 0 1-1 1h-7a1 1 0 0 1-1-1v-8z"/><path d="M9 9V6h4v3M9 6H7.5V4H14l1.5 2H13"/><circle class="solid" cx="19" cy="4" r="0.9"/><circle class="solid" cx="20.5" cy="7" r="0.9"/><circle class="solid" cx="18" cy="7.5" r="0.9"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-clean': CleanTaskIcon
  }
}
