// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Snacks task icon. For tasks about: snacks, cookie, biscuit, sweets, chocolate, chips, candy.
 *
 * @tag c2-task-icon-cookie
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-cookie')
export class CookieTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M20.5 12A8.5 8.5 0 1 1 12 3.5a3 3 0 0 0 4 3.5 3 3 0 0 0 4.5 5z"/><circle class="solid" cx="9" cy="9.5" r="1.1"/><circle class="solid" cx="8" cy="14.5" r="1.1"/><circle class="solid" cx="13" cy="16.5" r="1.1"/><circle class="solid" cx="13.5" cy="11.5" r="1.1"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-cookie': CookieTaskIcon
  }
}
