// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Eyes task icon. For tasks about: eyes, vision, optician, glasses, watch, review, look.
 *
 * @tag c2-task-icon-eye
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-eye')
export class EyeTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-eye': EyeTaskIcon
  }
}
