// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Football task icon. For tasks about: football, soccer, ball, match, game, sport.
 *
 * @tag c2-task-icon-football
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-football')
export class FootballTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<circle class="tone" cx="12" cy="12" r="9"/><path d="M12 7.5l3.3 2.4-1.3 3.9h-4l-1.3-3.9zM12 3v4.5M15.3 9.9l4.6-1.6M14 13.8l2.9 4M10 13.8l-2.9 4M8.7 9.9L4.1 8.3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-football': FootballTaskIcon
  }
}
