// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Game task icon. For tasks about: game, play, video, games, console, fun, gaming.
 *
 * @tag c2-task-icon-game
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-game')
export class GameTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M7 7h10a4.5 4.5 0 0 1 4.4 3.6l1 5.2a2.7 2.7 0 0 1-4.8 2.1L15.5 16h-7l-2.1 1.9a2.7 2.7 0 0 1-4.8-2.1l1-5.2A4.5 4.5 0 0 1 7 7z"/><path d="M7.5 10v4M5.5 12h4"/><circle class="solid" cx="15.5" cy="11" r="1"/><circle class="solid" cx="17.5" cy="13" r="1"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-game': GameTaskIcon
  }
}
