// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Waiting task icon. For tasks about: waiting, hourglass, pending, later, deadline, patience.
 *
 * @tag c2-task-icon-hourglass
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-hourglass')
export class HourglassTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M7 3h10v3.5a5 5 0 0 1-10 0zM7 21h10v-3.5a5 5 0 0 0-10 0z"/><path d="M5 3h14M5 21h14"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-hourglass': HourglassTaskIcon
  }
}
