// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Pantry task icon. For tasks about: pantry, jar, jam, honey, sauce, spices, condiments.
 *
 * @tag c2-task-icon-jar
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-jar')
export class JarTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<rect x="7" y="3" width="10" height="3" rx="1"/><path class="tone" d="M7.5 6h9l1 2.5V19a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2V8.5z"/><path d="M6.5 12h11M6.5 16.5h11"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-jar': JarTaskIcon
  }
}
