// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Like task icon. For tasks about: like, thumbs, up, approve, feedback, review, rate.
 *
 * @tag c2-task-icon-like
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-like')
export class LikeTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M7 10.5H4v10h3z"/><path d="M7 10.5l4-7.5a2 2 0 0 1 2.5 2l-.7 4h5.7a2 2 0 0 1 2 2.3l-1.2 7.5a2 2 0 0 1-2 1.7H7"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-like': LikeTaskIcon
  }
}
