// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * List task icon. For tasks about: list, items, outline, agenda.
 *
 * @tag c2-task-icon-list
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-list')
export class ListTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path d="M9 6h11M9 12h11M9 18h11"/><circle class="solid" cx="4.5" cy="6" r="1.3"/><circle class="solid" cx="4.5" cy="12" r="1.3"/><circle class="solid" cx="4.5" cy="18" r="1.3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-list': ListTaskIcon
  }
}
