// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Meditate task icon. For tasks about: meditate, yoga, mindfulness, breathe, calm, relax, zen.
 *
 * @tag c2-task-icon-meditate
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-meditate')
export class MeditateTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M12 5c2 2 3 4.5 3 7s-1 4.5-3 6c-2-1.5-3-3.5-3-6s1-5 3-7z"/><path d="M9.2 9.5C7 8.5 4.8 8.5 3 9c0 5 3.5 9 9 9s9-4 9-9c-1.8-.5-4-.5-6.2.5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-meditate': MeditateTaskIcon
  }
}
