// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Money task icon. For tasks about: money, cash, pay, salary, transfer, finance.
 *
 * @tag c2-task-icon-money
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-money')
export class MoneyTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<rect class="tone" x="2.5" y="6" width="19" height="12" rx="2"/><circle cx="12" cy="12" r="2.8"/><path d="M6 9.5v5M18 9.5v5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-money': MoneyTaskIcon
  }
}
