// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Note task icon. For tasks about: note, sticky, memo, jot, down, write.
 *
 * @tag c2-task-icon-note
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-note')
export class NoteTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M4 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v9.5L14.5 20H5a1 1 0 0 1-1-1z"/><path d="M20 14.5h-4.5a1 1 0 0 0-1 1V20M8 9h8M8 12.5h5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-note': NoteTaskIcon
  }
}
