// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Plants task icon. For tasks about: plants, water, houseplant, garden, pot, grow.
 *
 * @tag c2-task-icon-plant
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-plant')
export class PlantTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M6.5 14h11L16 21H8z"/><path d="M12 14V9M12 9c0-3 2-5 5.5-5 0 3-2 5-5.5 5zM12 11c0-2.5-1.8-4-4.5-4 0 2.5 1.8 4 4.5 4z"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-plant': PlantTaskIcon
  }
}
