// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Weather task icon. For tasks about: weather, rain, umbrella, forecast, storm.
 *
 * @tag c2-task-icon-rain
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-rain')
export class RainTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M7 15a4.5 4.5 0 0 1-.6-9A6 6 0 0 1 18 5.5a4.8 4.8 0 0 1-.5 9.5z"/><path d="M8 18l-1 2.5M12 18l-1 2.5M16 18l-1 2.5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-rain': RainTaskIcon
  }
}
