// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Report task icon. For tasks about: report, analytics, metrics, kpi, review, numbers, quarterly, summary.
 *
 * @tag c2-task-icon-report
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-report')
export class ReportTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M6 3h8l4 4v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M14 3v4h4M9 17.5v-3M12 17.5v-6M15 17.5V15"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-report': ReportTaskIcon
  }
}
