// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Restaurant task icon. For tasks about: restaurant, eat, out, dinner, lunch, reservation, book, table, food.
 *
 * @tag c2-task-icon-restaurant
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-restaurant')
export class RestaurantTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path d="M7 3v18M4.5 3v4.5a2.5 2.5 0 0 0 5 0V3"/><path class="tone" d="M17.5 21V3c-2 1.2-3 3.8-3 7v3.5h3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-restaurant': RestaurantTaskIcon
  }
}
