// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Launch task icon. For tasks about: launch, ship, release, deploy, go, live, rocket, start.
 *
 * @tag c2-task-icon-rocket
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-rocket')
export class RocketTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M12 15.5L8.5 12c1.5-4 4.5-8.5 12-9-.5 7.5-5 10.5-8.5 12.5z"/><path d="M8.5 12H5l2.5-3.5h4M12 15.5V19l3.5-2.5v-4M6.5 15.5C5 16 4 18 4 20c2 0 4-1 4.5-2.5"/><circle cx="15.5" cy="8.5" r="1.3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-rocket': RocketTaskIcon
  }
}
