// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Research task icon. For tasks about: research, search, find, look, up, investigate, explore.
 *
 * @tag c2-task-icon-search
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-search')
export class SearchTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<circle class="tone" cx="10.5" cy="10.5" r="6.5"/><path d="M15.5 15.5l5 5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-search': SearchTaskIcon
  }
}
