// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Server task icon. For tasks about: server, infrastructure, hosting, ops, devops, maintenance.
 *
 * @tag c2-task-icon-server
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-server')
export class ServerTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<rect class="tone" x="3" y="3.5" width="18" height="7" rx="2"/><rect class="tone" x="3" y="13.5" width="18" height="7" rx="2"/><circle class="solid" cx="7" cy="7" r="1"/><circle class="solid" cx="7" cy="17" r="1"/><path d="M11 7h6M11 17h6"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-server': ServerTaskIcon
  }
}
