// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Settings task icon. For tasks about: settings, configure, setup, preferences, admin, maintenance.
 *
 * @tag c2-task-icon-settings
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-settings')
export class SettingsTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M10.06 5.48L10.45 3.13L13.55 3.13L13.94 5.48L15.24 6.02L17.18 4.64L19.36 6.82L17.98 8.76L18.52 10.06L20.87 10.45L20.87 13.55L18.52 13.94L17.98 15.24L19.36 17.18L17.18 19.36L15.24 17.98L13.94 18.52L13.55 20.87L10.45 20.87L10.06 18.52L8.76 17.98L6.82 19.36L4.64 17.18L6.02 15.24L5.48 13.94L3.13 13.55L3.13 10.45L5.48 10.06L6.02 8.76L4.64 6.82L6.82 4.64L8.76 6.02z"/><circle cx="12" cy="12" r="2.8"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-settings': SettingsTaskIcon
  }
}
