// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Store task icon. For tasks about: store, shop, market, errand, pick, up, local, business.
 *
 * @tag c2-task-icon-shop
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-shop')
export class ShopTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="fill" d="M4 10h16v10a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z"/><path d="M4 10v10a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V10M3 4h18l1 4.5a2.5 2.5 0 0 1-5 0 2.5 2.5 0 0 1-5 0 2.5 2.5 0 0 1-5 0 2.5 2.5 0 0 1-5 0zM9.5 21v-5.5h5V21"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-shop': ShopTaskIcon
  }
}
