// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Toiletries task icon. For tasks about: toiletries, soap, shampoo, toothpaste, hygiene.
 *
 * @tag c2-task-icon-toiletries
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-toiletries')
export class ToiletriesTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M7 11h10v8.5a1.5 1.5 0 0 1-1.5 1.5h-7A1.5 1.5 0 0 1 7 19.5z"/><path d="M10 11V8h4v3M12 8V5h4v1.5M12 5H9.5"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-toiletries': ToiletriesTaskIcon
  }
}
