// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * DIY task icon. For tasks about: diy, toolbox, build, assemble, project, hardware.
 *
 * @tag c2-task-icon-toolbox
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-toolbox')
export class ToolboxTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<rect class="tone" x="2.5" y="8" width="19" height="12" rx="2"/><path d="M8.5 8V5.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1V8M2.5 13h19M7 11.5v3M17 11.5v3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-toolbox': ToolboxTaskIcon
  }
}
