// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Care task icon. For tasks about: care, volunteer, charity, help, donate, support, kindness.
 *
 * @tag c2-task-icon-volunteer
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-volunteer')
export class VolunteerTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path class="tone" d="M12 10.5s-4-2.4-4-5.1a2.2 2.2 0 0 1 4-1.1 2.2 2.2 0 0 1 4 1.1c0 2.7-4 5.1-4 5.1z"/><path d="M2.5 14.5h3l3.5 1.5h4a1.5 1.5 0 0 1 0 3H9M5.5 20.5l8.5 1 7-4.5a1.5 1.5 0 0 0-1.8-2.4L15 17"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-volunteer': VolunteerTaskIcon
  }
}
