// GENERATED by scripts/task-icon-generator from svg/. Do not edit by hand.
import { svg } from 'lit'
import { customElement } from '@c2n/core/element-helper.js'
import { TaskIconElement } from '../task-icon'

/**
 * Internet task icon. For tasks about: internet, wifi, network, router, connection.
 *
 * @tag c2-task-icon-wifi
 *
 * @cssproperty {length} [--c2-task-icon--size=24px] - Width and height of the icon.
 * @cssproperty {color} [--c2-task-icon--color=currentColor] - Outline and solid colour. Inherits the text colour by default.
 * @cssproperty {number} [--c2-task-icon--stroke-width=1.75] - Outline width, in units of the 24x24 canvas.
 * @cssproperty {color} [--c2-task-icon__tone--color=currentColor] - Colour of the soft duotone fill.
 * @cssproperty {number} [--c2-task-icon__tone--opacity=0.18] - Opacity of the soft duotone fill; 0 draws outlines only.
 */
@customElement('c2-task-icon-wifi')
export class WifiTaskIcon extends TaskIconElement {
  protected override renderIcon() {
    return svg`<path d="M2.5 9a14 14 0 0 1 19 0M5.5 12.5a9.5 9.5 0 0 1 13 0M8.5 16a5 5 0 0 1 7 0"/><circle class="solid" cx="12" cy="19.5" r="1.3"/>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'c2-task-icon-wifi': WifiTaskIcon
  }
}
