import { test, expect, props, watch, accessible, pointerClick } from '../../../../tests/component-fixture'

test('pointer and Space toggle once and publish the checked value', async ({ page, renderScenario }) => {
  await renderScenario('<c2-checkbox aria-label="Accept terms"></c2-checkbox>')
  const host = page.locator('c2-checkbox')
  const input = page.getByRole('checkbox', { name: 'Accept terms' })
  await watch(host, 'change')
  await input.check()
  await expect(host).toHaveJSProperty('checked', true)
  await input.press('Space')
  await expect(input).not.toBeChecked()
  await expect(host).toHaveAttribute('data-events', '[null,null]')
  await accessible(page)
})
test('mixed state clears on activation and property updates stay synchronized', async ({ page, renderScenario }) => {
  await renderScenario('<c2-checkbox aria-label="Select all" indeterminate></c2-checkbox>')
  const host = page.locator('c2-checkbox')
  const input = page.getByRole('checkbox')
  await expect(input).toHaveAttribute('aria-checked', 'mixed')
  await input.click()
  await expect(host).toHaveJSProperty('indeterminate', false)
  await props(host, { checked: false })
  await expect(input).not.toBeChecked()
  await props(host, { checked: true })
  await expect(input).toBeChecked()
})
test('disabled blocks clicks and host focus reaches the enabled input', async ({ page, renderScenario }) => {
  await renderScenario('<c2-checkbox aria-label="Accept" disabled></c2-checkbox>')
  const input = page.getByRole('checkbox')
  await pointerClick(input)
  await expect(input).not.toBeChecked()
  await props(page.locator('c2-checkbox'), { disabled: false })
  await page.locator('c2-checkbox').evaluate((el) => (el as HTMLElement).focus())
  await expect(input).toBeFocused()
})
