// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/masonry. Import once, anywhere in the program:
//
//     import '@c2n/masonry/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Masonry, MasonryEventMap } from '@c2n/masonry'
import type { MasonryItem } from '@c2n/masonry/masonry-item.js'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-masonry': DefineComponent<
      C2Props<Masonry> & {
        onLayoutError?: (event: MasonryEventMap['layout-error']) => void
        onLayoutChange?: (event: MasonryEventMap['layout-change']) => void
      }
    >
    'c2-masonry-item': DefineComponent<
      C2Props<MasonryItem> & {
        'item-id'?: unknown
        'cols-xs'?: unknown
        'cols-sm'?: unknown
        'cols-md'?: unknown
        'cols-lg'?: unknown
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
