// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/carousel. Import once, anywhere in the program:
//
//     import '@c2n/carousel/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Carousel, CarouselEventMap } from '@c2n/carousel'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-carousel': DefineComponent<
      C2Props<Carousel> & {
        'mouse-drag'?: unknown
        'previous-label'?: unknown
        'next-label'?: unknown
        'indicators-label'?: unknown
        'indicator-label-template'?: unknown
        'slide-label-template'?: unknown
        'play-label'?: unknown
        'pause-label'?: unknown
        onSlideChange?: (event: CarouselEventMap['slide-change']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
