// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/progress. Import once, anywhere in the program:
//
//     import '@c2n/progress/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Progress } from '@c2n/progress'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-progress': DefineComponent<
      C2Props<Progress> & {
        'show-value'?: unknown
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
