// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/toast. Import once, anywhere in the program:
//
//     import '@c2n/toast/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { Toast, ToastRegion } from '@c2n/toast'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>
/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */
type Attribute = string | number | boolean

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-toast': C2Props<Toast> & {
        'no-icon'?: Attribute
        'show-progress'?: Attribute
        'action-label'?: Attribute
        'close-label'?: Attribute
      }
      'c2-toast-region': C2Props<ToastRegion> & {
        'max-visible'?: Attribute
        'enter-animation'?: Attribute
        'exit-animation'?: Attribute
        'animation-duration'?: Attribute
        'show-progress'?: Attribute
      }
    }
  }
}

export {}
