// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/toast. Import once, anywhere in the program:
//
//     import '@c2n/toast/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { Toast, ToastEventMap, ToastRegion, ToastRegionEventMap } from '@c2n/toast'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes

declare module 'vue' {
  interface GlobalComponents {
    'c2-toast': DefineComponent<
      C2Props<Toast> & {
        'no-icon'?: unknown
        'show-progress'?: unknown
        'action-label'?: unknown
        'close-label'?: unknown
        onToastClose?: (event: ToastEventMap['toast-close']) => void
        onToastAction?: (event: ToastEventMap['toast-action']) => void
      }
    >
    'c2-toast-region': DefineComponent<
      C2Props<ToastRegion> & {
        'max-visible'?: unknown
        'enter-animation'?: unknown
        'exit-animation'?: unknown
        'animation-duration'?: unknown
        'show-progress'?: unknown
        onToastAction?: (event: ToastRegionEventMap['toast-action']) => void
        onToastDismiss?: (event: ToastRegionEventMap['toast-dismiss']) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
