// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// JSX types for the custom elements of @c2n/chart. Import once, anywhere in the program:
//
//     import '@c2n/chart/react'
//
// Register the elements at module scope before React renders, or React writes an object prop as an
// attribute and it stringifies.
//
// On a server-rendered page (Next.js, React Router SSR) write a camelCase property by its kebab-case attribute
// name ('row-key', not rowKey): the server emits props verbatim, HTML lowercases them, and hydration does not
// set properties. Those names are listed next to the properties below. Structured converter-backed values
// also accept their serialized string form, so server JSX can emit the same JSON/CSV attribute used by HTML.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { AreaChart } from '@c2n/chart/area-chart.js'
import type { BarChart } from '@c2n/chart/bar-chart.js'
import type { CandlestickChart } from '@c2n/chart/candlestick-chart.js'
import type { ChartLegend } from '@c2n/chart/chart-legend.js'
import type { ChartSeries } from '@c2n/chart/chart-series.js'
import type { ChartTooltip } from '@c2n/chart/chart-tooltip.js'
import type { GaugeChart } from '@c2n/chart/gauge-chart.js'
import type { LineChart } from '@c2n/chart/line-chart.js'
import type { PieChart } from '@c2n/chart/pie-chart.js'
import type { RadarChart } from '@c2n/chart/radar-chart.js'
import type { ScatterChart } from '@c2n/chart/scatter-chart.js'
import type { Sparkline } from '@c2n/chart/sparkline.js'

/** Standard React host-element attributes plus the element's own public properties. */
type C2Props<T> = DetailedHTMLProps<HTMLAttributes<T>, T> & Partial<Omit<T, keyof HTMLElement>>
/** What React writes to a custom element's attribute: true becomes the empty string, false removes it. */
type Attribute = string | number | boolean

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'c2-area-chart': Omit<C2Props<AreaChart>, 'series'> & {
        'fill-opacity'?: Attribute
        'y-min'?: Attribute
        'y-max'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: AreaChart['series'] | string
      }
      'c2-bar-chart': Omit<C2Props<BarChart>, 'series'> & {
        'bar-width'?: Attribute
        'bar-gap'?: Attribute
        'y-min'?: Attribute
        'y-max'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: BarChart['series'] | string
      }
      'c2-candlestick-chart': Omit<C2Props<CandlestickChart>, 'series'> & {
        'open-field'?: Attribute
        'close-field'?: Attribute
        'low-field'?: Attribute
        'high-field'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: CandlestickChart['series'] | string
      }
      'c2-chart-legend': C2Props<ChartLegend>
      'c2-chart-series': C2Props<ChartSeries> & {
        'line-width'?: Attribute
        'span-gaps'?: Attribute
      }
      'c2-chart-tooltip': C2Props<ChartTooltip>
      'c2-gauge-chart': Omit<C2Props<GaugeChart>, 'series'> & {
        'start-angle'?: Attribute
        'end-angle'?: Attribute
        'split-number'?: Attribute
        'value-suffix'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: GaugeChart['series'] | string
      }
      'c2-line-chart': Omit<C2Props<LineChart>, 'series'> & {
        'y-min'?: Attribute
        'y-max'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: LineChart['series'] | string
      }
      'c2-pie-chart': Omit<C2Props<PieChart>, 'series'> & {
        'inner-radius'?: Attribute
        'outer-radius'?: Attribute
        'start-angle'?: Attribute
        'label-content'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: PieChart['series'] | string
      }
      'c2-radar-chart': Omit<C2Props<RadarChart>, 'series'> & {
        'start-angle'?: Attribute
        'split-number'?: Attribute
        'fill-opacity'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: RadarChart['series'] | string
      }
      'c2-scatter-chart': Omit<C2Props<ScatterChart>, 'series'> & {
        'symbol-size'?: Attribute
        'large-threshold'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: ScatterChart['series'] | string
      }
      'c2-sparkline': Omit<C2Props<Sparkline>, 'series'> & {
        'y-min'?: Attribute
        'y-max'?: Attribute
        'x-field'?: Attribute
        'label-field'?: Attribute
        'x-type'?: Attribute
        'empty-message'?: Attribute
        'max-points'?: Attribute
        'lazy-render'?: Attribute
        series?: Sparkline['series'] | string
      }
    }
  }
}

export {}
