// GENERATED by @c2n/framework-types. Do not edit by hand.
//
// Vue template types for the custom elements of @c2n/todo-list. Import once, anywhere in the program:
//
//     import '@c2n/todo-list/vue'
//
// Tell the compiler about the tags as well, or every c2-* tag is resolved as a Vue component and renders
// nothing: template.compilerOptions.isCustomElement = (tag) => tag.startsWith('c2-') in vite.config.ts.

import type { DefineComponent, HTMLAttributes } from 'vue'
import type { EventMapOf } from '@c2n/core/event-helper.js'
import type { TodoList } from '@c2n/todo-list'

/** The element's own public properties, plus every attribute Vue understands on a host element. */
type C2Props<T> = Partial<Omit<T, keyof HTMLElement>> & HTMLAttributes
/** The event an element fires under `name`, read from the map its `addEventListener` carries (its own or inherited). */
type EventOf<T extends EventTarget, Name extends string> = Name extends keyof EventMapOf<T> ? EventMapOf<T>[Name] : CustomEvent

declare module 'vue' {
  interface GlobalComponents {
    'c2-todo-list': DefineComponent<
      C2Props<TodoList> & {
        'heading-level'?: unknown
        'storage-key'?: unknown
        'persist-tasks'?: unknown
        onLookChange?: (event: EventOf<TodoList, 'look-change'>) => void
        onTasksChange?: (event: EventOf<TodoList, 'tasks-change'>) => void
        onTaskToggle?: (event: EventOf<TodoList, 'task-toggle'>) => void
        onTaskAdd?: (event: EventOf<TodoList, 'task-add'>) => void
        onTaskRemove?: (event: EventOf<TodoList, 'task-remove'>) => void
        onTaskChange?: (event: EventOf<TodoList, 'task-change'>) => void
      }
    >
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Vue's own definition omits it, and slotting a plain element into a component needs it. */
    slot?: string
  }
}

export {}
